ifit.mccode.org - Description of iLoad
Home > Libraries > Loaders > iLoad.m
iFit/iLoad
PURPOSE
[data, loader] = iLoad(file, loader, ...)
SYNOPSIS
function [data, format] = iLoad(filename, loader, varargin)
DESCRIPTION
 [data, loader] = iLoad(file, loader, ...)
 imports any data into Matlab.
 The file formats cache and MeX files can be rebuilt/checked with
   iLoad force         update loaders cache and check importers
   iLoad compile       force compilation of external importers (MeX)
   iLoad save          save the cache to the user Preferences
   iLoad config        get the loaders list as a configuration structure
   iLoad formats       list of all supported file formats
 The iLoad_ini configuration file can be loaded and saved in the Preference
 directory using
   [config, configfile] = iLoad('load config').
   [config, configfile] = iLoad(config,'save config')
   Default supported formats include: any text based including CSV, Lotus1-2-3, SUN sound,
     WAV sound, AVI movie, NetCDF, FITS, XLS, BMP GIF JPEG TIFF PNG ICO images,
     HDF4, HDF5, MAT workspace, XML, CDF, JSON, YAML, IDL
   Other specialized formats include: McStas, ILL, SPEC, ISIS/SPE, INX, EDF, Mantid.
     SIF, MCCD/TIFF, ADSC, CBF, Analyze, NifTI, STL,PLY,OFF, CIF/CFL,
     EZD/CCP4, Bruker Varian and JEOL NMR formats, Bruker OPUS, LabView LVM and TDMS,
     Agilent and Thermo Finnigan MS, Quantum Design VMS, ENDF
   Compressed files are also supported, with on-the-fly extraction (zip, gz, tar, Z).
   Distant files are supported through e.g. URLs such as
     file://, ftp:// http:// and https://
   File names may end with an internal anchor reference '#anchor", as used in HTML
     links, in which case the members matching the anchor are returned.
 input arguments:
   file:   file name, or cell of file names, or any Matlab variable, or a URL
             or an empty string (then pops'up a file selector)
   loader: a function name to use as import routine, OR a structure with:
             loader = 'auto' (default)
             loader = 'gui' (asks for the format to use)
             loader.method = 'function name'
             loader.options= string of options to catenate after file name
                          OR cell of options to use as additional arguments
                             to the method
           leave it empty ('') for automatic setting.
   additional arguments are passed to the import routine.
 output variables:
   data:   a single structure containing file data, or a cell of structures
   loader: the loader that was used for importation, or a cell of loaders.
 example: iLoad; iLoad('file'); iLoad('http://path/name'); iLoad('file.zip')
          iLoad('file#anchor');
 See also: importdata, load, iLoad_ini, Loaders
 Part of: Loaders utilities (ILL library)
 Author:  E. Farhi <farhi@ill.fr>.
 Version: oct.. 23, 2018
 (c) E.Farhi, ILL. License: EUPL.
CROSS-REFERENCE INFORMATION
This function calls:
class2str This function creates a string containing Matlab code describing a variable.
iLoad [data, loader] = iLoad(file, loader, ...)
iLoad_ini config = iLoad_ini User definitions of specific import formats to be used by iLoad
ifitpath ifitpath iFit library location
read_anytext import any text using 'looktxt'.
read_cbf Read CBF/imgCIF x-ray file format
uigetfiles uigetfiles: Multiple open file dialog box
This function is called by:
iLoad [data, loader] = iLoad(file, loader, ...)