ifit.mccode.org - Description of ff_core_shell
Home > Scripts > Models > Specialized > ff_core_shell.m
iFit/ff_core_shell
PURPOSE
y = ff_core_shell(p, x, [y]) : Spherical/core shell form factor [Guinier]
SYNOPSIS
function y=ff_core_shell(varargin)
DESCRIPTION
 y = ff_core_shell(p, x, [y]) : Spherical/core shell form factor [Guinier]
   iFunc/ff_core_shell concentric spherical geometry, with 2 shells
     The 'x' wave-vector/momentum axis is usually in nm-1 or Angs-1.
     The parameters R1,R2 are given in inverse unit of the axis (i.e nm or Angs).
     Typical values for parameters are R1,R2=10-100 Angs, eta1,eta2=1e-6.
     When eta2=0, the model is equivalent to ff_sphere.
     Ref: Guinier, A. and G. Fournet, "Small-Angle Scattering of X-Rays",
            John Wiley and Sons, New York, (1955).
          Extracted from sasfit/sasfit_ff/sasfit_ff_spherical_shell.c
     I. Bressler, et al, Journal of Applied Crystallography, 2015, 48 (5), 1587-1598
 input:  p: sphere model parameters (double)
            p = [ R1=Shell_Radius R2=core_radius eta1=SLD shell/matrix eta2=SLD core/shell ]
          or 'guess'
         x: wave-vector/momentum axis (double, e.g. nm-1 or Angs-1)
         y: when values are given and p='guess', a guess of the parameters is performed (double)
 output: y: model value (intensity)
 ex:     y=ff_core_shell([14 11 0.1 0.1], 0:0.01:1); or plot(ff_core_shell,[14 11 0.1 0.],0:0.01:1)
 Version: oct.. 23, 2018
 See also iFunc, iFunc/fits, iFunc/plot, ff_sphere
 (c) E.Farhi, ILL. License: EUPL.
CROSS-REFERENCE INFORMATION
This function calls:
ff_sphere y = ff_sphere(p, x, [y]) : Sphere form factor [Guinier]
ff_sphere y = ff_sphere(p, x, [y]) : Sphere form factor [Guinier]
ff_sphere y = ff_sphere(p, x, [y]) : Sphere form factor [Guinier]
This function is called by: