ifit.mccode.org - Description of doc
Home > Objects > @iFunc > doc.m
iFit/doc
PURPOSE
doc(iFunc): iFunc web page documentation
SYNOPSIS
function d = doc(a, page)
DESCRIPTION
 doc(iFunc): iFunc web page documentation
   @iFunc/doc: web page documentation
     Open the iFunc documentation.
     doc(iFunc,page) opens a specific documentation page
     doc(iFunc,'Load')
     doc(iFunc,'Save')
     doc(iFunc,'Math')
     doc(iFunc,'Fit')
     doc(iFunc,'Plot')
     doc(iFunc,'Methods')
 Version: oct.. 23, 2018
CROSS-REFERENCE INFORMATION
This function calls:
doc doc(iFunc): iFunc web page documentation
isempty isempty(s) : true for empty iFunc object
This function is called by:
doc doc(iFunc): iFunc web page documentation