ifit.mccode.org - Description of fix
Home > Objects > @iFunc > fix.m
iFit/fix
PURPOSE
b = fix(s, parameters, ...) : sets parameter lock (fix) for further fit using the model 's'
SYNOPSIS
function a = fix(a, varargin)
DESCRIPTION
 b = fix(s, parameters, ...) : sets parameter lock (fix) for further fit using the model 's'
   @iFunc/mlock lock model parameters during further fit process.
     to lock/fix a parameter model, use fix(model, parameter)
   To lock/fix a set of parameters, you may use a regular expression as:
     fix(model, regexp(model.Parameters, 'token1|token2|...'))
   fix(model, {'Parameter1', 'Parameter2', ...})
     lock/fix parameter for further fits
   fix(model)
     display fixed parameters
   fix(model,'all')
     fix/lock all parameters
   fix(model,'none')
     free/unlock all parameters
 input:  s: object or array (iFunc)
         parameters: names or index of parameters to lock/fix (char or scalar)
 output: b: object or array (iFunc)
 ex:     b=fix(a,'Intensity');
 Version: oct.. 23, 2018
 See also iFunc, iFunc/fits, iFunc/munlock, iFunc/xlim
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty(s) : true for empty iFunc object
mlock b = mlock(s, parameters, ...) : sets parameter lock (fix) for further fit using the model 's'
This function is called by:
iFunc