ifit.mccode.org - Description of publish
Home > Objects > @iFunc > publish.m
iFit/publish
PURPOSE
b = publish(s) : export the Model object as an HTML document.
SYNOPSIS
function filename = publish(a, filename, section, message)
DESCRIPTION
 b = publish(s) : export the Model object as an HTML document.
   @iFunc/publish function to export an object into a readable document.
   publish(a)        export to a temporary directory and open the web browser
   publish(a, file)  export to given file name
   publish(a, dir)   export to given directory
   publish(a, file, sections) export only the given sections as char or cell
     default sections are {'header','parameters','model','expression','footer'};
     optional section:     'download','message'
   publish(a, file, section, message)
     write a specified section with additional label/text in 'message'.
   publish(a, file, 'force')
     overwrites any existing document (default is to append)
 When the generated report file already exists, the new document is appended.
 The resulting document file name is stored as:
   a.UserData.options.report
 input:  a: object or array (iFunc)
         filename: a file name or directory where to export. When not given
           the exportation takes place in the local directory.
         section: a list of sections to generate. The default is
           {'header','plot','expression','footer'}.
            'download' and 'message' can be added.
         message: an additional label for the section.
 output: b: generated filename
 ex:     publish(gauss)
 Version: oct.. 23, 2018
 See also iFunc, iFunc/save
CROSS-REFERENCE INFORMATION
This function calls:
cellstr ret = cellstr(s) : convert iFunc into a cell of strings
char ret = char(s) : convert iFunc into character
disp disp(s) : display iFunc object (details)
findfield [match, types, nelements]=findfield(iFunc, field, option) : look for iFunc fields
get [...] = get(s, 'PropertyName', ...) : get iFunc object properties
isempty isempty(s) : true for empty iFunc object
isfield b = isfield(s, field) : check existence of field/parameter in model objects
plot h = plot(model, parameters, axes, ...) plot a model
publish b = publish(s) : export the Model object as an HTML document.
save f = save(s, filename, format, options) : save iFunc object into various data formats
saveas f = saveas(s, filename, format, options) : save iFunc object into various data formats
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iFunc properties
This function is called by:
publish b = publish(s) : export the Model object as an HTML document.
saveas f = saveas(s, filename, format, options) : save iFunc object into various data formats