ifit.mccode.org - Description of abs
Home > Objects > @iData > abs.m
iFit/abs
PURPOSE
b = abs(s) : absolute value of iData object
SYNOPSIS
function a = abs(a)
DESCRIPTION
 b = abs(s) : absolute value of iData object
   @iData/abs function to return the absolute value of data sets
   This function computes the absolute value/modulus of the object 's'.
 input:  s: object or array (iData)
 output: b: object or array (iData)
 ex:     b=abs(a);
 Version: oct.. 23, 2018
 See also iData, iData/uminus, iData/abs, iData/real, iData/imag, iData/uplus
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
colon b = colon(s) : vector of arrays
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
gradient g = gradient(a, dim) : computes the gradient (derivative) of iData objects
interp [b...] = interp(s, ...) : interpolate iData object
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
std [half_width, center] = std(s, dim) : standard deviation of iData
subsref b = subsref(a,s) : iData indexed references