ifit.mccode.org - Description of camproj
Home > Objects > @iData > camproj.m
iFit/camproj
PURPOSE
s = camproj(a,dim) : projection/radial integration of iData objects elements
SYNOPSIS
function s = camproj(a,dim, center)
DESCRIPTION
 s = camproj(a,dim) : projection/radial integration of iData objects elements
   @iData/camproj function to compute the projection/sum of the elements of the data set
     camproj(a,dim) projects along axis of rank dim. All other axes are removed.
       If dim=0, projection is done on all axes and the total is returned as a
         scalar value.
       camproj(a,1) projects on first dimension (rows).
       camproj is the complementary to sum.
     camproj(a,'radial') computes the radial integration (R=sqrt(sum(axes^2)).
       the 'center' of the distribution (1st moment) is used as symmetry point
       for the computation of the radius.
     camproj(a,'radial', center) specifies the 'center' of the integration
       (vector of coordinates) or a single value used as center on all axes
       (for instance 0). All axes are assumed to be distances.
     The radial distribution can then be transformed into an histogram with
     e.g. hist(camproj(a), 100);
 input:  a:     object or array (iData/array of)
         dim:   dimension rank to project to (int or 'radial')
         center:scalar or a vector which length is the object dimensionality
 output: s: projection of elements (iData 1D/scalar)
 ex:     c=camproj(a); hist(c, 100);
 Version: oct.. 23, 2018
 See also iData, iData/rotate, iData/sum, iData/trapz, iData/cart2sph
CROSS-REFERENCE INFORMATION
This function calls:
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
isempty isempty(s) : true for empty iData object
isnumeric b = isnumeric(s) : True for numeric iData object elements
label b = label(s, alias, label) : Change iData label for a given alias/axis
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
ndims d = ndims(s) : get the dimensionality of iData object
ones s = ones(s,N,M,P,...) : initialize an iData array
reshape c = reshape(a) : reshape the object Signal
rmaxis s = rmaxis(s, Axis) : delete iData axes
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
sqrt b = sqrt(s) : square root value of iData object
std [half_width, center] = std(s, dim) : standard deviation of iData
xlabel b = xlabel(s,label) : Change iData X axis label
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
mean b = mean(s, dim) : mean value of iData object
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
sum s = sum(a,dim) : computes the sum of iData objects elements