ifit.mccode.org - Description of cart2sph
Home > Objects > @iData > cart2sph.m
iFit/cart2sph
PURPOSE
s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
SYNOPSIS
function s = cart2sph(a, center)
DESCRIPTION
 s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
   @iData/cart2sph function to
     cart2sph(a) Transforms the object axes into spherical coordinates, which
       allow radial integration aferwards.
       The 'center' of the distribution (1st moment) is used as symmetry point
       for the computation of the radius. All axes are considered to be
       distances.
     cart2sph(a,center) specifies the 'center' of the integration
       (vector of coordinates) or a single value used as center on all
       axes (for instance 0).
 input:  a:     object or array (iData/array of)
         center:scalar or a vector which length is the object dimensionality
 output: s: object with cartesian/spherical (iData)
 ex:     c=cart2sph(a);
 Version: oct.. 23, 2018
 See also iData, iData/rotate, iData/sum, iData/trapz, iData/camproj
CROSS-REFERENCE INFORMATION
This function calls:
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
isempty isempty(s) : true for empty iData object
isnumeric b = isnumeric(s) : True for numeric iData object elements
isvector b = isvector(s) : True for vector iData object
label b = label(s, alias, label) : Change iData label for a given alias/axis
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
ndims d = ndims(s) : get the dimensionality of iData object
ones s = ones(s,N,M,P,...) : initialize an iData array
reshape c = reshape(a) : reshape the object Signal
rmaxis s = rmaxis(s, Axis) : delete iData axes
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
sqrt b = sqrt(s) : square root value of iData object
std [half_width, center] = std(s, dim) : standard deviation of iData
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
trapz s = trapz(a,dim) : computes the integral of iData objects elements along given dimension