ifit.mccode.org - Description of cat
Home > Objects > @iData > cat.m
iFit/cat
PURPOSE
s = cat(dim,a,...) : catenate iData objects elements along dimension
SYNOPSIS
function b = cat(varargin)
DESCRIPTION
 s = cat(dim,a,...) : catenate iData objects elements along dimension
   @iData/cat function to catenate iData objects elements along dimension dim
     cat(dim,a,b,c,...) catenates along axis of rank dim. The axis is then extended.
     cat(1,a,...) accumulates on first dimension (columns)
     cat(a,b...)  accumulates on first dimension (columns) (uses dim=1)
     cat(0,a,...) catenates objects along a new dimension (dim = ndims(a)+1)
 input:  a: object or array (iData/array of)
         dim: dimension to accumulate (int)
 output: s: catenated data set (iData)
 ex:     c=cat(1,a,b); c=cat(1,[ a b ]);
 Version: oct.. 23, 2018
 See also iData, iData/plus, iData/prod, iData/cumcat, iData/mean
CROSS-REFERENCE INFORMATION
This function calls:
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
cell [content,fields]=cell(s) : convert iData objects into cells
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
interp [b...] = interp(s, ...) : interpolate iData object
isempty isempty(s) : true for empty iData object
isnumeric b = isnumeric(s) : True for numeric iData object elements
isscalar b = isscalar(s) : True for scalar iData objects
isvector b = isvector(s) : True for vector iData object
label b = label(s, alias, label) : Change iData label for a given alias/axis
ndims d = ndims(s) : get the dimensionality of iData object
ones s = ones(s,N,M,P,...) : initialize an iData array
reshape c = reshape(a) : reshape the object Signal
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
This function is called by:
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
combine c = combine(a,b) : combines iData objects
pca [b] = pca(X, k) : Principal component analysis of iData object(s)