ifit.mccode.org - Description of caxis
Home > Objects > @iData > caxis.m
iFit/caxis
PURPOSE
c = caxis(s, h) : Use the 2D/3D data as the colormap (CData property) in current object.
SYNOPSIS
function c = caxis(a, h)
DESCRIPTION
 c = caxis(s, h) : Use the 2D/3D data as the colormap (CData property) in current object.
   @iData/caxis function to use the current object as the colomap (CData).
     The iData object is automatically rescaled in order to match the current
       surface/view axes.
 input:  s: object or array (iData)
         h: surface or figure  (handle)
 output: c: graphics object handles that have been modified (handle array)
 ex:     a=iData(peaks); plot(a); caxis(del2(a));
 Version: oct.. 23, 2018
 See also iData, iData/plot
CROSS-REFERENCE INFORMATION
This function calls:
caxis c = caxis(s, h) : Use the 2D/3D data as the colormap (CData property) in current object.
double d = double(s) : convert iData into doubles
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
isempty isempty(s) : true for empty iData object
isvector b = isvector(s) : True for vector iData object
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
ndims d = ndims(s) : get the dimensionality of iData object
ones s = ones(s,N,M,P,...) : initialize an iData array
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
size size(s) : get iData object size (number of elements)
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
caxis c = caxis(s, h) : Use the 2D/3D data as the colormap (CData property) in current object.