ifit.mccode.org - Description of clim
Home > Objects > @iData > clim.m
iFit/clim
PURPOSE
b = clim(s,[ cmin cmax ]) : Reduce iData C axis limits
SYNOPSIS
function a = clim(a, lims, exclude)
DESCRIPTION
 b = clim(s,[ cmin cmax ]) : Reduce iData C axis limits
   @iData/clim function to reduce the C axis (rank 4) limits
     clim(s) returns the current C axis limits.
     Undefined axis returns [NaN NaN] as limits.
   clim(s, [min max], 'exclude') removes the specified range instead of keeping it.
 input:  s: object or array (iData)
         limits: new axis limits (vector)
 output: b: object or array (iData)
 ex:     b=clim(a);
 Version: oct.. 23, 2018
 See also iData, iData/plot, iData/ylabel
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
isempty isempty(s) : true for empty iData object
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
reshape c = reshape(a) : reshape the object Signal
size size(s) : get iData object size (number of elements)
subsref b = subsref(a,s) : iData indexed references
This function is called by: