ifit.mccode.org - Description of colormap
Home > Objects > @iData > colormap.m
iFit/colormap
PURPOSE
h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
SYNOPSIS
function h = colormap(varargin)
DESCRIPTION
 h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
 h=colormap(z1,cm1, z2, cm2, ...)
   Produces surfaces with different colormaps.
   iData 2D object z1 is plotted as surface 1, which is coloured with map cm1 (Nx3)
 h=colormap(z1, z2, ...)
   Same as above with a set of default colormaps
 h=colormap(..., options)
   Options specify the type of plot rendering (same as used in iData/plot)
   Any string argument will be interpreted as an 'option' for the 2D iData/plot
                 surf, mesh, contour, contour3, surfc, surfl, contourf
                 plot3, scatter3 (colored points), stem3, pcolor, waterfall
                 flat, interp, faceted (for shading), view2, view3
                 transparent, light, clabel, colorbar, shifted (overlayed 2D)
                 axis tight, axis auto, hide_axes (compact layout)
                 painters (bitmap drawing), zbuffer (vectorial drawing)
                 whole (do not reduce large object size for plotting)
 In addition, the 'log' option can be used to employ a log-scale color set
   which enhances contrast on low signal values in the plot.
 Available colormaps are:
    hsv        - Hue-saturation-value color map.
    hot        - Black-red-yellow-white color map.
    gray       - Linear gray-scale color map.
    bone       - Gray-scale with tinge of blue color map.
    copper     - Linear copper-tone color map.
    pink       - Pastel shades of pink color map.
    white      - All white color map.
    flag       - Alternating red, white, blue, and black color map.
    lines      - Color map with the line colors.
    colorcube  - Enhanced color-cube color map.
    vga        - Windows colormap for 16 colors.
    jet        - Variant of HSV.
    prism      - Prism color map.
    cool       - Shades of cyan and magenta color map.
    autumn     - Shades of red and yellow color map.
    spring     - Shades of magenta and yellow color map.
    winter     - Shades of blue and green color map.
    summer     - Shades of green and yellow color map.
 input: z1,z2,...:   iData objects (single or arrays)
        cm1, cm2...: colormaps (Mx3 matrices, such as jet)
        options:     string specifying the type of rendering for iData/plot.
 output: h:          graphics object handles (cell/array)
 example: a=iData(feval(gauss2d)); colormap(a,jet,a+1,hsv,'log transparent')
 Version: oct.. 23, 2018
 See also iData, iData/plot, iData/surf, iData/caxis
CROSS-REFERENCE INFORMATION
This function calls:
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
double d = double(s) : convert iData into doubles
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
isempty isempty(s) : true for empty iData object
isnumeric b = isnumeric(s) : True for numeric iData object elements
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
log b = log(s) : natural logarithm value of iData object
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
ndims d = ndims(s) : get the dimensionality of iData object
prod s = prod(a,dim) : computes the product of iData objects elements
reducevolume h = reducevolume(s, factor) : reduce an iData object size
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
size size(s) : get iData object size (number of elements)
strfind [match, field]=strfind(s, pattern, option) : search for pattern in iData
surf h = surf(s,option) : Plot a 2D/3D object as surface
title b = title(s,label) : Change iData Signal label
xlabel b = xlabel(s,label) : Change iData X axis label
ylabel b = ylabel(s,label) : Change iData Y axis label
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps