ifit.mccode.org - Description of colon
Home > Objects > @iData > colon.m
iFit/colon
PURPOSE
b = colon(s) : vector of arrays
SYNOPSIS
function c = colon(a,d,b)
DESCRIPTION
 b = colon(s) : vector of arrays
   @iData/colon create a vector of objects by varying their mean value,
     using linspace with a number of steps corresponding to the mean value range.
 input:  s: object (iData)
 output: b: object (iData)
 ex:     c=a:b; c=a:2:b;
 Version: oct.. 23, 2018
 See also iData, iData/floor, iData/ceil, iData/round, iData/combine
CROSS-REFERENCE INFORMATION
This function calls:
abs b = abs(s) : absolute value of iData object
ceil b = ceil(s) : upper integer round of iData object
end b = end(s,index,n) : end value for iData objects
floor b = floor(s) : lower integer round of iData object
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
isempty isempty(s) : true for empty iData object
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
mean b = mean(s, dim) : mean value of iData object
This function is called by: