ifit.mccode.org - Description of copyobj
Home > Objects > @iData > copyobj.m
iFit/copyobj
PURPOSE
b = copyobj(s) : makes a copy of iData object
SYNOPSIS
function a = copyobj(a)
DESCRIPTION
 b = copyobj(s) : makes a copy of iData object
   @iData/copyobj function to return a duplicate of data sets.
   creates a new iData object with same content as 'a', but different Tag/ID and Date.
 input:  s: object or array (iData)
 output: b: object or array (iData)
 ex:     b=copyobj(a);
 Version: oct.. 23, 2018
 See also iData, iData/uplus, iData/findobj
CROSS-REFERENCE INFORMATION
This function calls:
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
iData
reshape c = reshape(a) : reshape the object Signal
size size(s) : get iData object size (number of elements)
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
copyobj b = copyobj(s) : makes a copy of iData object
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
event c = event(a) : build an event list
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
fill FILL fill-in over missing data
gradient g = gradient(a, dim) : computes the gradient (derivative) of iData objects
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
imroi imroi: define a region of interest on a data set
interp [b...] = interp(s, ...) : interpolate iData object
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
logspace v = logspace(a,b,n) : creates a logarithmically spaced vector of objects
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
mean b = mean(s, dim) : mean value of iData object
median b = median(s, dim) : median value of iData object
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
mtimes c = mtimes(a,b) : computes the matrix product of iData objects
pack b = pack(a) : compress iData storage to save memory
pca [b] = pca(X, k) : Principal component analysis of iData object(s)
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
reducevolume h = reducevolume(s, factor) : reduce an iData object size
resize c = resize(a) : resize/rebin the object Signal
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
smooth Z = smooth(Y) : smooth iData objects
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
subsref b = subsref(a,s) : iData indexed references
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
zeros s = zeros(s,N,M,P,...) : initialize an iData array