ifit.mccode.org - Description of corrcoef
Home > Objects > @iData > corrcoef.m
iFit/corrcoef
PURPOSE
c = corrcoef(a,b) : correlation coefficient with an iData object
SYNOPSIS
function c = corrcoef(a, b)
DESCRIPTION
 c = corrcoef(a,b) : correlation coefficient with an iData object
   @iData/corrcoef function to compute the correlation of an object with other data
     http://en.wikipedia.org/wiki/Correlation_coefficient
 input:  a: iData or iFunc object, or numerical vector
         b: iData or iFunc object, or numerical vector
 output: c: correlation coefficient between -1 and 1
 ex:     b=corrcoef(a); c=corrcoef(a, gauss);
 Version: oct.. 23, 2018
 See also corrcoef, iData, iData/mean, iData/fits
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
corrcoef c = corrcoef(a,b) : correlation coefficient with an iData object
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
intersect [ai,bi] = intersect(a, b) : computes object intersection area and values
isfinite b = isfinite(s) : True for finite iData object elements
isnumeric b = isnumeric(s) : True for numeric iData object elements
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
ndims d = ndims(s) : get the dimensionality of iData object
reshape c = reshape(a) : reshape the object Signal
size size(s) : get iData object size (number of elements)
This function is called by:
corrcoef c = corrcoef(a,b) : correlation coefficient with an iData object