ifit.mccode.org - Description of deconv
Home > Objects > @iData > deconv.m
iFit/deconv
PURPOSE
c = deconv(a,b) : computes the deconvolution of iData objects
SYNOPSIS
function c = deconv(a,b, shape)
DESCRIPTION
 c = deconv(a,b) : computes the deconvolution of iData objects
   @iData/deconv function to compute the deconvolution of data sets (FFT based).
     When used with a single scalar value, it is used as a width to build a
       gaussian function, with same width along all dimensions
     When used with a vector of same length as the object dimension, a nD
       gaussian function with width as vector elements along each diemsions
     The second argument 'b' should better be centred, normalised, without background.
 input:  a: object or array (iData or numeric)
         b: object or array (iData or numeric or scalar)
     shape: optional shape of the return value
          deconv       Performs an FFT deconvolution.
          deconv_iter  Performs an iterative deconvolution.
          full         Returns the full two-dimensional convolution.
          same         Returns the central part of the convolution of the same size as a.
          valid        Returns only those parts of the convolution that are computed
                       without the zero-padded edges. Using this option, y has size
                       [ma-mb+1,na-nb+1] when all(size(a) >= size(b)).
          pad          Pads the 'a' signal by replicating its starting/ending values
                       in order to minimize the convolution side effects
          center       Centers the 'b' filter so that convolution does not shift
                       the 'a' signal.
          normalize    Normalizes the 'b' filter so that the convolution does not
                       change the 'a' signal integral.
          background   Remove the background from the filter 'b' (subtracts the minimal value)
     Default shape is 'deconv same'
 output: c: object or array (iData)
 ex:     c=deconv(a,b); c=deconv(a,b, 'fft same pad background center normalize');
 Version: oct.. 23, 2018
 See also iData, iData/times, iData/convn, iData/fft, iData/xcorr, fconv, fconvn, fxcorr, conv, deconv
CROSS-REFERENCE INFORMATION
This function calls:
double d = double(s) : convert iData into doubles
end b = end(s,index,n) : end value for iData objects
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
isempty isempty(s) : true for empty iData object
isscalar b = isscalar(s) : True for scalar iData objects
mean b = mean(s, dim) : mean value of iData object
ndims d = ndims(s) : get the dimensionality of iData object
strfind [match, field]=strfind(s, pattern, option) : search for pattern in iData
This function is called by: