ifit.mccode.org - Description of disp
Home > Objects > @iData > disp.m
iFit/disp
PURPOSE
disp(s) : display iData object (details)
SYNOPSIS
function disp(s_in, name, flat)
DESCRIPTION
 disp(s) : display iData object (details)
   @iData/disp function to display iData object details
 input:  s: object or array (iData)
 ex:     'disp(iData)'
 Version: oct.. 23, 2018
 See also iData, iData/display, iData/get
CROSS-REFERENCE INFORMATION
This function calls:
char c = char(s) : convert iData into character
disp disp(s) : display iData object (details)
end b = end(s,index,n) : end value for iData objects
full b = full(s) : Convert iData object storage to full matrix
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
isempty isempty(s) : true for empty iData object
islogical b = islogical(s) : True for logical iData object elements
isnumeric b = isnumeric(s) : True for numeric iData object elements
issparse b = issparse(s) : True for sparse matrix iData object
isvector b = isvector(s) : True for vector iData object
label b = label(s, alias, label) : Change iData label for a given alias/axis
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
mean b = mean(s, dim) : mean value of iData object
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
ndims d = ndims(s) : get the dimensionality of iData object
not b = not(s) : computes the logical 'not' of iData object
prod s = prod(a,dim) : computes the product of iData objects elements
size size(s) : get iData object size (number of elements)
std [half_width, center] = std(s, dim) : standard deviation of iData
sum s = sum(a,dim) : computes the sum of iData objects elements
transpose b = transpose(s) : non-conjugate transpose of iData object
This function is called by:
commandhistory commandhistory(s) : show the command history of iData object
disp disp(s) : display iData object (details)
doc doc(iData): iData web page documentation
edit edit(s) : edit iData object Signal/Monitor
get [...] = get(s, 'PropertyName', ...) : get iData object properties
help c = help(s) : display iData information as a Dialogue window
iData
imroi imroi: define a region of interest on a data set
load d = load(s, file, loader, ...): iData file loader
saveas f = saveas(s, filename, format, options) : save iData object into various data formats
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties