ifit.mccode.org - Description of dog
Home > Objects > @iData > dog.m
iFit/dog
PURPOSE
s= dog(dim,a) : split iData objects elements along dimension
SYNOPSIS
function s = dog(dim,a, varargin)
DESCRIPTION
 s= dog(dim,a) : split iData objects elements along dimension
   @iData/dog function to split iData objects elements along dimension dim
     dog(dim,a) split along axis of rank dim, which must be within dimensionality.
     Resulting split objects are returned within an array. This method is the counterpart to cat.
 input:  a: object or array (iData)
         dim: dimension to split (int)
 output: s: split data set (iData array)
 ex:     c=dog(1,a,b); c=dog(1,[ a b ]);
 Version: oct.. 23, 2018
 See also iData, iData/plus, iData/prod, iData/cumcat, iData/mean
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
dog s= dog(dim,a) : split iData objects elements along dimension
end b = end(s,index,n) : end value for iData objects
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
ndims d = ndims(s) : get the dimensionality of iData object
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
subsref b = subsref(a,s) : iData indexed references
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
dog s= dog(dim,a) : split iData objects elements along dimension