ifit.mccode.org - Description of end
Home > Objects > @iData > end.m
iFit/end
PURPOSE
b = end(s,index,n) : end value for iData objects
SYNOPSIS
function b = end(s,k,n)
DESCRIPTION
 b = end(s,index,n) : end value for iData objects
   @iData/end function defines end value for iData
   returns the length of rank 'index' among total dimensions 'n' in object 's'.
 Version: oct.. 23, 2018
 See also iData
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
ndims d = ndims(s) : get the dimensionality of iData object
prod s = prod(a,dim) : computes the product of iData objects elements
size size(s) : get iData object size (number of elements)
This function is called by:
avifile f = avifile(s, filename, options) : save iData object into a movie
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
caxis c = caxis(s, h) : Use the 2D/3D data as the colormap (CData property) in current object.
cell [content,fields]=cell(s) : convert iData objects into cells
char c = char(s) : convert iData into character
circshift b=circshift(a, rank, shift): shifts the axis of specified rank by a value
clabel b = clabel(s,label) : Change iData C axis label
clim b = clim(s,[ cmin cmax ]) : Reduce iData C axis limits
colon b = colon(s) : vector of arrays
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
combine c = combine(a,b) : combines iData objects
commandhistory commandhistory(s) : show the command history of iData object
contour h = contour(s,option) : Plot a 2D/3D object as contour
contour3 h = contour3(s,option) : Plot a 2D/3D object as 3D contour
contourf h = contourf(s,option) : Plot a 2D/3D object as filled contour
conv c = conv(a,b) : computes the convolution of iData objects
convn c = convn(a,b) : computes the convolution of an iData object with a response function
copyobj b = copyobj(s) : makes a copy of iData object
corrcoef c = corrcoef(a,b) : correlation coefficient with an iData object
csvwrite f = csvwrite(s, filename, options) : save iData object into a Comma Separated Values (CSV) file
ctranspose b = ctranspose(s) : complex conjugate transpose of iData object
cumprod s = cumprod(a,dim) : computes the cumulative product of iData objects elements
cumsum s = cumsum(a,dim) : computes the cumulative sum of iData objects elements
cumtrapz s = cumtrapz(a,dim) : computes the cumulative product of iData objects elements
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
deconv c = deconv(a,b) : computes the deconvolution of iData objects
disp disp(s) : display iData object (details)
display d = display(s) : display iData object (from command line)
doc doc(iData): iData web page documentation
dog s= dog(dim,a) : split iData objects elements along dimension
double d = double(s) : convert iData into doubles
edit edit(s) : edit iData object Signal/Monitor
end b = end(s,index,n) : end value for iData objects
eq c = eq(a,b) : equal comparison of iData objects
event c = event(a) : build an event list
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
fileattrib [attribute, link] = fileattrib(s, field) : return a field Attribute
fill FILL fill-in over missing data
find d = find(s) : find iData signal non zeros values
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
findobj [s,...]=findobj(s,...) : look for existing iData objects
findstr [match, field]=findstr(s, str, option) : look for strings stored in iData
fits [pars,criteria,message,output] = fits(a, model, pars, options, constraints, ...) : fit data set on a model
full b = full(s) : Convert iData object storage to full matrix
ge c = ge(a,b) : greater-than-or-equal comparison of iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
getframe frame = getframe(s, dim, options) : create an iData object thumbnail/frame matrix
gradient g = gradient(a, dim) : computes the gradient (derivative) of iData objects
gt c = gt(a,b) : greater-than comparison of iData objects
help c = help(s) : display iData information as a Dialogue window
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
iData
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
imroi imroi: define a region of interest on a data set
imwrite f = imwrite(s, filename, format) : save iData object into an image
ind2sub ind2sub(s,index) : get indexed element in an iData array
interp [b...] = interp(s, ...) : interpolate iData object
intersect [ai,bi] = intersect(a, b) : computes object intersection area and values
isempty isempty(s) : true for empty iData object
isequal c = isequal(a,b) : full numerical equality comparison of iData objects
isfield b = isfield(s, field) : check existence of field/alias in iData objects
isvector b = isvector(s) : True for vector iData object
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
label b = label(s, alias, label) : Change iData label for a given alias/axis
ldivide c = ldivide(a,b) : fast notation for combine iData objects
le c = le(a,b) : lower-than-or-equal comparison of iData objects
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
load d = load(s, file, loader, ...): iData file loader
logical d = logical(s) : convert iData into logical array
logspace v = logspace(a,b,n) : creates a logarithmically spaced vector of objects
lt c = lt(a,b) : lower-than comparison of iData objects
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
mean b = mean(s, dim) : mean value of iData object
median b = median(s, dim) : median value of iData object
mesh h = mesh(s,option) : Plot a 2D/3D object as mesh
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
minus c = minus(a,b) : computes the difference of iData objects
mldivide c = mldivide(a,b) : a\b is fast notation for combine(a,b)
mpower c = mpower(a,b) : computes the matrix-power of iData objects
mrdivide c = mrdivide(a,b) : computes the division of iData objects
mtimes c = mtimes(a,b) : computes the matrix product of iData objects
ndims d = ndims(s) : get the dimensionality of iData object
ne c = ne(a,b) : not-equal comparison of iData objects
ones s = ones(s,N,M,P,...) : initialize an iData array
pack b = pack(a) : compress iData storage to save memory
pca [b] = pca(X, k) : Principal component analysis of iData object(s)
pcolor h = pcolor(s,option) : Plot a 2D/3D object as a flat matrix image
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
permute c = permute(a, order) : Permute object dimensions from iData objects/arrays
plot h = plot(s, method, ...) : plot iData object
plot3 h = plot3(s,option) : Plot a 2D/3D object as separate points or semi-transparent volume
plus c = plus(a,b) : computes the sum of iData objects
power c = power(a,b) : computes the power of iData objects
prod s = prod(a,dim) : computes the product of iData objects elements
publish b = publish(s) : export the Dataset object as an HTML document.
rdivide c = rdivide(a,b) : computes the ratio of iData objects
reducevolume h = reducevolume(s, factor) : reduce an iData object size
reshape c = reshape(a) : reshape the object Signal
resize c = resize(a) : resize/rebin the object Signal
rmalias s = rmalias(s, AliasName) : removes iData aliases
rmaxis s = rmaxis(s, Axis) : delete iData axes
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
saveas f = saveas(s, filename, format, options) : save iData object into various data formats
scatter h = scatter(s,option) : Plot a 2D/3D object as separate colored points
scatter3 h = scatter3(s,option) : Plot a 2D/3D object as separate colored points
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
single d = single(s) : convert iData into single floats
size size(s) : get iData object size (number of elements)
slice slice(s) : Plot a 2D/3D object with slice rendering
smooth Z = smooth(Y) : smooth iData objects
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
std [half_width, center] = std(s, dim) : standard deviation of iData
subplot h = subplot(s) : plot iData array as subplots
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsindex d = subsindex(s) : subscript index for iData objects
subsref b = subsref(a,s) : iData indexed references
sum s = sum(a,dim) : computes the sum of iData objects elements
surf h = surf(s,option) : Plot a 2D/3D object as surface
surfc h = surfc(s,option) : Plot a 2D/3D object as surface+contour
surfl h = surfl(s,option) : Plot a 2D/3D object as surface with light
times c = times(a,b) : computes the product of iData objects
title b = title(s,label) : Change iData Signal label
transpose b = transpose(s) : non-conjugate transpose of iData object
trapz s = trapz(a,dim) : computes the integral of iData objects elements along given dimension
union [ai,bi] = union(a, b) : computes object union area and values
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
version v = version(iData): iData class version
waterfall h = waterfall(s,option) : Plot a 2D/3D object as waterfall (side by side lines)
xcorr c = xcorr(a,b,shape) : computes the correlation of iData objects
xlabel b = xlabel(s,label) : Change iData X axis label
xlim b = xlim(s,[ xmin xmax ]) : Reduce iData X axis limits
xmlwrite f = xmlwrite(s, filename) : save iData object into an XML file
ylabel b = ylabel(s,label) : Change iData Y axis label
ylim b = ylim(s,[ ymin ymax ]) : Reduce iData Y axis limits
zeros s = zeros(s,N,M,P,...) : initialize an iData array
zlabel b = zlabel(s,label) : Change iData Z axis label
zlim b = zlim(s,[ zmin zmax ]) : Reduce iData Z axis limits