ifit.mccode.org - Description of fileattrib
Home > Objects > @iData > fileattrib.m
iFit/fileattrib
PURPOSE
[attribute, link] = fileattrib(s, field) : return a field Attribute
SYNOPSIS
function [b, link] = fileattrib(a, field, allfields)
DESCRIPTION
 [attribute, link] = fileattrib(s, field) : return a field Attribute
   @iData/fileattrib function which looks for an associated Attribute to a field.
      Attributes are set from e.g. NetCDF/CDF/NeXus/HDF files.
      returns []  when no attribute exists
      returns NaN when the field is already an attribute
   s=fileattrib(s, field, attributes) sets the attribute for given field and return
     the updated object.
 input:  s:     object or array (iData)
         field: Alias/path in the object (string)
         attributes: when given as a structure, sets the attributes for the field.
                     when given as a cellstr, it is used for a faster search of
                       attributes, e.g. attributes=fieldfield(a)
 output: attribute: the value of the associated Attribute, or [].
                    or the updated object when storing attributes.
         link:      the path of the associated Attribute, or [].
 ex:     b=fileattrib(a, 'Signal');
         b=fileattrib(b, 'Signal',struct('long_name','hello world'))
 Version: oct.. 23, 2018
 See also iData, isfield
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
char c = char(s) : convert iData into character
end b = end(s,index,n) : end value for iData objects
fileattrib [attribute, link] = fileattrib(s, field) : return a field Attribute
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
isempty isempty(s) : true for empty iData object
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
This function is called by:
fileattrib [attribute, link] = fileattrib(s, field) : return a field Attribute