ifit.mccode.org - Description of findstr
Home > Objects > @iData > findstr.m
iFit/findstr
PURPOSE
[match, field]=findstr(s, str, option) : look for strings stored in iData
SYNOPSIS
function [match, field] = findstr(s, str, option)
DESCRIPTION
 [match, field]=findstr(s, str, option) : look for strings stored in iData
   @iData/findstr function to look for strings stored in iData
   [match,field] = findstr(iData, str) returns the string containg 'str'
     and the field name it appears in. If 'str' is set to '', the content of all
     character fields is returned.
   The 'option' may contain 'exact' to search for the exact occurence, and 'case'
   to specifiy a case sensitive search.
 input:  s: object or array (iData)
         str: string to search in object, or '' (char or cellstr).
         option: 'exact' 'case' or '' (char)
 output: match: content of iData fields that contain 'str' (cellstr)
         field: name of iData fields that contain 'str' (cellstr)
 ex:     findstr(iData,'ILL') or findstr(s,'TITLE','exact case')
 Version: oct.. 23, 2018
 See also iData, iData/set, iData/get, iData/findobj, iData/findfield
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
char c = char(s) : convert iData into character
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
findstr [match, field]=findstr(s, str, option) : look for strings stored in iData
get [...] = get(s, 'PropertyName', ...) : get iData object properties
isempty isempty(s) : true for empty iData object
strfind [match, field]=strfind(s, pattern, option) : search for pattern in iData
This function is called by:
findstr [match, field]=findstr(s, str, option) : look for strings stored in iData
strfind [match, field]=strfind(s, pattern, option) : search for pattern in iData