ifit.mccode.org - Description of get
Home > Objects > @iData > get.m
iFit/get
PURPOSE
[...] = get(s, 'PropertyName', ...) : get iData object properties
SYNOPSIS
function [varargout] = get(this,varargin)
DESCRIPTION
 [...] = get(s, 'PropertyName', ...) : get iData object properties
   @iData/get function to get iData properties.
   get(s) displays all property names and their current values for
     the iData object 's'.
   get(s,'PropertyName',...) returns only particular properties.
     the PropertyName may also be an object Alias or an Axis.
   Input 's' can be a single iData or a iData array.
   To get the Signal/Monitor, rather use getaxis(s, 'Signal') or s{0}
              Error/Monitor              getaxis(s, 'Error')
 input:  s: object or array (iData)
         PropertyName: name of Property to search (char)
 output: property: property value in 's' (cell)
 ex :    get(iData) or get(iData,'Title')
 Version: oct.. 23, 2018
 See also iData, iData/set, iData/getalias, iData/getaxis, iData/findobj
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
char c = char(s) : convert iData into character
disp disp(s) : display iData object (details)
display d = display(s) : display iData object (from command line)
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
iData
isempty isempty(s) : true for empty iData object
isnumeric b = isnumeric(s) : True for numeric iData object elements
isscalar b = isscalar(s) : True for scalar iData objects
subsref b = subsref(a,s) : iData indexed references
This function is called by:
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
caxis c = caxis(s, h) : Use the 2D/3D data as the colormap (CData property) in current object.
commandhistory commandhistory(s) : show the command history of iData object
disp disp(s) : display iData object (details)
display d = display(s) : display iData object (from command line)
edit edit(s) : edit iData object Signal/Monitor
end b = end(s,index,n) : end value for iData objects
event c = event(a) : build an event list
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
fill FILL fill-in over missing data
find d = find(s) : find iData signal non zeros values
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
findobj [s,...]=findobj(s,...) : look for existing iData objects
findstr [match, field]=findstr(s, str, option) : look for strings stored in iData
fits [pars,criteria,message,output] = fits(a, model, pars, options, constraints, ...) : fit data set on a model
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
getframe frame = getframe(s, dim, options) : create an iData object thumbnail/frame matrix
gradient g = gradient(a, dim) : computes the gradient (derivative) of iData objects
help c = help(s) : display iData information as a Dialogue window
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
iData
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
imroi imroi: define a region of interest on a data set
ind2sub ind2sub(s,index) : get indexed element in an iData array
isequal c = isequal(a,b) : full numerical equality comparison of iData objects
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
load d = load(s, file, loader, ...): iData file loader
logical d = logical(s) : convert iData into logical array
logspace v = logspace(a,b,n) : creates a logarithmically spaced vector of objects
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
mtimes c = mtimes(a,b) : computes the matrix product of iData objects
ndims d = ndims(s) : get the dimensionality of iData object
pack b = pack(a) : compress iData storage to save memory
pca [b] = pca(X, k) : Principal component analysis of iData object(s)
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
plot h = plot(s, method, ...) : plot iData object
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
saveas f = saveas(s, filename, format, options) : save iData object into various data formats
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
single d = single(s) : convert iData into single floats
slice slice(s) : Plot a 2D/3D object with slice rendering
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsindex d = subsindex(s) : subscript index for iData objects
subsref b = subsref(a,s) : iData indexed references
unique s = unique(a,dim) : set unique iData objects axes with no repetitions