ifit.mccode.org - Description of getalias
Home > Objects > @iData > getalias.m
iFit/getalias
PURPOSE
[link, label,names] = getalias(s, 'AliasName') : get iData alias
SYNOPSIS
function [link, label, names] = getalias(this,alias)
DESCRIPTION
 [link, label,names] = getalias(s, 'AliasName') : get iData alias
   @iData/getalias function to get iData alias definition.
   [link, label]          = getalias(s, alias) returns the alias link and its label/description.
   [names, links, labels] = getalias(s)        returns all defined aliases.
   The Signal, Error and Monitor aliases are always defined.
   The value of the alias is obtained with the syntax: 's.alias'.
   To search for aliases/fields in the object you may use findfield.
 input:  s: object or array (iData)
         alias: alias name to inquire in object, or '' (char).
 output: link: alias link/definition (char/cellstr)
         label: alias description (char/cellstr)
         names: all defined alias names (cellstr)
 ex:     getalias(iData) or getalias(iData,'Signal')
 Version: oct.. 23, 2018
 See also iData, iData/set, iData/get, iData/setalias, iData/rmalias
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
isempty isempty(s) : true for empty iData object
label b = label(s, alias, label) : Change iData label for a given alias/axis
size size(s) : get iData object size (number of elements)
This function is called by:
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
fileattrib [attribute, link] = fileattrib(s, field) : return a field Attribute
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
help c = help(s) : display iData information as a Dialogue window
interp [b...] = interp(s, ...) : interpolate iData object
isfield b = isfield(s, field) : check existence of field/alias in iData objects
mean b = mean(s, dim) : mean value of iData object
median b = median(s, dim) : median value of iData object
pack b = pack(a) : compress iData storage to save memory
plot h = plot(s, method, ...) : plot iData object
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references