ifit.mccode.org - Description of hist
Home > Objects > @iData > hist.m
iFit/hist
PURPOSE
hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
SYNOPSIS
function c=hist(a, varargin)
DESCRIPTION
 hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
   @iData/hist function to compute the accumulated histogram from an event data
     set. This is similar to a call to hist and accumarray.
   hist(a, axis1, axis2, ...) specify the axes as bin edges. The axes
     should be vectors or a single value that indicates the number of bins in the
     range [min, max] of the corresponding axis rank in the initial object.
     The bin edges vectors have length(a{k])+1 elements. A default of 33 bins
     is used when not specified.
   hist(a, [ bin1 bin2 ...]) same as above when specifying the number of bins.
   hist(a, ..., 'Fun', FUN)
     applies the function FUN to each subset of elements of VAL.  FUN is
     a function that accepts a column vector and returns
     a numeric, logical, or char scalar, or a scalar cell.  A has the same class
     as the values returned by FUN.  FUN is @SUM by default.  Specify FUN as []
     for the default behavior.
   hist(a, ..., 'fill')
     performs an interpolation between the events to fill unset histogram bins.
 The histogram can be converted back to an event list using the 'event' method.
 input:  a: object or array (iData)
         axis1, axis2, ...: bins or number of bins  (vector or scalar)
 output: c: histogrammed object (iData)
 ex:     a=iData([ ifitpath 'Data/Monitor_GV*']); b=hist(a);
 Version: oct.. 23, 2018
 See also iData, accumarray, hist, histc, iData/plot, sum, iData/interp, iData/event
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
event c = event(a) : build an event list
fill FILL fill-in over missing data
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
iData
isempty isempty(s) : true for empty iData object
isnumeric b = isnumeric(s) : True for numeric iData object elements
isscalar b = isscalar(s) : True for scalar iData objects
isvector b = isvector(s) : True for vector iData object
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
ndims d = ndims(s) : get the dimensionality of iData object
not b = not(s) : computes the logical 'not' of iData object
rmalias s = rmalias(s, AliasName) : removes iData aliases
rmaxis s = rmaxis(s, Axis) : delete iData axes
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
sqrt b = sqrt(s) : square root value of iData object
strfind [match, field]=strfind(s, pattern, option) : search for pattern in iData
subsref b = subsref(a,s) : iData indexed references
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
interp [b...] = interp(s, ...) : interpolate iData object
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
slice slice(s) : Plot a 2D/3D object with slice rendering