ifit.mccode.org - Description of isempty
Home > Objects > @iData > isempty.m
iFit/isempty
PURPOSE
isempty(s) : true for empty iData object
SYNOPSIS
function y = isempty(s)
DESCRIPTION
 isempty(s) : true for empty iData object
   @iData/isempty true for empty iData object
 input:  s: object or array (iData)
 output: false(0) or true(1) whether Signal is empty in the objects
 ex :    isempty(iData)
 Version: oct.. 23, 2018
 See also iData, iData/disp, iData/get, iData/size
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
size size(s) : get iData object size (number of elements)
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
caxis c = caxis(s, h) : Use the 2D/3D data as the colormap (CData property) in current object.
cell [content,fields]=cell(s) : convert iData objects into cells
clim b = clim(s,[ cmin cmax ]) : Reduce iData C axis limits
colon b = colon(s) : vector of arrays
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
commandhistory commandhistory(s) : show the command history of iData object
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
deconv c = deconv(a,b) : computes the deconvolution of iData objects
disp disp(s) : display iData object (details)
display d = display(s) : display iData object (from command line)
doc doc(iData): iData web page documentation
edit edit(s) : edit iData object Signal/Monitor
event c = event(a) : build an event list
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
fileattrib [attribute, link] = fileattrib(s, field) : return a field Attribute
fill FILL fill-in over missing data
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
findobj [s,...]=findobj(s,...) : look for existing iData objects
findstr [match, field]=findstr(s, str, option) : look for strings stored in iData
fits [pars,criteria,message,output] = fits(a, model, pars, options, constraints, ...) : fit data set on a model
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
help c = help(s) : display iData information as a Dialogue window
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
iData
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
imroi imroi: define a region of interest on a data set
interp [b...] = interp(s, ...) : interpolate iData object
isequal c = isequal(a,b) : full numerical equality comparison of iData objects
isfield b = isfield(s, field) : check existence of field/alias in iData objects
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
label b = label(s, alias, label) : Change iData label for a given alias/axis
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
load d = load(s, file, loader, ...): iData file loader
logspace v = logspace(a,b,n) : creates a logarithmically spaced vector of objects
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
pack b = pack(a) : compress iData storage to save memory
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
permute c = permute(a, order) : Permute object dimensions from iData objects/arrays
plot h = plot(s, method, ...) : plot iData object
reducevolume h = reducevolume(s, factor) : reduce an iData object size
reshape c = reshape(a) : reshape the object Signal
resize c = resize(a) : resize/rebin the object Signal
rmalias s = rmalias(s, AliasName) : removes iData aliases
rmaxis s = rmaxis(s, Axis) : delete iData axes
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
saveas f = saveas(s, filename, format, options) : save iData object into various data formats
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
slice slice(s) : Plot a 2D/3D object with slice rendering
smooth Z = smooth(Y) : smooth iData objects
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
std [half_width, center] = std(s, dim) : standard deviation of iData
subplot h = subplot(s) : plot iData array as subplots
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references
union [ai,bi] = union(a, b) : computes object union area and values
xlabel b = xlabel(s,label) : Change iData X axis label
xlim b = xlim(s,[ xmin xmax ]) : Reduce iData X axis limits
ylabel b = ylabel(s,label) : Change iData Y axis label
ylim b = ylim(s,[ ymin ymax ]) : Reduce iData Y axis limits
zeros s = zeros(s,N,M,P,...) : initialize an iData array
zlim b = zlim(s,[ zmin zmax ]) : Reduce iData Z axis limits