ifit.mccode.org - Description of isequal
Home > Objects > @iData > isequal.m
iFit/isequal
PURPOSE
c = isequal(a,b) : full numerical equality comparison of iData objects
SYNOPSIS
function s = isequal(a,b)
DESCRIPTION
 c = isequal(a,b) : full numerical equality comparison of iData objects
   @iData/eq (==) exact equality comparison operator on Signal, Source,
   Label, Title, Monitor
 input:  a: object or array (iData or numeric)
         b: object or array (iData or numeric)
 output: c: logical array indicating equal objects (iData)
 ex:     d=isequal(a,b);
 Version: oct.. 23, 2018
 See also iData, iData/find, iData/gt, iData/lt, iData/ge, iData/le, iData/ne, iData/eq
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
isempty isempty(s) : true for empty iData object
isequal c = isequal(a,b) : full numerical equality comparison of iData objects
This function is called by:
interp [b...] = interp(s, ...) : interpolate iData object
intersect [ai,bi] = intersect(a, b) : computes object intersection area and values
isequal c = isequal(a,b) : full numerical equality comparison of iData objects
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
reshape c = reshape(a) : reshape the object Signal
resize c = resize(a) : resize/rebin the object Signal
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
union [ai,bi] = union(a, b) : computes object union area and values