ifit.mccode.org - Description of linspace
Home > Objects > @iData > linspace.m
iFit/linspace
PURPOSE
v = linspace(a,b,n) : creates a linearly spaced vector of objects
SYNOPSIS
function v = linspace(a,b,n)
DESCRIPTION
 v = linspace(a,b,n) : creates a linearly spaced vector of objects
   @iData/linspace function to create a linearly spaced vector of iData objects
   This corresponds to a 'morphing' from a to b in n steps.
 input:  a: object or scalar (iData)
         b: object or scalar (iData)
         n: number of steps, i.e. length of vector. Default is n=10 (integer)
 output: v: vector (iData array)
 ex:     b=linspace(a,b);
 Version: oct.. 23, 2018
 See also iData, iData/max, iData/min, iData/colon, iData/logspace
CROSS-REFERENCE INFORMATION
This function calls:
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
iData
intersect [ai,bi] = intersect(a, b) : computes object intersection area and values
isempty isempty(s) : true for empty iData object
isnumeric b = isnumeric(s) : True for numeric iData object elements
isscalar b = isscalar(s) : True for scalar iData objects
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
mean b = mean(s, dim) : mean value of iData object
ones s = ones(s,N,M,P,...) : initialize an iData array
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
size size(s) : get iData object size (number of elements)
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
caxis c = caxis(s, h) : Use the 2D/3D data as the colormap (CData property) in current object.
colon b = colon(s) : vector of arrays
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
getframe frame = getframe(s, dim, options) : create an iData object thumbnail/frame matrix
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin