ifit.mccode.org - Description of logspace
Home > Objects > @iData > logspace.m
iFit/logspace
PURPOSE
v = logspace(a,b,n) : creates a logarithmically spaced vector of objects
SYNOPSIS
function v = logspace(a,b,n)
DESCRIPTION
 v = logspace(a,b,n) : creates a logarithmically spaced vector of objects
   @iData/logspace function to create a logarithmically spaced vector of iData objects
   This corresponds to a 'morphing' from a to b in n steps.
 input:  a: object  (iData)
         b: object  (iData)
         n: number of steps, i.e. length of vector. Default is n=10 (integer)
 output: v: vector (iData array)
 ex:     b=logspace(a,b);
 Version: oct.. 23, 2018
 See also iData, iData/max, iData/min, iData/colon, iData/linspace
CROSS-REFERENCE INFORMATION
This function calls:
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
iData
intersect [ai,bi] = intersect(a, b) : computes object intersection area and values
isempty isempty(s) : true for empty iData object
isnumeric b = isnumeric(s) : True for numeric iData object elements
isscalar b = isscalar(s) : True for scalar iData objects
logspace v = logspace(a,b,n) : creates a logarithmically spaced vector of objects
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
mean b = mean(s, dim) : mean value of iData object
ones s = ones(s,N,M,P,...) : initialize an iData array
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
size size(s) : get iData object size (number of elements)
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
logspace v = logspace(a,b,n) : creates a logarithmically spaced vector of objects