ifit.mccode.org - Description of max
Home > Objects > @iData > max.m
iFit/max
PURPOSE
[m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
SYNOPSIS
function [m,id] = max(a,b, dim)
DESCRIPTION
 [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
   @iData/max function to compute the maximum value of data sets.
     max(iData) returns a single value as the maximum value of the iData signal
     max(a,b)   returns an object which signal is the highest of a and b.
     max(a,[], dim) returns max value along dimension 'dim'
 input:  a: object or array (iData)
         b: object or array (iData/double)
         dim: dimension on which to operate
 output: m:  maximum value (double/iData)
         id: returns the indices of the maximum value (integer)
 ex:     b=max(a);
 Version: oct.. 23, 2018
 See also iData, max, iData/min
CROSS-REFERENCE INFORMATION
This function calls:
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
intersect [ai,bi] = intersect(a, b) : computes object intersection area and values
isempty isempty(s) : true for empty iData object
label b = label(s, alias, label) : Change iData label for a given alias/axis
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
ndims d = ndims(s) : get the dimensionality of iData object
rmaxis s = rmaxis(s, Axis) : delete iData axes
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
clim b = clim(s,[ cmin cmax ]) : Reduce iData C axis limits
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
disp disp(s) : display iData object (details)
edit edit(s) : edit iData object Signal/Monitor
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
help c = help(s) : display iData information as a Dialogue window
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
imroi imroi: define a region of interest on a data set
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
logspace v = logspace(a,b,n) : creates a logarithmically spaced vector of objects
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
plot h = plot(s, method, ...) : plot iData object
reducevolume h = reducevolume(s, factor) : reduce an iData object size
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
saveas f = saveas(s, filename, format, options) : save iData object into various data formats
setaxis s = setaxis(s, rank, alias, value) : set iData axes
subsref b = subsref(a,s) : iData indexed references
xlim b = xlim(s,[ xmin xmax ]) : Reduce iData X axis limits
ylim b = ylim(s,[ ymin ymax ]) : Reduce iData Y axis limits
zlim b = zlim(s,[ zmin zmax ]) : Reduce iData Z axis limits