ifit.mccode.org - Description of median
Home > Objects > @iData > median.m
iFit/median
PURPOSE
b = median(s, dim) : median value of iData object
SYNOPSIS
function b = median(a, dim)
DESCRIPTION
 b = median(s, dim) : median value of iData object
   @iData/median function to compute the median value of objects
     median(a,dim) computes median along axis of rank dim. The axis is then removed.
       If dim=0, median is done on all axes and the total is returned as a scalar value.
       median(a,1) operates on first dimension (columns)
     median(a,-dim) computes median on all axes except the dimension specified, i.e.
       the result is the median projection of a along dimension dim.
       All other axes are removed.
 input:  a: object or array (iData/array of)
         dim: dimension to operate on (int)
 output: s: median of elements (iData/scalar)
 ex:     c=median(a);
 Version: oct.. 23, 2018
 See also iData, iData/std, iData/combine, iData/mean
CROSS-REFERENCE INFORMATION
This function calls:
combine c = combine(a,b) : combines iData objects
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
label b = label(s, alias, label) : Change iData label for a given alias/axis
median b = median(s, dim) : median value of iData object
ndims d = ndims(s) : get the dimensionality of iData object
rmaxis s = rmaxis(s, Axis) : delete iData axes
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
median b = median(s, dim) : median value of iData object