ifit.mccode.org - Description of pca
Home > Objects > @iData > pca.m
iFit/pca
PURPOSE
[b] = pca(X, k) : Principal component analysis of iData object(s)
SYNOPSIS
function b = pca(a, varargin)
DESCRIPTION
 [b] = pca(X, k) : Principal component analysis of iData object(s)
   @iData/pca function to perform a Principal component analysis of object(s)
   b = pca(a,k) computes the principal component analysis of an object in a k-D
     space representation. This corresponds to a classification of the objects
     rows, searching for similarities/correlations. The resulting principal
     component coefficients object contains the same number of rows as 'a', and
     k columns for coordinates.
     Rows (rank 1) of X correspond to observations and further ranks correspond
     to variables.
   b = pca(a) assumes k=2 (2D space classifier).
   b = pca([a1 a2 ...], k) performs the PCA along all objects specified in the
     array, and return the principal component coefficients. The resulting object
     contains as many rows as the number of objects specified, and k columns.
   b = pca(a, key, value, ...)
     specifies the PCA configuration as key=value pairs:
       'NumComponents',k
         Number of components requested, specified as the comma-separated pair
         consisting of 'NumComponents' and a scalar integer k satisfying
         0 < k <= p, where p is the number of original variables in X. When
         specified, pca returns the first k PCA coefficients.
       'Centered', True(default) or False
         Center the variables by subtracting the mean values
       'VariableWeights', false or 'variance'
         'variance' to normalize variables to their variance (default)
 input:  X: object or array (iData)
         k: number of components wanted (integer, default is 2)
 output: b: principal component object (iData)
 ex:     b=pca(a); plot(b); text(b{1},b{2}, get(a,'Title'));
 See: http://en.wikipedia.org/wiki/Principal_component_analysis
 Version: oct.. 23, 2018
 See also iData, iData/kmeans, iData/cwt, iData/corrcoef
CROSS-REFERENCE INFORMATION
This function calls:
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
isscalar b = isscalar(s) : True for scalar iData objects
mean b = mean(s, dim) : mean value of iData object
pca [b] = pca(X, k) : Principal component analysis of iData object(s)
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
std [half_width, center] = std(s, dim) : standard deviation of iData
subsref b = subsref(a,s) : iData indexed references
union [ai,bi] = union(a, b) : computes object union area and values
This function is called by:
pca [b] = pca(X, k) : Principal component analysis of iData object(s)