ifit.mccode.org - Description of plot
Home > Objects > @iData > plot.m
iFit/plot
PURPOSE
h = plot(s, method, ...) : plot iData object
SYNOPSIS
function h=plot(a, varargin)
DESCRIPTION
 h = plot(s, method, ...) : plot iData object
   @iData/plot function to plot data sets
   This function plot the signal of the object as a function of the defined axes.
   The plot is an errorbar plot for 1D data y=f(x), a surface mesh for 2D z=f(x,y),
     and an isosurface for 3D c=f(x,y,z) data. Data specified as series of
     coordinate points are plotted using a plot3-type rendering. Further
     dimensionalities are not handled.
   The scatter3 rendering option is similar to plot3, but color points are set
   according to the signal intensity. The 'plot3' option for 3D (volume) objects
   uses a semi-transparent volume rendering, whereas the default plot uses
   an iso-surface on the median signal.
   When a XtickLabel alias/property exists in the object, the Xtick labels are set.
   As mentioned in the iData axis definition (see iData/setaxis), the 'X' axis
     refers to the 2nd dimension (along columns), whereas the 'Y' axis refers to
     the first dimension (along rows).
  Type <a href="matlab:doc(iData,'Plot')">doc(iData,'Plot')</a> to access the iFit/Plot Documentation.
 input:  s: object or array (iData)
         method: optional type of plot to render
               For 1D plots y=f(x), method is a string to specify color/symbol.
                 hide_errorbars is also valid not to plot error bars.
                 To plot a set of 1D objects side by side, specify a 2D plot
                 option such as 'surf' or 'plot3'.
               For 2D plots z=f(x,y), method is a string which may contain:
                 surf, mesh, contour, contour3, surfc, surfl, contourf
                 plot3, scatter3 (colored points), stem3, pcolor, waterfall
               For 3D plots c=f(x,y,z), method is a string which may contain:
                 plot3 (volume), scatter3 (colored points, supports 'scatter3 filled' and 'scatter3 bubble')
                 waterfall (supports 'waterfall x' 'y' and 'z'), contour (set of coutour plots)
                 surf, surf median, surf mean, surf half (isosurface)
               The slice(a) method opens the interactive sliceomatic 3D viewer.
               Global options for 2D and 3D plots:
                 flat, interp, faceted (for shading), view2, view3
                 transparent, light, clabel, colorbar, shifted (overlayed 2D)
               Global options for all plots:
                 axis tight, axis auto, hide_axes (compact layout)
                 painters (bitmap drawing), zbuffer (vectorial drawing)
                 opengl (faster for large data sets)
                 whole or full (do not reduce large object size for plotting)
                 figure (open a new figure window)
                 replace (replace existing plots for same objects)
                 legend (plot legend for objects)
         args: additional arguments passed to the plotting method
 output: h: graphics object handles (cell/array)
 ex:     plot(iData(rand(10)), 'surfc interp transparent'); plot(iData(1:10), 'r-');
         plot(iData(peaks));
         [x,y,z,v]=flow; c=iData(x,y,z,v); plot(c,'surf');
 Contributed code (Matlab Central):
   fscatter3: Felix Morsdorf, Jan 2003, Remote Sensing Laboratory Zuerich
   vol3d:     Joe Conti, 2004
   sliceomatic: Eric Ludlam 2001-2008
 Version: oct.. 23, 2018
 See also iData, interp1, interpn, ndgrid, plot, iData/setaxis, iData/getaxis
          iData/xlabel, iData/ylabel, iData/zlabel, iData/clabel, iData/title
          shading, lighting, surf, iData/slice, iData/contour3, iData/contourf
          iData/contour, iData/surf, iData/slice, iData/plot3, iData/surfl,
          iData/surfc, iData/mesh
CROSS-REFERENCE INFORMATION
This function calls:
char c = char(s) : convert iData into character
contour3 h = contour3(s,option) : Plot a 2D/3D object as 3D contour
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
findobj [s,...]=findobj(s,...) : look for existing iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
interp [b...] = interp(s, ...) : interpolate iData object
isempty isempty(s) : true for empty iData object
isfield b = isfield(s, field) : check existence of field/alias in iData objects
isnan b = isnan(s) : True for NaN iData object elements
isvector b = isvector(s) : True for vector iData object
label b = label(s, alias, label) : Change iData label for a given alias/axis
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
ndims d = ndims(s) : get the dimensionality of iData object
plot h = plot(s, method, ...) : plot iData object
prod s = prod(a,dim) : computes the product of iData objects elements
reducevolume h = reducevolume(s, factor) : reduce an iData object size
resize c = resize(a) : resize/rebin the object Signal
rmaxis s = rmaxis(s, Axis) : delete iData axes
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
size size(s) : get iData object size (number of elements)
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
strfind [match, field]=strfind(s, pattern, option) : search for pattern in iData
title b = title(s,label) : Change iData Signal label
transpose b = transpose(s) : non-conjugate transpose of iData object
xlabel b = xlabel(s,label) : Change iData X axis label
ylabel b = ylabel(s,label) : Change iData Y axis label
zlabel b = zlabel(s,label) : Change iData Z axis label
This function is called by:
contour h = contour(s,option) : Plot a 2D/3D object as contour
contour3 h = contour3(s,option) : Plot a 2D/3D object as 3D contour
contourf h = contourf(s,option) : Plot a 2D/3D object as filled contour
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
edit edit(s) : edit iData object Signal/Monitor
getframe frame = getframe(s, dim, options) : create an iData object thumbnail/frame matrix
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
imroi imroi: define a region of interest on a data set
mesh h = mesh(s,option) : Plot a 2D/3D object as mesh
pcolor h = pcolor(s,option) : Plot a 2D/3D object as a flat matrix image
plot h = plot(s, method, ...) : plot iData object
plot3 h = plot3(s,option) : Plot a 2D/3D object as separate points or semi-transparent volume
saveas f = saveas(s, filename, format, options) : save iData object into various data formats
scatter h = scatter(s,option) : Plot a 2D/3D object as separate colored points
scatter3 h = scatter3(s,option) : Plot a 2D/3D object as separate colored points
slice slice(s) : Plot a 2D/3D object with slice rendering
subplot h = subplot(s) : plot iData array as subplots
surf h = surf(s,option) : Plot a 2D/3D object as surface
surfc h = surfc(s,option) : Plot a 2D/3D object as surface+contour
surfl h = surfl(s,option) : Plot a 2D/3D object as surface with light
waterfall h = waterfall(s,option) : Plot a 2D/3D object as waterfall (side by side lines)