ifit.mccode.org - Description of reshape
Home > Objects > @iData > reshape.m
iFit/reshape
PURPOSE
c = reshape(a) : reshape the object Signal
SYNOPSIS
function a = reshape(a, varargin)
DESCRIPTION
 c = reshape(a) : reshape the object Signal
   @iData/reshape function to reshape the object Signal array
     reshape(a, m,n,p,...) reshapes the Signal as an m*n*p*... array
       the number of elements in the initial Signal must be m*n*p*...
     reshape(a, [m n p ...]) is the same thing.
     the resulting object has the elements of the initial one reordered so that
       the final size is that requested.
 input:  a:   object or array (iData)
         m,n,p...: dimensions (integers)
 output: c: object or array (iData)
 ex:     a=iData(peaks(60)); b=reshape(a, 75, 48);
 Version: oct.. 23, 2018
 See also iData, iData/squeeze, iData/size, iData/permute, iData/resize, iData/reducevolume
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
isempty isempty(s) : true for empty iData object
isequal c = isequal(a,b) : full numerical equality comparison of iData objects
prod s = prod(a,dim) : computes the product of iData objects elements
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
clim b = clim(s,[ cmin cmax ]) : Reduce iData C axis limits
conv c = conv(a,b) : computes the convolution of iData objects
copyobj b = copyobj(s) : makes a copy of iData object
corrcoef c = corrcoef(a,b) : correlation coefficient with an iData object
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
interp [b...] = interp(s, ...) : interpolate iData object
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
pack b = pack(a) : compress iData storage to save memory
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
reducevolume h = reducevolume(s, factor) : reduce an iData object size
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
smooth Z = smooth(Y) : smooth iData objects
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
xlim b = xlim(s,[ xmin xmax ]) : Reduce iData X axis limits
ylim b = ylim(s,[ ymin ymax ]) : Reduce iData Y axis limits
zeros s = zeros(s,N,M,P,...) : initialize an iData array
zlim b = zlim(s,[ zmin zmax ]) : Reduce iData Z axis limits