ifit.mccode.org - Description of resize
Home > Objects > @iData > resize.m
iFit/resize
PURPOSE
c = resize(a) : resize/rebin the object Signal
SYNOPSIS
function b = resize(a, varargin)
DESCRIPTION
 c = resize(a) : resize/rebin the object Signal
   @iData/resize function to resize/rebin the object Signal array
     resize(a, m,n,p,...) resizes the Signal as an m*n*p*... array
       using a N-D discrete cosine transform.
     resize(a, [m n p ...]) is the same thing.
 input:  a:   object or array (iData)
         m,n,p...: dimensions (integers)
 output: c: object or array (iData)
 ex:     a=iData(peaks); b=resize(a, 10,90);
 Version: oct.. 23, 2018
 See also iData, iData/squeeze, iData/size, iData/permute, iData/reshape, iData/reducevolume
CROSS-REFERENCE INFORMATION
This function calls:
ceil b = ceil(s) : upper integer round of iData object
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
isempty isempty(s) : true for empty iData object
isequal c = isequal(a,b) : full numerical equality comparison of iData objects
ndims d = ndims(s) : get the dimensionality of iData object
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
subsref b = subsref(a,s) : iData indexed references
This function is called by:
plot h = plot(s, method, ...) : plot iData object
slice slice(s) : Plot a 2D/3D object with slice rendering