ifit.mccode.org - Description of rotate
Home > Objects > @iData > rotate.m
iFit/rotate
PURPOSE
s = rotate(a, theta) : computes the rotation of iData objects around the origin
SYNOPSIS
function s = rotate(a, theta)
DESCRIPTION
 s = rotate(a, theta) : computes the rotation of iData objects around the origin
    @iData/rotate function to compute the rotation of iData object around the origin
      rotate(a) rotates around the Signal axis ('vertical') with 180 angular steps
      rotate(a, n) rotates using n angular steps in full revolution
      rotate(a, theta) rotates only on the specified theta values/range
      The resulting object dimensionality is increased by 1.
 input:  a:     object or array (iData/array of)
         theta: single integer to specify how many steps in the revolution, or
                an angular range (vector in radians)
 output: s: rotated object (iData)
 ex:     c=rotate(a);
 Version: oct.. 23, 2018
 See also iData, iData/camproj
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
copyobj b = copyobj(s) : makes a copy of iData object
cos b = cos(s) : computes the cosine of iData object
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
interp [b...] = interp(s, ...) : interpolate iData object
isempty isempty(s) : true for empty iData object
isnumeric b = isnumeric(s) : True for numeric iData object elements
isscalar b = isscalar(s) : True for scalar iData objects
isvector b = isvector(s) : True for vector iData object
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
ndims d = ndims(s) : get the dimensionality of iData object
ones s = ones(s,N,M,P,...) : initialize an iData array
reshape c = reshape(a) : reshape the object Signal
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
setaxis s = setaxis(s, rank, alias, value) : set iData axes
sin b = sin(s) : computes the sine of iData object
size size(s) : get iData object size (number of elements)
times c = times(a,b) : computes the product of iData objects
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by: