ifit.mccode.org - Description of set
Home > Objects > @iData > set.m
iFit/set
PURPOSE
[s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
SYNOPSIS
function this = set(this,varargin)
DESCRIPTION
 [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
   @iData/set function to set iData properties.
   set(s, 'PropertyName', Propertyvalue, ...})
     sets values into given property names for the iData object s.
   set(s, Struct.Field, ...)
     sets values from given structure fields into the iData object s.
   set(s, CellNames, CellValues, ...)
     sets values from given cells into the iData object s.
   set(s) indicates the signification of the iData base properties
   The input iData object is updated if no output argument is specified.
 ex      : set(iData,'Title','A nice Title')
 Version: oct.. 23, 2018
 See also iData, iData/get, iData/setalias, iData/setaxis
CROSS-REFERENCE INFORMATION
This function calls:
disp disp(s) : display iData object (details)
end b = end(s,index,n) : end value for iData objects
iData
isempty isempty(s) : true for empty iData object
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
This function is called by:
caxis c = caxis(s, h) : Use the 2D/3D data as the colormap (CData property) in current object.
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
commandhistory commandhistory(s) : show the command history of iData object
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
edit edit(s) : edit iData object Signal/Monitor
event c = event(a) : build an event list
fileattrib [attribute, link] = fileattrib(s, field) : return a field Attribute
getframe frame = getframe(s, dim, options) : create an iData object thumbnail/frame matrix
help c = help(s) : display iData information as a Dialogue window
iData
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
imroi imroi: define a region of interest on a data set
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
load d = load(s, file, loader, ...): iData file loader
logspace v = logspace(a,b,n) : creates a logarithmically spaced vector of objects
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
pack b = pack(a) : compress iData storage to save memory
pca [b] = pca(X, k) : Principal component analysis of iData object(s)
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
plot h = plot(s, method, ...) : plot iData object
resize c = resize(a) : resize/rebin the object Signal
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
saveas f = saveas(s, filename, format, options) : save iData object into various data formats
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
slice slice(s) : Plot a 2D/3D object with slice rendering
smooth Z = smooth(Y) : smooth iData objects
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references