ifit.mccode.org - Description of single
Home > Objects > @iData > single.m
iFit/single
PURPOSE
d = single(s) : convert iData into single floats
SYNOPSIS
function a=single(a)
DESCRIPTION
 d = single(s) : convert iData into single floats
   @iData/double function to convert iData object into single floats
 input:  s: object or array (iData)
 output: v: value of the iData Signal/Monitor (single)
 ex:     'single(iData(rand(10)))'
 Version: oct.. 23, 2018
 See also  iData/cell, iData/double, iData/struct,
           iData/char, iData/size
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
single d = single(s) : convert iData into single floats
size size(s) : get iData object size (number of elements)
This function is called by:
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
single d = single(s) : convert iData into single floats