ifit.mccode.org - Description of slice
Home > Objects > @iData > slice.m
iFit/slice
PURPOSE
slice(s) : Plot a 2D/3D object with slice rendering
SYNOPSIS
function h = slice(a, method)
DESCRIPTION
 slice(s) : Plot a 2D/3D object with slice rendering
   @iData/slice function to view slices in 3D object
     The plot is obtained with Matlab Central sliceomatic
     To avoid rebinning large objects, use:
       slice(a, 'whole')
 input:  s: object or array (iData)
 ex:     slice(iData(flow));
 Version: oct.. 23, 2018
 See also iData, iData/plot, sliceomatic
CROSS-REFERENCE INFORMATION
This function calls:
char c = char(s) : convert iData into character
end b = end(s,index,n) : end value for iData objects
findobj [s,...]=findobj(s,...) : look for existing iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
isempty isempty(s) : true for empty iData object
isvector b = isvector(s) : True for vector iData object
ndims d = ndims(s) : get the dimensionality of iData object
plot h = plot(s, method, ...) : plot iData object
prod s = prod(a,dim) : computes the product of iData objects elements
reducevolume h = reducevolume(s, factor) : reduce an iData object size
resize c = resize(a) : resize/rebin the object Signal
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
size size(s) : get iData object size (number of elements)
strfind [match, field]=strfind(s, pattern, option) : search for pattern in iData
title b = title(s,label) : Change iData Signal label
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
xlabel b = xlabel(s,label) : Change iData X axis label
ylabel b = ylabel(s,label) : Change iData Y axis label
zlabel b = zlabel(s,label) : Change iData Z axis label
This function is called by: