ifit.mccode.org - Description of squeeze
Home > Objects > @iData > squeeze.m
iFit/squeeze
PURPOSE
c = squeeze(a) : remove singleton dimensions from iData objects/arrays
SYNOPSIS
function a = squeeze(a)
DESCRIPTION
 c = squeeze(a) : remove singleton dimensions from iData objects/arrays
   @iData/squeeze returns an object B with the same elements as
    A but with all the singleton dimensions removed.  A singleton
    is a dimension such that size(A,dim)==1.  2-D arrays are
    unaffected by squeeze so that row vectors remain rows.
   In addition, to further 'clean' an object, use: fill(a) and pack(a)
 input:  a: object or array (iData)
 output: c: object or array (iData)
 ex:     c=squeeze(iData(rand(5,1,3)));
 Version: oct.. 23, 2018
 See also iData, iData/size, iData/resize, iData/permute, iData/reshape, iData/fill
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
isempty isempty(s) : true for empty iData object
isequal c = isequal(a,b) : full numerical equality comparison of iData objects
isnumeric b = isnumeric(s) : True for numeric iData object elements
isscalar b = isscalar(s) : True for scalar iData objects
isvector b = isvector(s) : True for vector iData object
ndims d = ndims(s) : get the dimensionality of iData object
ones s = ones(s,N,M,P,...) : initialize an iData array
reshape c = reshape(a) : reshape the object Signal
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
subsref b = subsref(a,s) : iData indexed references
This function is called by:
plot h = plot(s, method, ...) : plot iData object
resize c = resize(a) : resize/rebin the object Signal
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
subplot h = subplot(s) : plot iData array as subplots
subsref b = subsref(a,s) : iData indexed references