ifit.mccode.org - Description of strfind
Home > Objects > @iData > strfind.m
iFit/strfind
PURPOSE
[match, field]=strfind(s, pattern, option) : search for pattern in iData
SYNOPSIS
function [match, field] = strfind(s, varargin)
DESCRIPTION
 [match, field]=strfind(s, pattern, option) : search for pattern in iData
   @iData/strfind function to look for patterns stored in iData
   [match,field] = findfstr(iData, pattern) returns the string containg 'str'
     and the field name it appears in. If 'pattern' is set to '', the content of all
     character fields is returned.
   The 'option' may contain 'exact' to search for the exact occurence, and 'case'
   to specifiy a case sensitive search.
 input:  s: object or array (iData)
         pattern: string to search in object, or '' (char).
         option: 'exact' 'case' or '' (char)
 output: match: content of iData fields that contain 'str' (cellstr)
         field: name of iData fields that contain 'str' (cellstr)
 ex:     a=iData('sv1850.scn'); strfind(a,'ILL') or strfind(a,'TITLE','case')
 Version: oct.. 23, 2018
 See also iData, iData/set, iData/get, iData/findobj, iData/findfield
CROSS-REFERENCE INFORMATION
This function calls:
findstr [match, field]=findstr(s, str, option) : look for strings stored in iData
This function is called by:
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
deconv c = deconv(a,b) : computes the deconvolution of iData objects
edit edit(s) : edit iData object Signal/Monitor
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
findobj [s,...]=findobj(s,...) : look for existing iData objects
findstr [match, field]=findstr(s, str, option) : look for strings stored in iData
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
interp [b...] = interp(s, ...) : interpolate iData object
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
plot h = plot(s, method, ...) : plot iData object
saveas f = saveas(s, filename, format, options) : save iData object into various data formats
slice slice(s) : Plot a 2D/3D object with slice rendering