ifit.mccode.org - Description of subsasgn
Home > Objects > @iData > subsasgn.m
iFit/subsasgn
PURPOSE
b = subsasgn(a,index,b) : iData indexed assignement
SYNOPSIS
function b = subsasgn(a,S,val)
DESCRIPTION
 b = subsasgn(a,index,b) : iData indexed assignement
   @iData/subsasgn: function defines indexed assignement
   such as a(1:2,3) = b
   The special syntax a{0} multiplies the value by the Monitor and then assigns
   the Signal, and a{n} assigns the axis of rank n.
     When the assigned value is a char, the axis definition is set (as in setaxis).
     When the assigned value is numeric, the axis value is set (as in set).
   The special syntax a{'alias'} is a quick way to define an alias.
 Version: oct.. 23, 2018
 See also iData, iData/subsref
CROSS-REFERENCE INFORMATION
This function calls:
char c = char(s) : convert iData into character
diff b = diff(s) : computes the difference long 1st axis of iData object
double d = double(s) : convert iData into doubles
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
isempty isempty(s) : true for empty iData object
isfield b = isfield(s, field) : check existence of field/alias in iData objects
islogical b = islogical(s) : True for logical iData object elements
isnumeric b = isnumeric(s) : True for numeric iData object elements
isscalar b = isscalar(s) : True for scalar iData objects
isvector b = isvector(s) : True for vector iData object
label b = label(s, alias, label) : Change iData label for a given alias/axis
mean b = mean(s, dim) : mean value of iData object
ndims d = ndims(s) : get the dimensionality of iData object
ones s = ones(s,N,M,P,...) : initialize an iData array
prod s = prod(a,dim) : computes the product of iData objects elements
reshape c = reshape(a) : reshape the object Signal
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references
transpose b = transpose(s) : non-conjugate transpose of iData object
union [ai,bi] = union(a, b) : computes object union area and values
This function is called by:
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
subsasgn b = subsasgn(a,index,b) : iData indexed assignement