ifit.mccode.org - Description of subsindex
Home > Objects > @iData > subsindex.m
iFit/subsindex
PURPOSE
d = subsindex(s) : subscript index for iData objects
SYNOPSIS
function y = subsindex(s)
DESCRIPTION
 d = subsindex(s) : subscript index for iData objects
   @iData/subsindex: subscript index for iData objects
   I = subsindex(S) is called for the syntax 'X(S)' to use S as an index.
   The returned index is the convertion of S to integer.
 Version: oct.. 23, 2018
 See also iData, iData/subsasgn, iData/subsref
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
get [...] = get(s, 'PropertyName', ...) : get iData object properties
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
This function is called by: