ifit.mccode.org - Description of times
Home > Objects > @iData > times.m
iFit/times
PURPOSE
c = times(a,b) : computes the product of iData objects
SYNOPSIS
function c = times(a,b)
DESCRIPTION
 c = times(a,b) : computes the product of iData objects
   @iData/times (*) function to compute the product of data sets=a.*b
     the square of a single iData object should rather be computed
     using the power law.
 input:  a: object or array (iData or numeric)
         b: object or array (iData or numeric)
 output: c: object or array (iData)
 ex:     c=a.*2;
 Version: oct.. 23, 2018
 See also iData, iData/minus, iData/plus, iData/times, iData/rdivide, iData/power
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
This function is called by:
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
setaxis s = setaxis(s, rank, alias, value) : set iData axes
subsref b = subsref(a,s) : iData indexed references