ifit.mccode.org - Description of union
Home > Objects > @iData > union.m
iFit/union
PURPOSE
[ai,bi] = union(a, b) : computes object union area and values
SYNOPSIS
function [ai,bi] = union(a, b)
DESCRIPTION
 [ai,bi] = union(a, b) : computes object union area and values
   @iData/union function to pre-combine data sets
   This function computes the common axes union between data sets
   Resulting objects are returned, e.g. for performing further operations
     ai = union(a) where 'a' is an object array computes union of all elements
 input:  a: object or array (iData)
         b: object (iData)
 output: b: object or array (iData)
 ex:     b=union(a, a);
 Version: oct.. 23, 2018
 See also iData, iData/setaxis, iData/getaxis, iData/intersect
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
interp [b...] = interp(s, ...) : interpolate iData object
isempty isempty(s) : true for empty iData object
isequal c = isequal(a,b) : full numerical equality comparison of iData objects
ndims d = ndims(s) : get the dimensionality of iData object
union [ai,bi] = union(a, b) : computes object union area and values
This function is called by:
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
pca [b] = pca(X, k) : Principal component analysis of iData object(s)
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
union [ai,bi] = union(a, b) : computes object union area and values