ifit.mccode.org - Description of version
Home > Objects > @iData > version.m
iFit/version
PURPOSE
v = version(iData): iData class version
SYNOPSIS
function [b, vers] = version(a,long_request)
DESCRIPTION
 v = version(iData): iData class version
   @iData/version: version of the iData class library
 Version: oct.. 23, 2018
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
This function is called by:
commandhistory commandhistory(s) : show the command history of iData object
doc doc(iData): iData web page documentation
edit edit(s) : edit iData object Signal/Monitor
iData
saveas f = saveas(s, filename, format, options) : save iData object into various data formats