ifit.mccode.org - Description of zeros
Home > Objects > @iData > zeros.m
iFit/zeros
PURPOSE
s = zeros(s,N,M,P,...) : initialize an iData array
SYNOPSIS
function s = zeros(iData_in,varargin)
DESCRIPTION
 s = zeros(s,N,M,P,...) : initialize an iData array
   @iData/zeros function to create an array of 's' iData objects
   The object 's' is duplicated into an array. Use s=iData to get an empty array.
 input:  s: object or array (iData)
 output: b: object or array (iData)
 ex: zeros(iData,5,5) will create a 5-by-5 empty iData array
     zeros(s,5,5) will return a 5-by-5 array filled with 's'
 Version: oct.. 23, 2018
 See also iData
CROSS-REFERENCE INFORMATION
This function calls:
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
iData
isempty isempty(s) : true for empty iData object
reshape c = reshape(a) : reshape the object Signal
size size(s) : get iData object size (number of elements)
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
caxis c = caxis(s, h) : Use the 2D/3D data as the colormap (CData property) in current object.
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
conv c = conv(a,b) : computes the convolution of iData objects
copyobj b = copyobj(s) : makes a copy of iData object
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
dog s= dog(dim,a) : split iData objects elements along dimension
edit edit(s) : edit iData object Signal/Monitor
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
fill FILL fill-in over missing data
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
imroi imroi: define a region of interest on a data set
interp [b...] = interp(s, ...) : interpolate iData object
intersect [ai,bi] = intersect(a, b) : computes object intersection area and values
isempty isempty(s) : true for empty iData object
isfield b = isfield(s, field) : check existence of field/alias in iData objects
isvector b = isvector(s) : True for vector iData object
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
logspace v = logspace(a,b,n) : creates a logarithmically spaced vector of objects
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
mean b = mean(s, dim) : mean value of iData object
median b = median(s, dim) : median value of iData object
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
mtimes c = mtimes(a,b) : computes the matrix product of iData objects
ndims d = ndims(s) : get the dimensionality of iData object
ones s = ones(s,N,M,P,...) : initialize an iData array
pack b = pack(a) : compress iData storage to save memory
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
reducevolume h = reducevolume(s, factor) : reduce an iData object size
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
smooth Z = smooth(Y) : smooth iData objects
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
zeros s = zeros(s,N,M,P,...) : initialize an iData array