ifit.mccode.org - Description of zlabel
Home > Objects > @iData > zlabel.m
iFit/zlabel
PURPOSE
b = zlabel(s,label) : Change iData Z axis label
SYNOPSIS
function a = zlabel(a, lab)
DESCRIPTION
 b = zlabel(s,label) : Change iData Z axis label
   @iData/zlabel function to change the Z axis (rank 3) label
     zlabel(s) returns the current Z axis label
   The input iData object is updated if no output argument is specified.
 input:  s: object or array (iData)
         label: new Z label (char/cellstr)
 output: b: object or array (iData)
 ex:     b=zlabel(a);
 Version: oct.. 23, 2018
 See also iData, iData/plot, iData/xlabel, iData/ylabel, iData/label, iData/clabel
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
label b = label(s, alias, label) : Change iData label for a given alias/axis
This function is called by:
help c = help(s) : display iData information as a Dialogue window
plot h = plot(s, method, ...) : plot iData object
slice slice(s) : Plot a 2D/3D object with slice rendering