ifit.mccode.org - Description of cellstr
Home > Objects > @iFunc > cellstr.m
iFit/cellstr
PURPOSE
ret = cellstr(s) : convert iFunc into a cell of strings
SYNOPSIS
function [ret, header] = cellstr(s)
DESCRIPTION
 ret = cellstr(s) : convert iFunc into a cell of strings
   @iFunc/cellstr: function to convert iFunc objects into a cell of
       strings e.g. for further evaluation.
   Returns the iFunc expression to evaluate
 input:  s: object or array (iFunc)
 output: ret: iFunc identification (cellstr)
 Version: oct.. 23, 2018
 See also  iFunc/struct, iFunc/char
CROSS-REFERENCE INFORMATION
This function calls:
cellstr ret = cellstr(s) : convert iFunc into a cell of strings
char ret = char(s) : convert iFunc into character
isempty isempty(s) : true for empty iFunc object
isfield b = isfield(s, field) : check existence of field/parameter in model objects
This function is called by:
cellstr ret = cellstr(s) : convert iFunc into a cell of strings
char ret = char(s) : convert iFunc into character
disp disp(s) : display iFunc object (details)
display d = display(s) : display iFunc object (from command line)
feval [signal, model, axes, name] = feval(model, parameters, x,y, ...) evaluate a function
findfield [match, types, nelements]=findfield(iFunc, field, option) : look for iFunc fields
mlock b = mlock(s, parameters, ...) : sets parameter lock (fix) for further fit using the model 's'
munlock b = munlock(s, parameters, ...) : free parameter lock (clear) for further fit using the model 's'
plot h = plot(model, parameters, axes, ...) plot a model
publish b = publish(s) : export the Model object as an HTML document.
saveas f = saveas(s, filename, format, options) : save iFunc object into various data formats
subsasgn b = subsasgn(a,index,b) : iFunc indexed assignement
xlim b = xlim(s, parameters, [min max], ...) : sets parameter bounds (min,max) for further fit using the model 's'