ifit.mccode.org - Description of iFunc
Home > Objects > @iFunc > iFunc.m
iFit/iFunc
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
abs b = abs(s) : absolute value of iFunc object
disp disp(s) : display iFunc object (details)
feval [signal, model, axes, name] = feval(model, parameters, x,y, ...) evaluate a function
fix b = fix(s, parameters, ...) : sets parameter lock (fix) for further fit using the model 's'
iFunc
isempty isempty(s) : true for empty iFunc object
isfield b = isfield(s, field) : check existence of field/parameter in model objects
load d = load(s, file): iFunc Model loader
This function is called by:
copyobj b = copyobj(s) : makes a copy of iFunc object
get [...] = get(s, 'PropertyName', ...) : get iFunc object properties
iFunc
load d = load(s, file): iFunc Model loader
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iFunc properties
subsasgn b = subsasgn(a,index,b) : iFunc indexed assignement
subsref b = subsref(a,s) : iFunc indexed references
zeros s = zeros(s,N,M,P,...) : initialize an iFunc array