ifit.mccode.org - Description of munlock
Home > Objects > @iFunc > munlock.m
iFit/munlock
PURPOSE
b = munlock(s, parameters, ...) : free parameter lock (clear) for further fit using the model 's'
SYNOPSIS
function a = munlock(a, varargin)
DESCRIPTION
 b = munlock(s, parameters, ...) : free parameter lock (clear) for further fit using the model 's'
   @iFunc/munlock unlock model parameters during further fit process.
     to unlock/clear a parameter model, use munlock(model, parameter)
   To unlock/free a set of parameters, you may use a regular expression as:
     munlock(model, regexp(model.Parameters, 'token1|token2|...'))
   munlock(model, {'Parameter1', 'Parameter2', ...})
     unlock/free parameter for further fits
   munlock(model, [1 2 ...])
     unlock/free parameters given their index
   munlock(model, 'all')
     unlock/free all parameters
   munlock(model, 'none')
     fix/lock all parameters
   munlock(model)
     display free parameters
 input:  s: object or array (iFunc)
 output: b: object or array (iFunc)
 ex:     b=munlock(a,'Intensity');
 Version: oct.. 23, 2018
 See also iFunc, iFunc/fits, iFunc/mlock, iFunc/xlim
CROSS-REFERENCE INFORMATION
This function calls:
cellstr ret = cellstr(s) : convert iFunc into a cell of strings
feval [signal, model, axes, name] = feval(model, parameters, x,y, ...) evaluate a function
isempty isempty(s) : true for empty iFunc object
mlock b = mlock(s, parameters, ...) : sets parameter lock (fix) for further fit using the model 's'
subsasgn b = subsasgn(a,index,b) : iFunc indexed assignement
This function is called by:
mlock b = mlock(s, parameters, ...) : sets parameter lock (fix) for further fit using the model 's'