ifit.mccode.org - Description of iData_vDOS
Home > Objects > iData_subclasses > @iData_vDOS > iData_vDOS.m
iFit/iData_vDOS
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
iData_vDOS
multi_phonons iData_vDOS: multi_phonons: compute the integrated multi-phonon generalised density of states (gDOS) from an initial vibrational density of states (vDOS)
This function is called by:
iData_vDOS
multi_phonons iData_vDOS: multi_phonons: compute the integrated multi-phonon generalised density of states (gDOS) from an initial vibrational density of states (vDOS)