ifit.mccode.org - Description of symmetrize
Home > Objects > iData_subclasses > @iData_Sqw2D > symmetrize.m
iFit/symmetrize
PURPOSE
iData_Sqw2D: symmetrize(s): extend the S(|q|,w) in both energy sides
SYNOPSIS
function s=symmetrize(s)
DESCRIPTION
 iData_Sqw2D: symmetrize(s): extend the S(|q|,w) in both energy sides
  The resulting S(q,w) is the combination of S(q,w) and S(q,-w), which
  is thus symmetric in energy:
     S(q,w) = S(q,-w)
  The incoming data set should NOT contain the Bose factor, that is it
    should be 'classical'.
  To obtain a 'classical' S(q,w) from an experiment, use first:
    deBosify(s, T)
 The positive energy values in the S(q,w) map correspond to Stokes processes,
 i.e. material gains energy, and neutrons loose energy when down-scattered.
 syntax:
   s_sym = symmetrize(s)
 input:
   s:  Sqw data set (classical, often labelled as S*)
        2D data set with w as 1st axis (rows, meV), q as 2nd axis (Angs-1).
 output:
   s:  S(|q|,w) symmetrised in energy, classical.
 Example: Sqw=iData_Sqw2D('SQW_coh_lGe.nc'); symmetrize(s);
 See also: iData_Sqw2D/Bosify, iData_Sqw2D/deBosify,
           iData_Sqw2D/dynamic_range, iData_Sqw2D/scattering_cross_section
 (c) E.Farhi, ILL. License: EUPL.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
dynamic_range iData_Sqw2D: dynamic_range: crop the S(|q|,w) to the available dynamic range
muphocor run MUPHOCOR on the given S(q,w) data set, incident wavelength and Temperature
scattering_cross_section iData_Sqw2D: scattering_cross_section: compute the total neutron scattering cross section for