ifit.mccode.org - Description of class2str
Home > Libraries > Loaders > class2str.m
iFit/class2str
PURPOSE
This function creates a string containing Matlab code describing a variable.
SYNOPSIS
function str=class2str(this, data, options)
DESCRIPTION
   This function creates a string containing Matlab code describing a variable.
   class2str(this,data)
     Create a string [ 'this = data;' ]
   class2str(this, data, 'no comments')
     same as above, but removes comments from the output file
   class2str(this, data, 'eval')
     creates a compact evaluable string of the initial data
   class2str(this, data, 'flat')
     creates a flat text with commented data blocks, which is not an m-file,
     but rather a Linux-style config file.
 input arguments:
   this: string containing the name of the object to describe. Use '' to name the
           root level from the input variable name, and ' ' to ignore root level
           in structures.
   data: any data set (struct, array, cell, char, objects)
   options: optinal argument which may contain 'flat', 'no comments','eval'
 output variables:
   str: string which contains a function code to generate the data.
 example:
  data=struct('a',1,'b','a string comment','c',{'cell'});
  str=class2str(data)          % produces a string/script that regenerates data
  str=class2str('this', data)  % idem, but creates 'this' instead of 'data'.
  str=class2str(data, 'flat')  % a kind of config file
  str=class2str(data, 'eval')  % a compact evaluable string
 See also: mat2str, num2str, eval, sprintf
 Part of: Loaders utilities (ifit.mccode.org)
 Author:  E. Farhi <farhi@ill.fr>. oct.. 23, 2018
 (c) E.Farhi, ILL. License: BSD.
CROSS-REFERENCE INFORMATION
This function calls:
class2str This function creates a string containing Matlab code describing a variable.
This function is called by:
class2str This function creates a string containing Matlab code describing a variable.
iLoad [data, loader] = iLoad(file, loader, ...)