ifit.mccode.org - Description of sqw_vaks
Home > Scripts > Models > Factory > sqw_vaks.m
iFit/sqw_vaks
PURPOSE
model = sqw_vaks(p, h,k,l,w, {signal}) : dispersion(HKL) in perovskites ABX3 with DHO(energy)
SYNOPSIS
function signal=sqw_vaks(varargin)
DESCRIPTION
 model = sqw_vaks(p, h,k,l,w, {signal}) : dispersion(HKL) in perovskites ABX3 with DHO(energy)
   iFunc/sqw_vaks: a 4D S(q,w) with a HKL dispersion, and a DHO line
      shape, based on a parameterisation by Vaks, suited for ABX3 perovskite
      compounds. This parameterisation is based on a quadratic expansion of the
      Hamiltonian, valid for e.g. |k|<.3 rlu in a cubic
      crystal and provides energies of TA1,TA2,LA,TO1 and TO2 modes.
 MODEL CREATION
 To build a model, you may use:
   sqw_vaks('gui')     displays a dialogue box
   sqw_vaks            same as above ('gui')
   sqw_vaks('KTaO3')   use parameters for KTaO3 perovskite
   sqw_vaks('BaTiO3')  use parameters for BaTiO3 perovskite
   sqw_vaks('SrTiO3')  use parameters for SrTiO3 perovskite
   sqw_vaks([ ... ])   use a 12 values vector as model parameters
   sqw_vaks('defaults') selects KTaO3
 WARNING:
      Single intensity and line width parameters are used here.
      The HKL position is relative to the closest Bragg peak.
   The acoustic parameters can be related to the elastic constants as:
     At= (C12+2C44)/rho [meV2/rlu2]
     Al=  C44/rho
     Aa= (C11-C12-2C44)/rho
   with rho=density of the crystal [g/cm3]
 MODEL EVALUATION
 Once created, the model is used as:
   value = model(p, qh, qk, ql, w)
   value = iData(model, p, qh, qk, ql, w)
 input:  p: sqw_vaks model parameters (double)
           p(1)=At transverse acoustic [meV2/rlu2]
           p(2)=Al longitudinal acoustic [meV2/rlu2]
           p(3)=Aa anisotropic acoustic [meV2/rlu2]
           p(4)=St soft mode  transverse soft optical [meV2/rlu2]
           p(5)=Sa soft mode  anisotropic soft optical [meV2/rlu2]
           p(6)=Vt transverse acoustic-optical coupling [meV2/rlu2]
           p(7)=Va anisotropic acoustic-optical coupling [meV2/rlu2]
           p(8)=w0 soft mode frequency at q=0, depends on temperature [meV]
           p(9)=Gamma   dispersion DHO half-width in energy [meV]
           p(10)=Temperature of the material [K]
           p(11)=Amplitude
           p(12)=Background (constant)
          or 'KTaO3','BaTiO3','SrTiO3' for predefined settings
         qh: axis along QH in rlu (row,double)
         qk: axis along QK in rlu (column,double)
         ql: axis along QL in rlu (page,double)
         w:  axis along energy in meV (double)
    signal: when values are given, a guess of the parameters is performed (double)
 output: signal: model value
 Example:
 s=sqw_vaks('KTaO3'); qh=linspace(0,.5,50);qk=qh; ql=qh; w=linspace(0.01,10,51);
 f=iData(s,[],qh,qk,ql,w); scatter3(log(f(:,:,1,:)),'filled');
 References: E. Farhi et al, EPJB, 15 (2000) pp 615-623. DOI: 10.1007/s100510051164
             A.K. Tagantsev et al, Nature Comm, 4 (2013) 2229. DOI: 10.1038/ncomms3229
             V.G. Vaks, Introduction to the Microscopic Theory of Ferroelectrics (Nauka, Moscow, 1973)
 Version: oct.. 23, 2018
 See also iData, iFunc/fits, iFunc/plot, gauss, sqw_phonons, sqw_sine3d
   sqw_cubic_monoatomic, <a href="matlab:doc(iFunc,'Models')">iFunc:Models</a>
 (c) E.Farhi, ILL. License: EUPL.
CROSS-REFERENCE INFORMATION
This function calls:
sqw_vaks model = sqw_vaks(p, h,k,l,w, {signal}) : dispersion(HKL) in perovskites ABX3 with DHO(energy)
sqw_vaks model = sqw_vaks(p, h,k,l,w, {signal}) : dispersion(HKL) in perovskites ABX3 with DHO(energy)
sqw_vaks model = sqw_vaks(p, h,k,l,w, {signal}) : dispersion(HKL) in perovskites ABX3 with DHO(energy)
This function is called by:
sqw_vaks model = sqw_vaks(p, h,k,l,w, {signal}) : dispersion(HKL) in perovskites ABX3 with DHO(energy)
sqw_vaks model = sqw_vaks(p, h,k,l,w, {signal}) : dispersion(HKL) in perovskites ABX3 with DHO(energy)
sqw_vaks model = sqw_vaks(p, h,k,l,w, {signal}) : dispersion(HKL) in perovskites ABX3 with DHO(energy)