ifit.mccode.org - Description of band_structure
Home > Objects > iFunc_subclasses > @iFunc_Sqw4D > band_structure.m
iFit/band_structure
PURPOSE
band_structure: evaluates a 4D S(q,w) model along specified k-path / bands
SYNOPSIS
function [S, qLim, fig] = band_structure(f, qLim, E, options)
DESCRIPTION
 band_structure: evaluates a 4D S(q,w) model along specified k-path / bands
    band_structure(f, kpath, w, options)
      The k-path can be given as a cell containing 3-values (HKL) vectors, or
        a n x 3 matrix, each row being a HKL location.
      The energy range can be entered as a vector, or a [min max] pair.
      Refer to https://en.wikipedia.org/wiki/Brillouin_zone and
             http://lamp.tu-graz.ac.at/~hadley/ss1/bzones/ to get the standard
      points in the Brillouin zone.
      The bands intensity is computed along the path. For neutron scattering,
        as all standard points in the Brillouin zone are centered around 0 and
        the intensity is proportional to |Q.e|^2, all transverse modes are extinct.
      To get the proper band intensity around a given Bragg peak G, the k-path
        should be shifted by G.
    band_structure(f);
      plots the dispersion curves following the BZ points for the
      crystal spacegroup, and using the maximum excitation energy.
    [S,k] = band_structure(...)
      returns the dispersion curves data set (iData), and the k-path used.
    When the command is followed by ';' or options contains 'plot', a plot is
    generated.
 Example:
   S = band_structure(sqw_cubic_monoatomic, '', [0 10]); plot(log10(S));
   S = sqw_phonons('POSCAR_Al','emt','metal'); band_structure(S);
 input:
   f:    a 4D HKLE model S(q,w) (iFunc)
   path: a list of k-locations given as a cell/array of HKL locations (cell or matrix)
         can also be 'Cubic','Hexagonal','Trigonal','Tetragonal','Orthorhombic',
                     'Monoclinic','Triclinic','fcc','bcc'
         can also be given as a list of BZ points, such as:
           {'Gamma' 'K' 'M' 'Gamma' 'A' 'H' 'L' 'A' }
           which are then defined according to the space group, e.g:
             f.UserData.properties.spacegroup_number
         can be given as a list of HKL locations, such as {[0,0,0],[1,1,1],[1,1,0]}
           or as an array e.g. [0 0 0 ; 1 1 1 ; 1 1 0 ; 0 0 0 ; 0 0 1]
         The path can also be given as a Bragg peak location, e.g. [0 0 1] to compute
           the dispersion around that location using the default K-path in the BZ.
         when not given or empty, this is guessed from the crystal spacegroup.
   w:    a vector of energies (4-th axis) for which to evaluate the model (double)
         can also be given as Emax, or [ Emin Emax ]
         when not given or empty, the maximum excitation energy is used.
   options: plotting option (string). Can contain 'plot' 'THz','cm-1','meV'.
         The 'plot' option also displays the density of states, when available.
         The 'newplot' option does the same but opens a new figure instead of
         re-using an existing one.
 output:
   S:    the dispersion W(HKL) computed along the path (iData)
   k:    the k-path used to generate the dispersion curves (matrix, HKL list)
   fig:  figure handle generated when options contains 'plot' or no output.
 Version: oct.. 23, 2018
 See also sqw_cubic_monoatomic, sqw_sine3d, sqw_vaks, sqw_spinw
   iFunc_Sqw4D/powder, <a href="matlab:doc(iFunc,'Models')">iFunc:Models</a>
 (c) E.Farhi, ILL. License: EUPL.
CROSS-REFERENCE INFORMATION
This function calls:
band_structure band_structure: evaluates a 4D S(q,w) model along specified k-path / bands
dos iFunc_Sqw4D: dos: compute the density of states (vDOS)
max iFunc_Sqw4D: max: get a quick estimate of the max dispersion frequency
This function is called by:
band_structure band_structure: evaluates a 4D S(q,w) model along specified k-path / bands
iFunc_Sqw4D