ifit.mccode.org - Description of thermochemistry
Home > Objects > iFunc_subclasses > @iFunc_Sqw4D > thermochemistry.m
iFit/thermochemistry
PURPOSE
iFunc_Sqw4D/thermochemistry: compute thermodynamic quantities for 4D S(q,w) models.
SYNOPSIS
function [t, fig]=thermochemistry(s, T, options)
DESCRIPTION
 iFunc_Sqw4D/thermochemistry: compute thermodynamic quantities for 4D S(q,w) models.
 compute thermodynamics quantities for a 4D S(q,w) Model.
 When missing, the phonon (vibrational) density of states (vDOS) is estimated
 from e.g. the evaluation of the 4D sqw phonons object.
 The input 4D model should be e.g. a 4D phonon one, with axes qh,qk,ql,energy
 in [rlu^3,meV]. The evaluation of the model should provide the density of states
 in model.UserData.DOS as an iData object.
 the function returns an array of iData objects:
   DOS                                 [modes/energy unit/unit cell]
   DOS_partials                    DOS partials (one per mode)
   entropy                           S [eV/K/cell]
   internal_energy                   U [eV/cell]
   helmholtz_energy                  F [eV/cell]
   heat_capacity at constant volume Cv [eV/K/cell]
 input:
   s: a 4D sqw phonons model [K,H,L,Energy] (iFunc)
   T: temperature range. When not given, T=1:500 [K]
   options: can be 'plot' to display the results.
         The 'newplot' option does the same but opens a new figure instead of
         re-using an existing one.
 output:
   t: structure with [DOS, DOS_partials, S U F Cv ]
   fig: figure handle
 Reference: https://wiki.fysik.dtu.dk/ase/ase/thermochemistry/thermochemistry.html#background
            D.A. McQuarrie. Statistical Mechanics. University Science Books, 2000.
CROSS-REFERENCE INFORMATION
This function calls:
dos iFunc_Sqw4D: dos: compute the density of states (vDOS)
thermochemistry iFunc_Sqw4D/thermochemistry: compute thermodynamic quantities for 4D S(q,w) models.
This function is called by:
publish iFunc_Sqw4D: publish: generate a readable HTML document and export results to
thermochemistry iFunc_Sqw4D/thermochemistry: compute thermodynamic quantities for 4D S(q,w) models.