ifit.mccode.org - Description of iFunc_McCode
Home > Objects > iFunc_subclasses > @iFunc_McCode > iFunc_McCode.m
iFit/iFunc_McCode
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
dialog run a McCode instrument model and request instrument parameters in a dialogue
iFunc_McCode
plot iFunc_McCode/plot: runs the model in --trace mode and capture the output
This function is called by:
iFunc_McCode