ifit.mccode.org - Description of ceil
Home > Objects > @iData > ceil.m
iFit/ceil
PURPOSE
b = ceil(s) : upper integer round of iData object
SYNOPSIS
function a = ceil(a)
DESCRIPTION
 b = ceil(s) : upper integer round of iData object
   @iData/ceil function to round the elements of 's' to the nearest integers
   towards plus infinity.
 input:  s: object or array (iData)
 output: b: object or array (iData)
 ex:     b=ceil(a);
 Version: oct.. 23, 2018
 See also iData, iData/floor, iData/ceil, iData/round
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
colon b = colon(s) : vector of arrays
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
reducevolume h = reducevolume(s, factor) : reduce an iData object size
resize c = resize(a) : resize/rebin the object Signal
smooth Z = smooth(Y) : smooth iData objects
subplot h = subplot(s) : plot iData array as subplots