ifit.mccode.org - Description of cell
Home > Objects > @iData > cell.m
iFit/cell
PURPOSE
[content,fields]=cell(s) : convert iData objects into cells
SYNOPSIS
function [content,fields]=cell(s)
DESCRIPTION
 [content,fields]=cell(s) : convert iData objects into cells
   @iData/cell function to convert iData objects into cells
 input:  s: iData single object (iData)
 output: content: content of the iData structure (cell)
         fields:  field names of the iData object (cell)
 Version: oct.. 23, 2018
 See also  iData/cell, iData/double, iData/struct,
           iData/char, iData/size
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
iData
isempty isempty(s) : true for empty iData object
size size(s) : get iData object size (number of elements)
This function is called by:
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
commandhistory commandhistory(s) : show the command history of iData object
corrcoef c = corrcoef(a,b) : correlation coefficient with an iData object
dog s= dog(dim,a) : split iData objects elements along dimension
double d = double(s) : convert iData into doubles
fileattrib [attribute, link] = fileattrib(s, field) : return a field Attribute
find d = find(s) : find iData signal non zeros values
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
findstr [match, field]=findstr(s, str, option) : look for strings stored in iData
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
getframe frame = getframe(s, dim, options) : create an iData object thumbnail/frame matrix
gradient g = gradient(a, dim) : computes the gradient (derivative) of iData objects
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
interp [b...] = interp(s, ...) : interpolate iData object
isfield b = isfield(s, field) : check existence of field/alias in iData objects
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
label b = label(s, alias, label) : Change iData label for a given alias/axis
load d = load(s, file, loader, ...): iData file loader
logical d = logical(s) : convert iData into logical array
pack b = pack(a) : compress iData storage to save memory
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
reducevolume h = reducevolume(s, factor) : reduce an iData object size
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
saveas f = saveas(s, filename, format, options) : save iData object into various data formats
single d = single(s) : convert iData into single floats