ifit.mccode.org - Description of char
Home > Objects > @iData > char.m
iFit/char
PURPOSE
c = char(s) : convert iData into character
SYNOPSIS
function c = char(s)
DESCRIPTION
 c = char(s) : convert iData into character
   @iData/char: function to convert iData objects into char
   returns the iData title/filename
 input:  s: object or array (iData)
 output: c: iData identification (char)
 Version: oct.. 23, 2018
 See also  iData/cell, iData/double, iData/struct,
           iData/char, iData/size
CROSS-REFERENCE INFORMATION
This function calls:
char c = char(s) : convert iData into character
end b = end(s,index,n) : end value for iData objects
size size(s) : get iData object size (number of elements)
transpose b = transpose(s) : non-conjugate transpose of iData object
This function is called by:
char c = char(s) : convert iData into character
commandhistory commandhistory(s) : show the command history of iData object
disp disp(s) : display iData object (details)
edit edit(s) : edit iData object Signal/Monitor
fileattrib [attribute, link] = fileattrib(s, field) : return a field Attribute
findstr [match, field]=findstr(s, str, option) : look for strings stored in iData
get [...] = get(s, 'PropertyName', ...) : get iData object properties
help c = help(s) : display iData information as a Dialogue window
load d = load(s, file, loader, ...): iData file loader
plot h = plot(s, method, ...) : plot iData object
saveas f = saveas(s, filename, format, options) : save iData object into various data formats
slice slice(s) : Plot a 2D/3D object with slice rendering
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references