ifit.mccode.org - Description of circshift
Home > Objects > @iData > circshift.m
iFit/circshift
PURPOSE
b=circshift(a, rank, shift): shifts the axis of specified rank by a value
SYNOPSIS
function a=circshift(a, dim, shift)
DESCRIPTION
 b=circshift(a, rank, shift): shifts the axis of specified rank by a value
   @iData/circshift function to shift iData object axes
     This is equivalent to a{rank} = a{rank}+shift;
 input:  a:     object or array (iData)
         rank:  axis rank (scalar)
         shift: value to shift the axis with (scalar)
 output: b: object or array (iData)
 Version: oct.. 23, 2018
 See also  iData/getaxis, iData/setaxis
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
setaxis s = setaxis(s, rank, alias, value) : set iData axes
This function is called by:
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData