ifit.mccode.org - Description of combine
Home > Objects > @iData > combine.m
iFit/combine
PURPOSE
c = combine(a,b) : combines iData objects
SYNOPSIS
function c = combine(a,varargin)
DESCRIPTION
 c = combine(a,b) : combines iData objects
   @iData/combine (\) function to combine data sets
     A fast notation for combine(a,b) is a\b
     To combine a set of iData objects use combine([ a b c ...])
     The combine operator (aka merge) is defined as:
       (S1+S2) over monitor (M1+M2)
     where S1,M1 and S2,M2 and the Signal and Monitor of the two objects.
 input:  a: object or numerical array (iData or numeric)
         b: object or numerical array (iData or numeric)
 output: c: object (iData)
 ex:     c=combine(a,b); or combine([ a b ])
 Version: oct.. 23, 2018
 See also iData, iData/minus, iData/plus, iData/times, iData/rdivide
CROSS-REFERENCE INFORMATION
This function calls:
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
combine c = combine(a,b) : combines iData objects
end b = end(s,index,n) : end value for iData objects
isvector b = isvector(s) : True for vector iData object
This function is called by:
combine c = combine(a,b) : combines iData objects
ldivide c = ldivide(a,b) : fast notation for combine iData objects
mean b = mean(s, dim) : mean value of iData object
median b = median(s, dim) : median value of iData object
mldivide c = mldivide(a,b) : a\b is fast notation for combine(a,b)