ifit.mccode.org - Description of commandhistory
Home > Objects > @iData > commandhistory.m
iFit/commandhistory
PURPOSE
commandhistory(s) : show the command history of iData object
SYNOPSIS
function [s,fig] = commandhistory(a, fig, varargin)
DESCRIPTION
 commandhistory(s) : show the command history of iData object
   @iData/commandhistory shows the list of commands that have been used to
   produce the current iData object.
 a=commandhistory(a, message)
   adds a message to the command history and update the current object
 input:  s: object or array (iData)
 output: b: command history (char/cell)
 ex:     b=commandhistory(a);
 Version: oct.. 23, 2018
 See also iData, iData/disp, iData/display
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
char c = char(s) : convert iData into character
commandhistory commandhistory(s) : show the command history of iData object
disp disp(s) : display iData object (details)
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
isempty isempty(s) : true for empty iData object
isfield b = isfield(s, field) : check existence of field/alias in iData objects
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
size size(s) : get iData object size (number of elements)
version v = version(iData): iData class version
This function is called by:
commandhistory commandhistory(s) : show the command history of iData object
help c = help(s) : display iData information as a Dialogue window