ifit.mccode.org - Description of contour3
Home > Objects > @iData > contour3.m
iFit/contour3
PURPOSE
h = contour3(s,option) : Plot a 2D/3D object as 3D contour
SYNOPSIS
function h = contour3(a, option, varargin)
DESCRIPTION
 h = contour3(s,option) : Plot a 2D/3D object as 3D contour
   @iData/contour3 function to plot a 2D or 3D object
     2D objects are shown as a 3D contour
   contour3(a, option, levels) specifies the number of coutour lines to plot.
 input:  s: object or array (iData)
         option: global option for 2D and 3D plots:
                 flat, interp, faceted (for shading)
                 transparent, light, clabel, colorbar, hide_axes
                 axis tight, axis auto, view2, view3
                 painters (bitmap drawing), zbuffer (vectorial drawing)
 output: h: graphics object handles (cell)
 ex:     contour3(iData(peaks)); contour3(iData(flow));
 Version: oct.. 23, 2018
 See also iData, iData/plot, iData/contour, iData/contourf
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
plot h = plot(s, method, ...) : plot iData object
This function is called by:
plot h = plot(s, method, ...) : plot iData object