ifit.mccode.org - Description of convn
Home > Objects > @iData > convn.m
iFit/convn
PURPOSE
c = convn(a,b) : computes the convolution of an iData object with a response function
SYNOPSIS
function c = convn(a,b)
DESCRIPTION
 c = convn(a,b) : computes the convolution of an iData object with a response function
   @iData/convn function to compute the convolution of data sets with automatic centering
     and normalization of the filter. This is a shortcut for
       conv(a,b, 'same pad background center normalize')
     When used with a single scalar value, it is used as a width to build a
       gaussian function, with same width along all dimensions
     When used with a vector of same length as the object dimension, a nD
       gaussian function with width as vector elements along each diemsions
 input:  a: object or array, signal (iData or numeric)
         b: object or array, filter (iData or numeric)
 output: c: object or array (iData)
 ex:     c=convn(a,b);
 Version: oct.. 23, 2018
 See also iData, iData/times, iData/conv, iData/fft, iData/xcorr, fconv, fconvn, fxcorr
CROSS-REFERENCE INFORMATION
This function calls:
double d = double(s) : convert iData into doubles
end b = end(s,index,n) : end value for iData objects
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
isscalar b = isscalar(s) : True for scalar iData objects
mean b = mean(s, dim) : mean value of iData object
ndims d = ndims(s) : get the dimensionality of iData object
This function is called by:
smooth Z = smooth(Y) : smooth iData objects