ifit.mccode.org - Description of ctranspose
Home > Objects > @iData > ctranspose.m
iFit/ctranspose
PURPOSE
b = ctranspose(s) : complex conjugate transpose of iData object
SYNOPSIS
function a = ctranspose(a)
DESCRIPTION
 b = ctranspose(s) : complex conjugate transpose of iData object
   @iData/ctranspose function to return the complex conjugate transpose of data sets
     which corresponds to syntax: b = s'
   When the argument is an iData array, the whole array is transposed. To
     transpose each array element, use transpose(s) or b=s.'
 input:  s: object or array (iData)
 output: b: object or array (iData)
 ex:     b=ctranspose(a);
 Version: oct.. 23, 2018
 See also iData, iData/transpose, iData/ctranspose, iData/setaxis, iData/getaxis
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
ndims d = ndims(s) : get the dimensionality of iData object
permute c = permute(a, order) : Permute object dimensions from iData objects/arrays
This function is called by: