ifit.mccode.org - Description of display
Home > Objects > @iData > display.m
iFit/display
PURPOSE
d = display(s) : display iData object (from command line)
SYNOPSIS
function d = display(s_in, name)
DESCRIPTION
 d = display(s) : display iData object (from command line)
 @iData/display function to display iData object.
   Used when no ';' sign follows a iData object in matlab.
 The return value may be catched as a string to display.
 input:  s: object or array (iData)
 output: d: string to display (char)
 ex:     'display(iData)' or 'iData'
 Version: oct.. 23, 2018
 See also iData, iData/disp, iData/get
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
isempty isempty(s) : true for empty iData object
isvector b = isvector(s) : True for vector iData object
ndims d = ndims(s) : get the dimensionality of iData object
size size(s) : get iData object size (number of elements)
title b = title(s,label) : Change iData Signal label
This function is called by:
get [...] = get(s, 'PropertyName', ...) : get iData object properties