ifit.mccode.org - Description of double
Home > Objects > @iData > double.m
iFit/double
PURPOSE
d = double(s) : convert iData into doubles
SYNOPSIS
function a=double(a)
DESCRIPTION
 d = double(s) : convert iData into doubles
   @iData/double function to convert iData object into doubles
 input:  s: object or array (iData)
 output: v: value of the iData Signal/Monitor (double)
 ex:     'double(iData(rand(10)))'
 Version: oct.. 23, 2018
 See also  iData/cell, iData/single, iData/struct,
           iData/char, iData/size
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
double d = double(s) : convert iData into doubles
end b = end(s,index,n) : end value for iData objects
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
size size(s) : get iData object size (number of elements)
This function is called by:
caxis c = caxis(s, h) : Use the 2D/3D data as the colormap (CData property) in current object.
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
conv c = conv(a,b) : computes the convolution of iData objects
convn c = convn(a,b) : computes the convolution of an iData object with a response function
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
deconv c = deconv(a,b) : computes the deconvolution of iData objects
double d = double(s) : convert iData into doubles
edit edit(s) : edit iData object Signal/Monitor
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
interp [b...] = interp(s, ...) : interpolate iData object
isvector b = isvector(s) : True for vector iData object
mtimes c = mtimes(a,b) : computes the matrix product of iData objects
pack b = pack(a) : compress iData storage to save memory
saveas f = saveas(s, filename, format, options) : save iData object into various data formats
std [half_width, center] = std(s, dim) : standard deviation of iData
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references