ifit.mccode.org - Description of edit
Home > Objects > @iData > edit.m
iFit/edit
PURPOSE
edit(s) : edit iData object Signal/Monitor
SYNOPSIS
function h = edit(a, option)
DESCRIPTION
 edit(s) : edit iData object Signal/Monitor
   @iData/edit function to view the Signal/Monitor of a data set.
     The data appears as a spreadsheet (requires Java to be enabled).
   An additional 'option' argument allows to specify what to do with the Table
   d=edit(iData, handle)   The given Table handle is exported into an iData object.
   edit(iData, 'editable') The Table data can be modified after creation.
 input:  s: object or array (iData)
 output: b: object or array (iData)
 ex:     b=edit(a);
 Version: oct.. 23, 2018
 See also iData, iData/uminus, iData/abs, iData/real, iData/imag, iData/uplus
CROSS-REFERENCE INFORMATION
This function calls:
char c = char(s) : convert iData into character
csvwrite f = csvwrite(s, filename, options) : save iData object into a Comma Separated Values (CSV) file
disp disp(s) : display iData object (details)
double d = double(s) : convert iData into doubles
edit edit(s) : edit iData object Signal/Monitor
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
isempty isempty(s) : true for empty iData object
isfield b = isfield(s, field) : check existence of field/alias in iData objects
isscalar b = isscalar(s) : True for scalar iData objects
isvector b = isvector(s) : True for vector iData object
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
ndims d = ndims(s) : get the dimensionality of iData object
not b = not(s) : computes the logical 'not' of iData object
plot h = plot(s, method, ...) : plot iData object
prod s = prod(a,dim) : computes the product of iData objects elements
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
size size(s) : get iData object size (number of elements)
strfind [match, field]=strfind(s, pattern, option) : search for pattern in iData
surf h = surf(s,option) : Plot a 2D/3D object as surface
title b = title(s,label) : Change iData Signal label
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
version v = version(iData): iData class version
xlabel b = xlabel(s,label) : Change iData X axis label
ylabel b = ylabel(s,label) : Change iData Y axis label
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
edit edit(s) : edit iData object Signal/Monitor