ifit.mccode.org - Description of event
Home > Objects > @iData > event.m
iFit/event
PURPOSE
c = event(a) : build an event list
SYNOPSIS
function b = event(a, dim, signal, err, monitor)
DESCRIPTION
 c = event(a) : build an event list
   @iData/event function to transform an object into an event list.
     An nD event list object is a list of points (e.g. one per row) for
       which the points coordinates are given as the n first columns
       and subsequent columns define a Signal.
     event(a) will attempt to guess the dimensionality (up to 3D)
     event(a, dim) specifies the object dimensionality. The first dim
       columns are used for the coordinates. 'dim' is an integer.
     event(a, dim, signal) also specifies which column has to be used as
       Signal. When given as a vector, the norm of the specified columns is used.
     event(a, dim, signal, error, monitor) also specifies which column
       has to be used as Error and Monitor.
     An event list object can be converted back into a mesh-type histogram
     with the meshgrid or hist method, e.g.
       b=event(a); c=meshgrid(b);
     then a and c are close.
 input:  a:   object or array (iData)
         m,n,p...: dimensions (integers)
 output: c: object or array (iData)
 ex:     a=iData(rand(50,4)); b=event(a);
 Version: oct.. 23, 2018
 See also iData, iData/squeeze, iData/size, iData/permute, iData/resize, iData/meshgrid, iData/hist
CROSS-REFERENCE INFORMATION
This function calls:
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
isempty isempty(s) : true for empty iData object
isnumeric b = isnumeric(s) : True for numeric iData object elements
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
ndims d = ndims(s) : get the dimensionality of iData object
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
sqrt b = sqrt(s) : square root value of iData object
sum s = sum(a,dim) : computes the sum of iData objects elements
This function is called by:
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets