ifit.mccode.org - Description of fft
Home > Objects > @iData > fft.m
iFit/fft
PURPOSE
c = fft(a) : computes the Discrete Fourier transform of iData objects
SYNOPSIS
function b = fft(a, op, dim)
DESCRIPTION
 c = fft(a) : computes the Discrete Fourier transform of iData objects
   @iData/fft function to compute the Discrete Fourier transform of data sets
     using the FFT algorithm. The power spectrum density (PSD) is abs(fft)^2.
     fft(a, 'ifft') is equivalent fo ifft(a)
     fft(a, op, dim) and fft(a, dim) apply FFT or iFFT along dimension dim.
 input:  a:   object or array (iData)
         op:  can be 'fft' (default) or 'ifft' (inverse)
         dim: dimension to apply FFT upon. dim=0 for all dimensions.
 output: c: object or array (iData)
 ex:     t=linspace(0,1,1000);
         a=iData(t,0.7*sin(2*pi*50*t)+sin(2*pi*120*t)+2*randn(size(t)));
         c=fft(a); plot(abs(c));
 Version: oct.. 23, 2018
 See also iData, iData/ifft, iData/conv, FFT, IFFT
CROSS-REFERENCE INFORMATION
This function calls:
abs b = abs(s) : absolute value of iData object
copyobj b = copyobj(s) : makes a copy of iData object
diff b = diff(s) : computes the difference long 1st axis of iData object
end b = end(s,index,n) : end value for iData objects
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
ifft c = ifft(a) : computes the inverse Discrete Fourier transform of iData objects
interp [b...] = interp(s, ...) : interpolate iData object
isempty isempty(s) : true for empty iData object
isfield b = isfield(s, field) : check existence of field/alias in iData objects
isnumeric b = isnumeric(s) : True for numeric iData object elements
isscalar b = isscalar(s) : True for scalar iData objects
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
mean b = mean(s, dim) : mean value of iData object
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
ndims d = ndims(s) : get the dimensionality of iData object
prod s = prod(a,dim) : computes the product of iData objects elements
reshape c = reshape(a) : reshape the object Signal
rmaxis s = rmaxis(s, Axis) : delete iData axes
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
ifft c = ifft(a) : computes the inverse Discrete Fourier transform of iData objects