ifit.mccode.org - Description of fill
Home > Objects > @iData > fill.m
iFit/fill
PURPOSE
FILL fill-in over missing data
SYNOPSIS
function c=fill(a, n)
DESCRIPTION
 FILL fill-in over missing data
   Y = FILL(X) replaces the missing data in X by extra/interpolating
   the non-missing elements. The non finite values (NaN or Inf) in X are
   considered as missing data.
   FILL uses an iterative process that converges toward the solution.
   Y = FILL(X,N) uses N iterations. By default, N = 100. If you
   estimate that FILL did not totally converge, increase N:
   Y = FILL(X,1000);
 input:  a: object or array (iData)
         n: number of iterations (integer)
 output: c: filled object (iData)
 ex:     a=iData([ ifitpath 'Data/Monitor_GV*']); b=hist(a); c=fill(b);
 Version: oct.. 23, 2018
 See also iData, accumarray, hist, histc, iData/plot, sum, iData/interp, iData/event, iData/squeeze, iData/pack
CROSS-REFERENCE INFORMATION
This function calls:
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
iData
isempty isempty(s) : true for empty iData object
isnan b = isnan(s) : True for NaN iData object elements
isscalar b = isscalar(s) : True for scalar iData objects
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
subsref b = subsref(a,s) : iData indexed references
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids