ifit.mccode.org - Description of findobj
Home > Objects > @iData > findobj.m
iFit/findobj
PURPOSE
[s,...]=findobj(s,...) : look for existing iData objects
SYNOPSIS
function [varargout] = findobj(s_in, varargin)
DESCRIPTION
 [s,...]=findobj(s,...) : look for existing iData objects
   @iData/findobj function to look for existing iData objects
   [caller, base] = findobj(iData) returns the names of all iData objects
     in base workspace and caller workspace into cells.
   [caller, base] = findobj(iData,'Property','Value')
   [caller, base] = findobj(s,'Property','Value')
     Returns the iData objects (in s or workspaces)
     that match the required properties.
 input:  s: object or array (iData)  (iData)
         PropertyName: name of Property to search (char)
         PropertyValue: value of PropertyName to search (char), in pairs with PropertyName
 output: caller: objects found in caller workspace (iData array)
         base:  objects found in base/MATLAB workspace (iData array)
 ex :    findobj(iData) or findobj(iData,'Title','MyTitle')
 Version: oct.. 23, 2018
 See also iData, iData/set, iData/get, iData/findstr, iData/findfield
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
get [...] = get(s, 'PropertyName', ...) : get iData object properties
isempty isempty(s) : true for empty iData object
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
strfind [match, field]=strfind(s, pattern, option) : search for pattern in iData
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
This function is called by:
plot h = plot(s, method, ...) : plot iData object
slice slice(s) : Plot a 2D/3D object with slice rendering