ifit.mccode.org - Description of findfield
Home > Objects > @iData > findfield.m
iFit/findfield
PURPOSE
[match, types, nelements]=findfield(iData, field, option) : look for iData fields
SYNOPSIS
function [match, types, dims] = findfield(s, field, option)
DESCRIPTION
 [match, types, nelements]=findfield(iData, field, option) : look for iData fields
   @iData/findfield function to look for iData fields, type and number of elements
   [match,type,n] = findfield(iData) returns the names of all iData fields
   [match,type,n] = findfield(iData, field) returns the names of all iData fields
     that match 'field'
   The optional 'option' argument can contain one or more keywords:
     The 'exact'   option will search for the exact occurences.
     The 'case'    option specifies a case sensitive search.
     The 'numeric' option will return only numerical fields.
     The 'char'    option will return only character fields.
     The 'cache'   option allows to re-use a previous field search cache for
                     faster consecutive searches on the same object.
     The 'first'   option returns the first match (with shortest name/link).
     The 'biggest' option returns the biggest match (has max nb of elements).
   The cache mechanism allows to do iterative searches on the same object, e.g.
     findfield(s,'Title') and then findfield(s,'Signal','cache numeric')
 input:  s: object or array (iData)
         field: field name to search, or '' (char).
         option: empty or 'exact' 'case' 'char' or 'numeric' (char)
 output: match:  names of iData fields (cellstr)
         types:  types of iData fields (cellstr), e.g. 'double', 'char', 'struct'...
         nelements: total number of elements in iData fields (double)
 ex:     findfield(iData) or findfield(iData,'Title') or findfield(s,'Title','exact case')
 Version: oct.. 23, 2018
 See also iData, iData/set, iData/get, iData/findobj, iData/findstr
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
isempty isempty(s) : true for empty iData object
isnumeric b = isnumeric(s) : True for numeric iData object elements
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
strfind [match, field]=strfind(s, pattern, option) : search for pattern in iData
transpose b = transpose(s) : non-conjugate transpose of iData object
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
This function is called by:
fileattrib [attribute, link] = fileattrib(s, field) : return a field Attribute
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
findstr [match, field]=findstr(s, str, option) : look for strings stored in iData
fits [pars,criteria,message,output] = fits(a, model, pars, options, constraints, ...) : fit data set on a model
help c = help(s) : display iData information as a Dialogue window
pack b = pack(a) : compress iData storage to save memory
plot h = plot(s, method, ...) : plot iData object