ifit.mccode.org - Description of find
Home > Objects > @iData > find.m
iFit/find
PURPOSE
d = find(s) : find iData signal non zeros values
SYNOPSIS
function a=find(a)
DESCRIPTION
 d = find(s) : find iData signal non zeros values
   @iData/find function to find iData non zeros values
 input:  s: object or array (iData)
 output: v: value of the iData Signal (logical)
 ex:     'find(iData(rand(10)))'
 Version: oct.. 23, 2018
 See also  iData/find, iData
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
get [...] = get(s, 'PropertyName', ...) : get iData object properties
size size(s) : get iData object size (number of elements)
This function is called by:
clim b = clim(s,[ cmin cmax ]) : Reduce iData C axis limits
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
corrcoef c = corrcoef(a,b) : correlation coefficient with an iData object
find d = find(s) : find iData signal non zeros values
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
findobj [s,...]=findobj(s,...) : look for existing iData objects
findstr [match, field]=findstr(s, str, option) : look for strings stored in iData
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
isvector b = isvector(s) : True for vector iData object
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
label b = label(s, alias, label) : Change iData label for a given alias/axis
load d = load(s, file, loader, ...): iData file loader
ndims d = ndims(s) : get the dimensionality of iData object
pack b = pack(a) : compress iData storage to save memory
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
permute c = permute(a, order) : Permute object dimensions from iData objects/arrays
plot h = plot(s, method, ...) : plot iData object
rmaxis s = rmaxis(s, Axis) : delete iData axes
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsindex d = subsindex(s) : subscript index for iData objects
subsref b = subsref(a,s) : iData indexed references
xlim b = xlim(s,[ xmin xmax ]) : Reduce iData X axis limits
ylim b = ylim(s,[ ymin ymax ]) : Reduce iData Y axis limits
zlim b = zlim(s,[ zmin zmax ]) : Reduce iData Z axis limits