ifit.mccode.org - Description of getaxis
Home > Objects > @iData > getaxis.m
iFit/getaxis
PURPOSE
[val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
SYNOPSIS
function [val, lab] = getaxis(s,ax)
DESCRIPTION
 [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
 [val, lab] = getaxis(s, 'AxisName|AxisIndex'): get iData axis definition and label
   @iData/getaxis function to get iData axis value, definition and alias.
   An axis is an alias associated with an index/rank.
   when the axis input parameter is given as an index (integer),
     the value of the axis is returned.
   when the axis input parameter is given as a string/name (e.g. '1' or 'x')
     the corresponding axis definition is returned.
   The Signal/Monitor corresponds to axis rank 0, and can also be accessed with
     getaxis(a, 'Signal') and a{0}.
   The Error/Monitor can also be accessed with getaxis(a, 'Error').
   Axis 1 is often labelled as 'y' (rows, vertical), 2 as 'x' (columns, horizontal).
   The special syntax s{0} gets the signal/monitor only (same as double(s)),
     and s{n} gets the axis of rank n.
 input:  s: object or array (iData)
         AxisIndex: axis index to inquire in object,
           or [] to obtain all axis values
           or '' to obtain all axis definitions (integer).
         AxisName: axis name to inquire in object, or '' (char). The name may
                   also be specified as 'n' where n is the axis index, e.g. '1'
 output: val: axis value, or corresponding axis name  (double/char)
         lab: axis label (char)
 ex:     getaxis(iData,1), getaxis(iData,'1'), getaxis(s, 'y')
 Version: oct.. 23, 2018
 See also iData, iData/set, iData/get, iData/getalias
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
double d = double(s) : convert iData into doubles
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
isempty isempty(s) : true for empty iData object
isfloat b = isfloat(s) : True for float iData object elements
isnan b = isnan(s) : True for NaN iData object elements
isnumeric b = isnumeric(s) : True for numeric iData object elements
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
ndims d = ndims(s) : get the dimensionality of iData object
not b = not(s) : computes the logical 'not' of iData object
ones s = ones(s,N,M,P,...) : initialize an iData array
prod s = prod(a,dim) : computes the product of iData objects elements
rdivide c = rdivide(a,b) : computes the ratio of iData objects
real b = real(s) : real value of iData object
reshape c = reshape(a) : reshape the object Signal
size size(s) : get iData object size (number of elements)
subsref b = subsref(a,s) : iData indexed references
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
circshift b=circshift(a, rank, shift): shifts the axis of specified rank by a value
clim b = clim(s,[ cmin cmax ]) : Reduce iData C axis limits
colon b = colon(s) : vector of arrays
conv c = conv(a,b) : computes the convolution of iData objects
convn c = convn(a,b) : computes the convolution of an iData object with a response function
corrcoef c = corrcoef(a,b) : correlation coefficient with an iData object
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
deconv c = deconv(a,b) : computes the deconvolution of iData objects
disp disp(s) : display iData object (details)
dog s= dog(dim,a) : split iData objects elements along dimension
double d = double(s) : convert iData into doubles
edit edit(s) : edit iData object Signal/Monitor
event c = event(a) : build an event list
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
gradient g = gradient(a, dim) : computes the gradient (derivative) of iData objects
help c = help(s) : display iData information as a Dialogue window
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
iData
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
imroi imroi: define a region of interest on a data set
interp [b...] = interp(s, ...) : interpolate iData object
intersect [ai,bi] = intersect(a, b) : computes object intersection area and values
isequal c = isequal(a,b) : full numerical equality comparison of iData objects
isfield b = isfield(s, field) : check existence of field/alias in iData objects
isvector b = isvector(s) : True for vector iData object
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
label b = label(s, alias, label) : Change iData label for a given alias/axis
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
mean b = mean(s, dim) : mean value of iData object
median b = median(s, dim) : median value of iData object
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
mtimes c = mtimes(a,b) : computes the matrix product of iData objects
ndims d = ndims(s) : get the dimensionality of iData object
pack b = pack(a) : compress iData storage to save memory
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
plot h = plot(s, method, ...) : plot iData object
reducevolume h = reducevolume(s, factor) : reduce an iData object size
reshape c = reshape(a) : reshape the object Signal
resize c = resize(a) : resize/rebin the object Signal
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
saveas f = saveas(s, filename, format, options) : save iData object into various data formats
setaxis s = setaxis(s, rank, alias, value) : set iData axes
slice slice(s) : Plot a 2D/3D object with slice rendering
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
std [half_width, center] = std(s, dim) : standard deviation of iData
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references
union [ai,bi] = union(a, b) : computes object union area and values
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
xlim b = xlim(s,[ xmin xmax ]) : Reduce iData X axis limits
ylim b = ylim(s,[ ymin ymax ]) : Reduce iData Y axis limits
zlim b = zlim(s,[ zmin zmax ]) : Reduce iData Z axis limits