ifit.mccode.org - Description of getframe
Home > Objects > @iData > getframe.m
iFit/getframe
PURPOSE
frame = getframe(s, dim, options) : create an iData object thumbnail/frame matrix
SYNOPSIS
function frame = getframe(a, dim, options)
DESCRIPTION
 frame = getframe(s, dim, options) : create an iData object thumbnail/frame matrix
   @iData/getframe function to create iData frames/thumbnails.
   Such thumbnails may be used to create icons on GUIs
   Note: a figure will flicker on screen.
 input:  s:   object or array (iData)
         dim: dimension of the thumbnail. When specified, the frame has no labels, ticks, ...
              to serve as a thumbnail
         options: specific plot options, default is 'axis tight'
 output: frame: frame/thumbnail
 ex:     f=getframe(a); image(f.cdata);
 Version: oct.. 23, 2018
 See also iData, iData/plot, getframe, image, imwrite
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getframe frame = getframe(s, dim, options) : create an iData object thumbnail/frame matrix
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
ndims d = ndims(s) : get the dimensionality of iData object
plot h = plot(s, method, ...) : plot iData object
round b = round(s) : upper integer round of iData object
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
size size(s) : get iData object size (number of elements)
subsref b = subsref(a,s) : iData indexed references
title b = title(s,label) : Change iData Signal label
xlabel b = xlabel(s,label) : Change iData X axis label
ylabel b = ylabel(s,label) : Change iData Y axis label
This function is called by:
getframe frame = getframe(s, dim, options) : create an iData object thumbnail/frame matrix
saveas f = saveas(s, filename, format, options) : save iData object into various data formats