ifit.mccode.org - Description of gradient
Home > Objects > @iData > gradient.m
iFit/gradient
PURPOSE
g = gradient(a, dim) : computes the gradient (derivative) of iData objects
SYNOPSIS
function b = gradient(a, dim)
DESCRIPTION
 g = gradient(a, dim) : computes the gradient (derivative) of iData objects
   @iData/gradient function to compute the gradient (derivative) of data sets.
     the returned value is an iData array of the partials for dimension
     ranks 1,2,3..., that is g=[gy gx gz ...] (remember X is rank 2, Y is 1).
     When the dimension is specified, only that rank partial derivative is returned.
 input:  a: object or array (iData)
       dim: dimension/rank of the partial to compute (int)
 output: g: object or cell array (iData)
 ex:     a=iData(peaks);
         g=gradient(a); subplot([ a g(1) g(2) ]);
 Version: oct.. 23, 2018
 See also iData, iData/diff, iData/del2, diff, gradient, iData/jacobian
CROSS-REFERENCE INFORMATION
This function calls:
abs b = abs(s) : absolute value of iData object
cell [content,fields]=cell(s) : convert iData objects into cells
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
ge c = ge(a,b) : greater-than-or-equal comparison of iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
gradient g = gradient(a, dim) : computes the gradient (derivative) of iData objects
interp [b...] = interp(s, ...) : interpolate iData object
ndims d = ndims(s) : get the dimensionality of iData object
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
size size(s) : get iData object size (number of elements)
This function is called by:
diff b = diff(s) : computes the difference long 1st axis of iData object
gradient g = gradient(a, dim) : computes the gradient (derivative) of iData objects
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects