ifit.mccode.org - Description of help
Home > Objects > @iData > help.m
iFit/help
PURPOSE
c = help(s) : display iData information as a Dialogue window
SYNOPSIS
function c = help(s)
DESCRIPTION
 c = help(s) : display iData information as a Dialogue window
   @iData/help: display information about the data set as a Dialogue
 input:  s: object or array (iData)
 output: c: iData identification (structure)
 Version: oct.. 23, 2018
 See also  iData/cell, iData/double, iData/struct,
           iData/char, iData/size, iData/get
CROSS-REFERENCE INFORMATION
This function calls:
char c = char(s) : convert iData into character
commandhistory commandhistory(s) : show the command history of iData object
disp disp(s) : display iData object (details)
end b = end(s,index,n) : end value for iData objects
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
full b = full(s) : Convert iData object storage to full matrix
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
isempty isempty(s) : true for empty iData object
isfield b = isfield(s, field) : check existence of field/alias in iData objects
isnumeric b = isnumeric(s) : True for numeric iData object elements
isvector b = isvector(s) : True for vector iData object
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
mean b = mean(s, dim) : mean value of iData object
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
ndims d = ndims(s) : get the dimensionality of iData object
not b = not(s) : computes the logical 'not' of iData object
prod s = prod(a,dim) : computes the product of iData objects elements
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
size size(s) : get iData object size (number of elements)
std [half_width, center] = std(s, dim) : standard deviation of iData
sum s = sum(a,dim) : computes the sum of iData objects elements
title b = title(s,label) : Change iData Signal label
transpose b = transpose(s) : non-conjugate transpose of iData object
xlabel b = xlabel(s,label) : Change iData X axis label
ylabel b = ylabel(s,label) : Change iData Y axis label
zlabel b = zlabel(s,label) : Change iData Z axis label
This function is called by: