ifit.mccode.org - Description of image
Home > Objects > @iData > image.m
iFit/image
PURPOSE
h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
SYNOPSIS
function h = image(r, g, b, option)
DESCRIPTION
 h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
   @iData/image function to plot up to 3 data sets on the RBG channels of an image
     the 3 objects should be 2D objects. Each object is re-scaled within 0 and 1
     interval, so that each color channel is fully used. However, the 'norm'
     keyword in options will scale the color channels within the global min and
     max Signal values, allowing to compare the relative intensity of the objects.
 input:  r: 2D object on the Red channel (iData or empty)
         g: 2D object on the Green channel (iData or empty)
         b: 2D object on the Blue channel (iData or empty)
         option: global option for 2D and 3D plots:
                 flat, interp, faceted (for shading)
                 transparent, light, clabel
                 axis tight, axis auto, view2, view3, hide_axes
                 painters (bitmap drawing), zbuffer (vectorial drawing)
                 norm (will use the same color-scale)
 output: h: graphics object handle
 ex:     image(iData(peaks),[],[], 'hide axes');
 Version: oct.. 23, 2018
 See also iData, iData/plot
CROSS-REFERENCE INFORMATION
This function calls:
double d = double(s) : convert iData into doubles
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
interp [b...] = interp(s, ...) : interpolate iData object
isempty isempty(s) : true for empty iData object
isfinite b = isfinite(s) : True for finite iData object elements
isinf b = isinf(s) : True for infinite iData object elements
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
ndims d = ndims(s) : get the dimensionality of iData object
plot h = plot(s, method, ...) : plot iData object
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
strfind [match, field]=strfind(s, pattern, option) : search for pattern in iData
union [ai,bi] = union(a, b) : computes object union area and values
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by: