ifit.mccode.org - Description of interp
Home > Objects > @iData > interp.m
iFit/interp
PURPOSE
[b...] = interp(s, ...) : interpolate iData object
SYNOPSIS
function b = interp(a, varargin)
DESCRIPTION
 [b...] = interp(s, ...) : interpolate iData object
   @iData/interp function to interpolate data sets.
   The multidimensional interpolation is based on a Delauney tessellation
     using the Computational Geometry Algorithms Library, CGAL.
   This function computes the values of the object 's' interpolated
   on a new axis grid, which may be specified from an other object, as independent axes,
   or as a rebinning of the original axes.
     b=interp(s)    rebin/check 's' on a regular grid.
     b=interp(s, d) where 'd' is an iData object computes 's' on the 'd' axes.
     b=interp(s, X1,X2, ... Xn) where 'Xn' are vectors or matrices as obtained
                    from ndgrid computes 's' on these axes.
     b=interp(s, {X1,X2, ... Xn}) is similar to the previous syntax
     b=interp(s, ..., ntimes) where 'ntimes' is an integer computes new axes for
                    interpolation by sub-dividing the original axes ntimes.
                    we also recommend the 'resize' method (much faster).
     b=interp(s, ..., 'method') uses specified method for interpolation as one of
                    linear (default), spline, cubic, or nearest
     b=interp(s, ..., 'grid') uses meshgrid/ndgrid to determine new axes as arrays
   Extrapolated data is set to NaN for the Signal, Error and Monitor. Also, in some
     cases, the triangulation interpolant creates fake 'flat' area, especially
     when the axes area is concave. We then recommend you try the 'hist' method.
   For Event data sets, we recommend to use the 'hist' method which is much faster.
 input:  s: object or array (iData)
         d: single object from which interpolation axes are extracted (iData)
            or a cell containing axes d={X1,X2, ... Xn}               (cell)
         X1...Xn: scalar, vectors or matrices specifying axis for
            dimensions 1 to ndims(s) (double scalar/vector/matrix)
         ntimes: original axis sub-division (integer)
 output: b: object or array (iData)
 ex:     a=iData(peaks); b=interp(a, 'grid'); c=interp(a, 2);
 Version: oct.. 23, 2018
 See also iData, interp1, interpn, ndgrid, iData/setaxis, iData/getaxis,
          iData/hist, iData/resize, iData/reshape
CROSS-REFERENCE INFORMATION
This function calls:
abs b = abs(s) : absolute value of iData object
cell [content,fields]=cell(s) : convert iData objects into cells
copyobj b = copyobj(s) : makes a copy of iData object
diff b = diff(s) : computes the difference long 1st axis of iData object
double d = double(s) : convert iData into doubles
end b = end(s,index,n) : end value for iData objects
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
iData
interp [b...] = interp(s, ...) : interpolate iData object
isempty isempty(s) : true for empty iData object
isequal c = isequal(a,b) : full numerical equality comparison of iData objects
isnan b = isnan(s) : True for NaN iData object elements
isnumeric b = isnumeric(s) : True for numeric iData object elements
isscalar b = isscalar(s) : True for scalar iData objects
isvector b = isvector(s) : True for vector iData object
ndims d = ndims(s) : get the dimensionality of iData object
ones s = ones(s,N,M,P,...) : initialize an iData array
prod s = prod(a,dim) : computes the product of iData objects elements
reshape c = reshape(a) : reshape the object Signal
rmaxis s = rmaxis(s, Axis) : delete iData axes
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
strfind [match, field]=strfind(s, pattern, option) : search for pattern in iData
subsref b = subsref(a,s) : iData indexed references
transpose b = transpose(s) : non-conjugate transpose of iData object
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
gradient g = gradient(a, dim) : computes the gradient (derivative) of iData objects
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
interp [b...] = interp(s, ...) : interpolate iData object
intersect [ai,bi] = intersect(a, b) : computes object intersection area and values
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
plot h = plot(s, method, ...) : plot iData object
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
union [ai,bi] = union(a, b) : computes object union area and values