ifit.mccode.org - Description of isfield
Home > Objects > @iData > isfield.m
iFit/isfield
PURPOSE
b = isfield(s, field) : check existence of field/alias in iData objects
SYNOPSIS
function b = isfield(a, field)
DESCRIPTION
 b = isfield(s, field) : check existence of field/alias in iData objects
   @iData/isfield function which checks if a name is already defined as a Property
       or Alias or unique definition in the iData object.
     isfield(s) returns the full list of defined fields and aliases in the
     object.
   isfield scope (Properties and Aliases) is more restricted than findfield and
     strfind methods.
 input:  s: object or array (iData)
         field: name to check for (string)
 output: b: true when the name is already defined, false otherwise
 ex:     b=isfield(a, 'history');
 Version: oct.. 23, 2018
 See also iData, isfield, iData/findfield, iData/strfind
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
end b = end(s,index,n) : end value for iData objects
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
isempty isempty(s) : true for empty iData object
size size(s) : get iData object size (number of elements)
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
commandhistory commandhistory(s) : show the command history of iData object
edit edit(s) : edit iData object Signal/Monitor
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
fits [pars,criteria,message,output] = fits(a, model, pars, options, constraints, ...) : fit data set on a model
help c = help(s) : display iData information as a Dialogue window
iData
imroi imroi: define a region of interest on a data set
load d = load(s, file, loader, ...): iData file loader
plot h = plot(s, method, ...) : plot iData object
saveas f = saveas(s, filename, format, options) : save iData object into various data formats
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references