ifit.mccode.org - Description of isfinite
Home > Objects > @iData > isfinite.m
iFit/isfinite
PURPOSE
b = isfinite(s) : True for finite iData object elements
SYNOPSIS
function a = isfinite(a)
DESCRIPTION
 b = isfinite(s) : True for finite iData object elements
   @iData/isfinite function to return true for finite elements
   of 's', i.e. that are not NaN, Inf or -Inf.
   To remove nan's and inf's values use: fill(s)
 input:  s: object or array (iData)
 output: b: array (int)
 ex:     b=isfinite(a);
 Version: oct.. 23, 2018
 See also iData, iData/sign, iData/isreal, iData/isfinite, iData/isnan,
          iData/isinf, iData/isfloat, iData/isinterger,
          iData/isnumeric, iData/islogical, iData/isscalar,
          iData/isvector, iData/issparse, iData/fill
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
corrcoef c = corrcoef(a,b) : correlation coefficient with an iData object
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object