ifit.mccode.org - Description of isnan
Home > Objects > @iData > isnan.m
iFit/isnan
PURPOSE
b = isnan(s) : True for NaN iData object elements
SYNOPSIS
function a = isnan(a)
DESCRIPTION
 b = isnan(s) : True for NaN iData object elements
   @iData/isnan function to return true for NaN elements
   of 's', i.e. that are NaN ('not a number')
   To remove nan's and inf's values use: fill(s)
 input:  s: object or array (iData)
 output: b: object or array (iData)
 ex:     b=isnan(a);
 Version: oct.. 23, 2018
 See also iData, iData/sign, iData/isreal, iData/isfinite, iData/isnan,
          iData/isinf, iData/isfloat, iData/isinterger,
          iData/isnumeric, iData/islogical, iData/isscalar,
          iData/isvector, iData/issparse, iData/fill
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
fill FILL fill-in over missing data
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
interp [b...] = interp(s, ...) : interpolate iData object
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
label b = label(s, alias, label) : Change iData label for a given alias/axis
plot h = plot(s, method, ...) : plot iData object
setaxis s = setaxis(s, rank, alias, value) : set iData axes
subsref b = subsref(a,s) : iData indexed references