ifit.mccode.org - Description of isnumeric
Home > Objects > @iData > isnumeric.m
iFit/isnumeric
PURPOSE
b = isnumeric(s) : True for numeric iData object elements
SYNOPSIS
function a = isnumeric(a)
DESCRIPTION
 b = isnumeric(s) : True for numeric iData object elements
   @iData/isnumeric function to return true for numeric elements
   of 's', i.e. that are of type double, single, integer.
 input:  s: object or array (iData)
 output: b: object or array (iData)
 ex:     b=isnumeric(a);
 Version: oct.. 23, 2018
 See also iData, iData/sign, iData/isreal, iData/isfinite, iData/isnan,
          iData/isinf, iData/isfloat, iData/isinterger,
          iData/isnumeric, iData/islogical, iData/isscalar,
          iData/isvector, iData/issparse
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
corrcoef c = corrcoef(a,b) : correlation coefficient with an iData object
disp disp(s) : display iData object (details)
event c = event(a) : build an event list
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
help c = help(s) : display iData information as a Dialogue window
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
iData
interp [b...] = interp(s, ...) : interpolate iData object
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
label b = label(s, alias, label) : Change iData label for a given alias/axis
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
logspace v = logspace(a,b,n) : creates a logarithmically spaced vector of objects
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
reducevolume h = reducevolume(s, factor) : reduce an iData object size
rmaxis s = rmaxis(s, Axis) : delete iData axes
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
subplot h = subplot(s) : plot iData array as subplots
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references