ifit.mccode.org - Description of isscalar
Home > Objects > @iData > isscalar.m
iFit/isscalar
PURPOSE
b = isscalar(s) : True for scalar iData objects
SYNOPSIS
function a = isscalar(a)
DESCRIPTION
 b = isscalar(s) : True for scalar iData objects
   @iData/isscalar function to return true if data set is a single scalar element
   of 's', i.e. that size is 1x1
 input:  s: object or array (iData)
 output: b: object or array (iData)
 ex:     b=isscalar(a);
 Version: oct.. 23, 2018
 See also iData, iData/sign, iData/isreal, iData/isfinite, iData/isnan,
          iData/isinf, iData/isfloat, iData/isinterger,
          iData/isnumeric, iData/islogical, iData/isscalar,
          iData/isvector, iData/issparse
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
conv c = conv(a,b) : computes the convolution of iData objects
convn c = convn(a,b) : computes the convolution of an iData object with a response function
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
deconv c = deconv(a,b) : computes the deconvolution of iData objects
edit edit(s) : edit iData object Signal/Monitor
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
fill FILL fill-in over missing data
get [...] = get(s, 'PropertyName', ...) : get iData object properties
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
interp [b...] = interp(s, ...) : interpolate iData object
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
label b = label(s, alias, label) : Change iData label for a given alias/axis
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
logspace v = logspace(a,b,n) : creates a logarithmically spaced vector of objects
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
mtimes c = mtimes(a,b) : computes the matrix product of iData objects
pca [b] = pca(X, k) : Principal component analysis of iData object(s)
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references