ifit.mccode.org - Description of isvector
Home > Objects > @iData > isvector.m
iFit/isvector
PURPOSE
b = isvector(s) : True for vector iData object
SYNOPSIS
function v = isvector(s)
DESCRIPTION
 b = isvector(s) : True for vector iData object
   @iData/isvector function to return true if data set is a vector
   i.e. that its size is 1xN or Nx1.
   Additionally, if the vector data set has X axes defined, it returns X, for
   instance with event data sets.
 input:  s: object or array (iData)
 output: b: object or array (iData)
 ex:     b=isvector(a);
 Version: oct.. 23, 2018
 See also iData, iData/sign, iData/isreal, iData/isfinite, iData/isnan,
          iData/isinf, iData/isfloat, iData/isinterger,
          iData/isnumeric, iData/islogical, iData/isscalar,
          iData/isvector, iData/issparse
CROSS-REFERENCE INFORMATION
This function calls:
double d = double(s) : convert iData into doubles
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
isvector b = isvector(s) : True for vector iData object
size size(s) : get iData object size (number of elements)
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
caxis c = caxis(s, h) : Use the 2D/3D data as the colormap (CData property) in current object.
combine c = combine(a,b) : combines iData objects
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
disp disp(s) : display iData object (details)
display d = display(s) : display iData object (from command line)
edit edit(s) : edit iData object Signal/Monitor
help c = help(s) : display iData information as a Dialogue window
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
iData
interp [b...] = interp(s, ...) : interpolate iData object
isvector b = isvector(s) : True for vector iData object
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
permute c = permute(a, order) : Permute object dimensions from iData objects/arrays
plot h = plot(s, method, ...) : plot iData object
reducevolume h = reducevolume(s, factor) : reduce an iData object size
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
setaxis s = setaxis(s, rank, alias, value) : set iData axes
slice slice(s) : Plot a 2D/3D object with slice rendering
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
std [half_width, center] = std(s, dim) : standard deviation of iData
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references
xlabel b = xlabel(s,label) : Change iData X axis label
ylabel b = ylabel(s,label) : Change iData Y axis label