ifit.mccode.org - Description of kmeans
Home > Objects > @iData > kmeans.m
iFit/kmeans
PURPOSE
[b,c] = kmeans(X, k) : k-means clustering of iData object
SYNOPSIS
function [s,c] = kmeans(a, k, method)
DESCRIPTION
 [b,c] = kmeans(X, k) : k-means clustering of iData object
   @iData/kmeans function to partition the object X into k classes.
   b = kmeans(X,k) partitions the Signal in the iData object X into k clusters.
     The resulting object Signal contains numbers from 1 to 'k' which are indices
     of segments/partitions.
     When no cluster can be found, the result is empty.
   b = kmeans(X)   assumes k=2 partitions
   [b,c] = kmeans(X,k) also returns the centroid of the clusters/partitions/segments.
   b = kmeans(X, k, 'otsu')
     uses the Otsu method, for 2D data sets
   b = kmeans(X, k, 'kmeans++')
     uses the K-means++ method, for 2D data sets
 input:  X: object or array (iData)
         k: number of partitions wanted (integer, default is 2)
         method: '' for default, 'otsu' for Otsu method (only for 2D images).
 output: b: object or array with partition indices (iData)
         c: centroid locations of clusters
 ex:     a=iData(peaks); b=kmeans(a);
 See: https://en.wikipedia.org/wiki/K-means_clustering
 See: https://en.wikipedia.org/wiki/K-means%2B%2B
 See: https://en.wikipedia.org/wiki/Otsu%27s_method
 References:
   Otsu N., A threshold selection method from gray-level histogram, IEEE Trans. Syst. Man Cybern. 9:62-66;1979
   [1] J. B. MacQueen, "Some Methods for Classification and Analysis of
       MultiVariate Observations", in Proc. of the fifth Berkeley
       Symposium on Mathematical Statistics and Probability, L. M. L. Cam
       and J. Neyman, eds., vol. 1, UC Press, 1967, pp. 281-297.
   [2] D. Arthur and S. Vassilvitskii, "k-means++: The Advantages of
       Careful Seeding", Technical Report 2006-13, Stanford InfoLab, 2006.
 Version: oct.. 23, 2018
 See also iData, iData/uminus, iData/abs, iData/real, iData/imag, iData/uplus
CROSS-REFERENCE INFORMATION
This function calls:
abs b = abs(s) : absolute value of iData object
cell [content,fields]=cell(s) : convert iData objects into cells
copyobj b = copyobj(s) : makes a copy of iData object
cumsum s = cumsum(a,dim) : computes the cumulative sum of iData objects elements
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
fliplr b = fliplr(s) : Flip object in left/right direction
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
iData
ind2sub ind2sub(s,index) : get indexed element in an iData array
isempty isempty(s) : true for empty iData object
isfinite b = isfinite(s) : True for finite iData object elements
isfloat b = isfloat(s) : True for float iData object elements
isnan b = isnan(s) : True for NaN iData object elements
label b = label(s, alias, label) : Change iData label for a given alias/axis
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
minus c = minus(a,b) : computes the difference of iData objects
ndims d = ndims(s) : get the dimensionality of iData object
ones s = ones(s,N,M,P,...) : initialize an iData array
real b = real(s) : real value of iData object
reshape c = reshape(a) : reshape the object Signal
round b = round(s) : upper integer round of iData object
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
single d = single(s) : convert iData into single floats
size size(s) : get iData object size (number of elements)
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
sqrt b = sqrt(s) : square root value of iData object
std [half_width, center] = std(s, dim) : standard deviation of iData
subsref b = subsref(a,s) : iData indexed references
sum s = sum(a,dim) : computes the sum of iData objects elements
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by: