ifit.mccode.org - Description of label
Home > Objects > @iData > label.m
iFit/label
PURPOSE
b = label(s, alias, label) : Change iData label for a given alias/axis
SYNOPSIS
function labl = label(this, varargin)
DESCRIPTION
 b = label(s, alias, label) : Change iData label for a given alias/axis
   @iData/label function to set/get labels
     label(s, alias) returns the current label
     label(s)        returns the object Label
     label(s, rank, label)   sets the object label
   The input iData object is updated if no output argument is specified.
 input:  s: object or array (iData)
         alias: name of the alias or index of the axis (char/numeric)
         label: new label (char/cellstr)
 output: b: object or array (iData)
 ex:     b=label(a,'x','new xlabel'); b=label(a,'x'); b=label(a, 1,'new xlabel');
 Version: oct.. 23, 2018
 See also iData, iData/plot, iData/xlabel, iData/ylabel, iData/zlabel, iDala/clabel
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
isempty isempty(s) : true for empty iData object
isnan b = isnan(s) : True for NaN iData object elements
isnumeric b = isnumeric(s) : True for numeric iData object elements
isscalar b = isscalar(s) : True for scalar iData objects
label b = label(s, alias, label) : Change iData label for a given alias/axis
ndims d = ndims(s) : get the dimensionality of iData object
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
clabel b = clabel(s,label) : Change iData C axis label
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
disp disp(s) : display iData object (details)
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
iData
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
label b = label(s, alias, label) : Change iData label for a given alias/axis
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
mean b = mean(s, dim) : mean value of iData object
median b = median(s, dim) : median value of iData object
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
plot h = plot(s, method, ...) : plot iData object
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
title b = title(s,label) : Change iData Signal label
xlabel b = xlabel(s,label) : Change iData X axis label
ylabel b = ylabel(s,label) : Change iData Y axis label
zlabel b = zlabel(s,label) : Change iData Z axis label