ifit.mccode.org - Description of meshgrid
Home > Objects > @iData > meshgrid.m
iFit/meshgrid
PURPOSE
s = meshgrid(a) : transforms an iData object so that its axes are grids
SYNOPSIS
function b = meshgrid(a, varargin)
DESCRIPTION
 s = meshgrid(a) : transforms an iData object so that its axes are grids
   @iData/meshgrid function to transform iData object axes so that they are
     on a regular grid, as obtained from ndgrid. When the initial axes are not
     perpendicular/regular, the object Signal is interpolated on the new grid.
   meshgrid(a, 'vector' ...) forces all axes as vectors
   meshgrid(a, 'grid' ...)   forces all axes as grid with same size as Signal
   meshgrid(a, dims, ...)    specifies the size of the histogram
   meshgrid(a, 'fill' ...)   fills empty histogram bins (e.g. when converting from an event list)
   meshgrid(a, 'method' ...) uses specified method for interpolation as one of
                    linear (default), spline, cubic, or nearest
   A meshgrid histogram can be converted back into an event list with the 'event' method.
 input:  a: object or array (iData)
         method: 'linear','cubic','spline','nearest'
                 'vector' to get only vector axes
                 'fill'   to replace NaN's in the final data set
 output: s: object (iData)
 ex:     c=meshgrid(a); c=meshgrid(a, 'vector linear')
         c=meshgrid(a, 100, 'fill')
 Version: oct.. 23, 2018
 See also iData, iData/interp, iData/hist, iData/event, iData/fill
CROSS-REFERENCE INFORMATION
This function calls:
ceil b = ceil(s) : upper integer round of iData object
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
fill FILL fill-in over missing data
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
iData
interp [b...] = interp(s, ...) : interpolate iData object
isempty isempty(s) : true for empty iData object
isnumeric b = isnumeric(s) : True for numeric iData object elements
isscalar b = isscalar(s) : True for scalar iData objects
isvector b = isvector(s) : True for vector iData object
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
ndims d = ndims(s) : get the dimensionality of iData object
ones s = ones(s,N,M,P,...) : initialize an iData array
prod s = prod(a,dim) : computes the product of iData objects elements
reshape c = reshape(a) : reshape the object Signal
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
strfind [match, field]=strfind(s, pattern, option) : search for pattern in iData
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
corrcoef c = corrcoef(a,b) : correlation coefficient with an iData object
event c = event(a) : build an event list
imroi imroi: define a region of interest on a data set
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
std [half_width, center] = std(s, dim) : standard deviation of iData