ifit.mccode.org - Description of mtimes
Home > Objects > @iData > mtimes.m
iFit/mtimes
PURPOSE
c = mtimes(a,b) : computes the matrix product of iData objects
SYNOPSIS
function c = mtimes(a,b)
DESCRIPTION
 c = mtimes(a,b) : computes the matrix product of iData objects
   @iData/mtimes function to compute the matrix product of data sets=a*b
      the number of columns of a must equal the number of rows of b.
CROSS-REFERENCE INFORMATION
This function calls:
copyobj b = copyobj(s) : makes a copy of iData object
double d = double(s) : convert iData into doubles
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
isscalar b = isscalar(s) : True for scalar iData objects
ndims d = ndims(s) : get the dimensionality of iData object
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
size size(s) : get iData object size (number of elements)
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by: