ifit.mccode.org - Description of ndims
Home > Objects > @iData > ndims.m
iFit/ndims
PURPOSE
d = ndims(s) : get the dimensionality of iData object
SYNOPSIS
function v=ndims(s)
DESCRIPTION
 d = ndims(s) : get the dimensionality of iData object
   @iData/ndims function to get the number of dimensions of the iData signal.
 input:  s: object or array (iData)
 output: dimensionality of Signal in the object (double array)
 ex :    ndims(iData)
 Version: oct.. 23, 2018
 See also  iData/size
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
ndims d = ndims(s) : get the dimensionality of iData object
size size(s) : get iData object size (number of elements)
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
caxis c = caxis(s, h) : Use the 2D/3D data as the colormap (CData property) in current object.
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
conv c = conv(a,b) : computes the convolution of iData objects
convn c = convn(a,b) : computes the convolution of an iData object with a response function
corrcoef c = corrcoef(a,b) : correlation coefficient with an iData object
ctranspose b = ctranspose(s) : complex conjugate transpose of iData object
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
deconv c = deconv(a,b) : computes the deconvolution of iData objects
disp disp(s) : display iData object (details)
display d = display(s) : display iData object (from command line)
dog s= dog(dim,a) : split iData objects elements along dimension
edit edit(s) : edit iData object Signal/Monitor
end b = end(s,index,n) : end value for iData objects
event c = event(a) : build an event list
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
getframe frame = getframe(s, dim, options) : create an iData object thumbnail/frame matrix
gradient g = gradient(a, dim) : computes the gradient (derivative) of iData objects
help c = help(s) : display iData information as a Dialogue window
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
iData
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
imroi imroi: define a region of interest on a data set
interp [b...] = interp(s, ...) : interpolate iData object
intersect [ai,bi] = intersect(a, b) : computes object intersection area and values
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
label b = label(s, alias, label) : Change iData label for a given alias/axis
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
mean b = mean(s, dim) : mean value of iData object
median b = median(s, dim) : median value of iData object
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
mtimes c = mtimes(a,b) : computes the matrix product of iData objects
ndims d = ndims(s) : get the dimensionality of iData object
pack b = pack(a) : compress iData storage to save memory
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
permute c = permute(a, order) : Permute object dimensions from iData objects/arrays
plot h = plot(s, method, ...) : plot iData object
reducevolume h = reducevolume(s, factor) : reduce an iData object size
resize c = resize(a) : resize/rebin the object Signal
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
saveas f = saveas(s, filename, format, options) : save iData object into various data formats
scatter h = scatter(s,option) : Plot a 2D/3D object as separate colored points
setaxis s = setaxis(s, rank, alias, value) : set iData axes
slice slice(s) : Plot a 2D/3D object with slice rendering
smooth Z = smooth(Y) : smooth iData objects
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
std [half_width, center] = std(s, dim) : standard deviation of iData
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references
transpose b = transpose(s) : non-conjugate transpose of iData object
union [ai,bi] = union(a, b) : computes object union area and values
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
xlim b = xlim(s,[ xmin xmax ]) : Reduce iData X axis limits
ylim b = ylim(s,[ ymin ymax ]) : Reduce iData Y axis limits