ifit.mccode.org - Description of not
Home > Objects > @iData > not.m
iFit/not
PURPOSE
b = not(s) : computes the logical 'not' of iData object
SYNOPSIS
function a = not(a)
DESCRIPTION
 b = not(s) : computes the logical 'not' of iData object
   @iData/not function to compute the logical 'not' of data sets,
     i.e. returns 0 where iData Signal is not zero, and 1 otherwise.
 input:  s: object or array (iData)
 output: b: object or array (iData)
 ex:     b=not(a);
 Version: oct.. 23, 2018
 See also iData, iData/or, iData/and
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
disp disp(s) : display iData object (details)
edit edit(s) : edit iData object Signal/Monitor
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
help c = help(s) : display iData information as a Dialogue window
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
setaxis s = setaxis(s, rank, alias, value) : set iData axes
subsref b = subsref(a,s) : iData indexed references