ifit.mccode.org - Description of ones
Home > Objects > @iData > ones.m
iFit/ones
PURPOSE
s = ones(s,N,M,P,...) : initialize an iData array
SYNOPSIS
function s = ones(iData_in,varargin)
DESCRIPTION
 s = ones(s,N,M,P,...) : initialize an iData array
   @iData/ones function to create an array of 's' iData objects
   The object 's' is duplicated into an array. Use s=iData to get an empty array.
 input:  s: object or array (iData)
 output: b: object or array (iData)
 ex: ones(iData,5,5) will create a 5-by-5 empty iData array
     ones(s,5,5) will return a 5-by-5 array filled with 's'
 Version: oct.. 23, 2018
 See also iData
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
size size(s) : get iData object size (number of elements)
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
caxis c = caxis(s, h) : Use the 2D/3D data as the colormap (CData property) in current object.
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
interp [b...] = interp(s, ...) : interpolate iData object
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
logspace v = logspace(a,b,n) : creates a logarithmically spaced vector of objects
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
reducevolume h = reducevolume(s, factor) : reduce an iData object size
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
subsasgn b = subsasgn(a,index,b) : iData indexed assignement