ifit.mccode.org - Description of pack
Home > Objects > @iData > pack.m
iFit/pack
PURPOSE
b = pack(a) : compress iData storage to save memory
SYNOPSIS
function b = pack(a)
DESCRIPTION
 b = pack(a) : compress iData storage to save memory
   @iData/pack function to save memory when storing data sets
   This includes to compare sparse/full storage for large matrices, and
   reduce the Command history. Only the Signal, aliases and Axes are kept
   so that unused Data items are removed.
   In addition, to further 'clean' an object, use: fill(a) and squeeze(a)
 input:  s: object or array (iData)
 output: f: compressed object or array (iData)
 ex:     b=pack(a);
 Version: oct.. 23, 2018
 See also iData, iData/sparse, iData/full, iData/saveas, iData/fill, iData/squeeze
CROSS-REFERENCE INFORMATION
This function calls:
cell [content,fields]=cell(s) : convert iData objects into cells
copyobj b = copyobj(s) : makes a copy of iData object
double d = double(s) : convert iData into doubles
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
full b = full(s) : Convert iData object storage to full matrix
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
isempty isempty(s) : true for empty iData object
issparse b = issparse(s) : True for sparse matrix iData object
ndims d = ndims(s) : get the dimensionality of iData object
pack b = pack(a) : compress iData storage to save memory
reshape c = reshape(a) : reshape the object Signal
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
sparse b = sparse(s) : Convert iData object storage to sparse
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
pack b = pack(a) : compress iData storage to save memory