ifit.mccode.org - Description of peaks
Home > Objects > @iData > peaks.m
iFit/peaks
PURPOSE
[half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
SYNOPSIS
function [sigma, position, amplitude, baseline] = peaks(a, dim, m)
DESCRIPTION
 [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
   @iData/peaks function to compute an estimate of peak position and width along
     dimension 'dim'
 input:  a: object or array (iData/array of)
         dim: dimension to use. Default is 1 (int)
         m: typical peak width or 0 for automatic guess (int)
 output: half_width: width of peaks (scalar/array)
         center:     center of peaks (scalar/array)
         amplitude:  amplitude of peaks (scalar/array)
         baseline:   baseline (background) (iData)
 ex:     c=peaks(a);
 References: Slavic, NIM 112 (1973) 253 ; M. Morhac, NIM A 600 (2009) 478
 Version: oct.. 23, 2018
 See also iData, iData/median, iData/mean, iData/std
CROSS-REFERENCE INFORMATION
This function calls:
abs b = abs(s) : absolute value of iData object
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
ceil b = ceil(s) : upper integer round of iData object
cell [content,fields]=cell(s) : convert iData objects into cells
circshift b=circshift(a, rank, shift): shifts the axis of specified rank by a value
copyobj b = copyobj(s) : makes a copy of iData object
diff b = diff(s) : computes the difference long 1st axis of iData object
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
interp [b...] = interp(s, ...) : interpolate iData object
isempty isempty(s) : true for empty iData object
isreal b = isreal(s) : True for real iData object elements
isvector b = isvector(s) : True for vector iData object
log b = log(s) : natural logarithm value of iData object
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
ndims d = ndims(s) : get the dimensionality of iData object
ones s = ones(s,N,M,P,...) : initialize an iData array
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
prod s = prod(a,dim) : computes the product of iData objects elements
reshape c = reshape(a) : reshape the object Signal
round b = round(s) : upper integer round of iData object
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
size size(s) : get iData object size (number of elements)
sqrt b = sqrt(s) : square root value of iData object
std [half_width, center] = std(s, dim) : standard deviation of iData
sum s = sum(a,dim) : computes the sum of iData objects elements
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData