ifit.mccode.org - Description of prod
Home > Objects > @iData > prod.m
iFit/prod
PURPOSE
s = prod(a,dim) : computes the product of iData objects elements
SYNOPSIS
function [s,sigma] = prod(a,dim)
DESCRIPTION
 s = prod(a,dim) : computes the product of iData objects elements
   @iData/prod function to compute the product of the elements of the data set
     prod(a,dim) operates along axis of rank dim. The axis is then removed.
       If dim=0, product is done on all axes and the total is returned as a scalar value.
         In this case, a second output argument holds the error bar.
       prod(a,1) operates on first dimension (columns)
 input:  a: object or array (iData/array of)
         dim: dimension to operate (int//array of)
 output: s: product of elements (iData/scalar)
 ex:     c=prod(a);
 Version: oct.. 23, 2018
 See also iData, iData/plus, iData/prod, iData/cumprod, iData/mean
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
This function is called by:
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
disp disp(s) : display iData object (details)
edit edit(s) : edit iData object Signal/Monitor
end b = end(s,index,n) : end value for iData objects
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
help c = help(s) : display iData information as a Dialogue window
interp [b...] = interp(s, ...) : interpolate iData object
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
plot h = plot(s, method, ...) : plot iData object
reducevolume h = reducevolume(s, factor) : reduce an iData object size
reshape c = reshape(a) : reshape the object Signal
setaxis s = setaxis(s, rank, alias, value) : set iData axes
slice slice(s) : Plot a 2D/3D object with slice rendering
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references