ifit.mccode.org - Description of reducevolume
Home > Objects > @iData > reducevolume.m
iFit/reducevolume
PURPOSE
h = reducevolume(s, factor) : reduce an iData object size
SYNOPSIS
function s = reducevolume(a, R)
DESCRIPTION
 h = reducevolume(s, factor) : reduce an iData object size
 B = REDUCEVOLUME(A, [Rx Ry Rz ... ]) reduces the number
    of elements in the object by only keeping every Rx element in the x
    direction, every Ry element in the y direction, and every Rz element
    in the z direction and so on.
 B = REDUCEVOLUME(A, R)
    If a scalar R is used to indicate the amount or
    reduction instead of a vector, the reduction is assumed to
    be R on all axes.
 B = REDUCEVOLUME(A)
    When omitted, the volume/size reduction is performed on bigger axes until
    the final object contains less than 1e6 elements.
 Version: oct.. 23, 2018
 See also iData, reducevolume,plot, iData/plot, iData/size
CROSS-REFERENCE INFORMATION
This function calls:
ceil b = ceil(s) : upper integer round of iData object
cell [content,fields]=cell(s) : convert iData objects into cells
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
isempty isempty(s) : true for empty iData object
isnumeric b = isnumeric(s) : True for numeric iData object elements
isvector b = isvector(s) : True for vector iData object
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
ndims d = ndims(s) : get the dimensionality of iData object
ones s = ones(s,N,M,P,...) : initialize an iData array
prod s = prod(a,dim) : computes the product of iData objects elements
reshape c = reshape(a) : reshape the object Signal
size size(s) : get iData object size (number of elements)
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
subsref b = subsref(a,s) : iData indexed references
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
plot h = plot(s, method, ...) : plot iData object
slice slice(s) : Plot a 2D/3D object with slice rendering