ifit.mccode.org - Description of rmalias
Home > Objects > @iData > rmalias.m
iFit/rmalias
PURPOSE
s = rmalias(s, AliasName) : removes iData aliases
SYNOPSIS
function this = rmalias(this,names)
DESCRIPTION
 s = rmalias(s, AliasName) : removes iData aliases
   @iData/rmalias function to remove iData aliases.
   The function works also when AliasName is given as a cell string.
   The command rmalias(iData,'Signal') resets the Signal to the biggest numerical field.
   The input iData object is updated if no output argument is specified.
   To automatically guess new Signal and Axes, use:
     s.Signal='';
 input:  s: object or array (iData)
         AliasName: Name of existing or new alias (char/cellstr)
 output: s: array (iData)
 ex:     rmalias(iData,'Temperature')
 Version: oct.. 23, 2018
 See also iData, iData/getalias, iData/get, iData/set, iData/setalias
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
isempty isempty(s) : true for empty iData object
rmalias s = rmalias(s, AliasName) : removes iData aliases
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
This function is called by:
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
rmalias s = rmalias(s, AliasName) : removes iData aliases