ifit.mccode.org - Description of rmaxis
Home > Objects > @iData > rmaxis.m
iFit/rmaxis
PURPOSE
s = rmaxis(s, Axis) : delete iData axes
SYNOPSIS
function this = rmaxis(this,rank)
DESCRIPTION
 s = rmaxis(s, Axis) : delete iData axes
   @iData/rmaxis function to delete iData axes.
     As Axes are often required for the Signal to be used,
     default axes will be automatically re-created when needed.
   The Axis can be specified as a rank (1-ndims) or an axis name.
   When the Axis is empty, all axes are removed.
   The input iData object is updated if no output argument is specified.
   Axis 1 is often labelled as 'y' (rows, vertical), 2 as 'x' (columns, horizontal).
 input:  s: object or array (iData)
         AxisIndex: rank or alias name of the axis
 output: s: array (iData)
 ex:     rmaxis(iData, 1) removes the 'x' axis (rank 1)
 Version: oct.. 23, 2018
 See also iData, iData/getaxis, iData/get, iData/set, iData/setaxis
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
isempty isempty(s) : true for empty iData object
isnumeric b = isnumeric(s) : True for numeric iData object elements
rmaxis s = rmaxis(s, Axis) : delete iData axes
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
interp [b...] = interp(s, ...) : interpolate iData object
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
mean b = mean(s, dim) : mean value of iData object
median b = median(s, dim) : median value of iData object
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
plot h = plot(s, method, ...) : plot iData object
rmaxis s = rmaxis(s, Axis) : delete iData axes