ifit.mccode.org - Description of setalias
Home > Objects > @iData > setalias.m
iFit/setalias
PURPOSE
[s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
SYNOPSIS
function this = setalias(this,names,links,labels)
DESCRIPTION
 [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
   @iData/setalias function to set iData aliases.
   The function works also when AliasName, AliasLink, and optional AliasLabel
     are given as cell strings. The AliasLink may be of any class, but char is
     interpreted as a link to search in the object or an external file, such
     as '#Data' 'Data' (local links), 'file://path' (full file structure)
     or 'file://path#Data' (a part of an external file).
   The special name 'this' may be used in the Alias link to refer the object itself.
   When the link is empty, the alias is removed, so that
     setalias(s, alias)       deletes an alias, similarly to rmalias
     setalias(s, getalias(s)) deletes all alias definitions.
   The command setalias(iData,'Signal') sets the Signal to the biggest numerical field.
   The input iData object is updated if no output argument is specified.
   An new field/alias may be defined with the quick syntax 's.alias = value'.
 input:  s: object or array (iData)
         AliasName: Name of existing or new alias (char/cellstr)
         AliasLink: definition of the alias, or '' to remove the alias (cell of char/double/...)
         AliasLabel: optional description/label of the alias (char/cellstr)
 output: s: array (iData)
 ex:     setalias(iData,'Temperature','Data.Temperature','This is the temperature')
         setalias(iData,'Temperature','this.Data.Temperature')
         setalias(iData,'Temperature',1:20)
         setalias(iData,'T_pi','[ this.Data.Temperature pi ]')
 Version: oct.. 23, 2018
 See also iData, iData/getalias, iData/get, iData/set, iData/rmalias
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
get [...] = get(s, 'PropertyName', ...) : get iData object properties
iData
isempty isempty(s) : true for empty iData object
isnumeric b = isnumeric(s) : True for numeric iData object elements
label b = label(s, alias, label) : Change iData label for a given alias/axis
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
event c = event(a) : build an event list
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
fill FILL fill-in over missing data
gradient g = gradient(a, dim) : computes the gradient (derivative) of iData objects
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
iData
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
imroi imroi: define a region of interest on a data set
interp [b...] = interp(s, ...) : interpolate iData object
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
load d = load(s, file, loader, ...): iData file loader
logspace v = logspace(a,b,n) : creates a logarithmically spaced vector of objects
mean b = mean(s, dim) : mean value of iData object
median b = median(s, dim) : median value of iData object
mtimes c = mtimes(a,b) : computes the matrix product of iData objects
pack b = pack(a) : compress iData storage to save memory
pca [b] = pca(X, k) : Principal component analysis of iData object(s)
rmalias s = rmalias(s, AliasName) : removes iData aliases
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references
unique s = unique(a,dim) : set unique iData objects axes with no repetitions