ifit.mccode.org - Description of setaxis
Home > Objects > @iData > setaxis.m
iFit/setaxis
PURPOSE
s = setaxis(s, rank, alias, value) : set iData axes
SYNOPSIS
function this = setaxis(this, rank, alias, value)
DESCRIPTION
 s = setaxis(s, rank, alias, value) : set iData axes
   @iData/setaxis function to set iData axes.
     setaxis(object, rank, alias) defines axis of specified rank as the alias.
       The alias name must exist in the object.
     setaxis(object, rank, alias, value) also sets the alias value.
       The alias name must exist in the object, or it is created and assigned to the axis value.
     setaxis(object, rank, value) sets axis value (possibly creates an alias).
     setaxis(object)              tests all axes
     setaxis(object,'Signal')     sets the Signal to the biggest numerical field
   The input iData object is updated if no output argument is specified.
   The Signal/Monitor corresponds to axis rank 0. Setting its value multiplies
     it by the Monitor and then assigns the Signal.
   Axis 1 is often labelled as 'y' (rows, vertical), 2 as 'x' (columns, horizontal).
   The special syntax a{0} multiplies the value by the Monitor and then assigns
   the Signal, and a{n} assigns the axis of rank n.
     When the assigned value is a char, the axis definition is set.
       a{rank} = 'x'     is the same as   setaxis(a, rank, 'x')
     When the assigned value is numeric, the axis value is set.
       a{rank} = 1:100   is the same as   setaxis(a, rank, 1:100)
 input:  s: object or array (iData)
         rank: rank of the axis (integer)
         alias: name of an alias/field (char)
         value: value of the axis (char/alias/numeric)
 output: s: array (iData)
 ex:     setaxis(iData, 1, 'Temperature') defines Temperature as the 'y' axis (rank 1)
         a{1} =  'Temperature'            does the same
 Version: oct.. 23, 2018
 See also iData, iData/getaxis, iData/get, iData/set, iData/rmaxis
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
isempty isempty(s) : true for empty iData object
isnan b = isnan(s) : True for NaN iData object elements
isnumeric b = isnumeric(s) : True for numeric iData object elements
isvector b = isvector(s) : True for vector iData object
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
ndims d = ndims(s) : get the dimensionality of iData object
not b = not(s) : computes the logical 'not' of iData object
permute c = permute(a, order) : Permute object dimensions from iData objects/arrays
prod s = prod(a,dim) : computes the product of iData objects elements
real b = real(s) : real value of iData object
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
times c = times(a,b) : computes the product of iData objects
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
circshift b=circshift(a, rank, shift): shifts the axis of specified rank by a value
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
dog s= dog(dim,a) : split iData objects elements along dimension
event c = event(a) : build an event list
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
iData
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
interp [b...] = interp(s, ...) : interpolate iData object
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
label b = label(s, alias, label) : Change iData label for a given alias/axis
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
mean b = mean(s, dim) : mean value of iData object
median b = median(s, dim) : median value of iData object
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
pack b = pack(a) : compress iData storage to save memory
pca [b] = pca(X, k) : Principal component analysis of iData object(s)
reshape c = reshape(a) : reshape the object Signal
resize c = resize(a) : resize/rebin the object Signal
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
setaxis s = setaxis(s, rank, alias, value) : set iData axes
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references
unique s = unique(a,dim) : set unique iData objects axes with no repetitions