ifit.mccode.org - Description of size
Home > Objects > @iData > size.m
iFit/size
PURPOSE
size(s) : get iData object size (number of elements)
SYNOPSIS
function y=size(s, dim)
DESCRIPTION
 size(s) : get iData object size (number of elements)
   @iData/size function to get iData object size
 input:  s: object or array (iData)
         dim: optional dimension/rank to inquire
 output: v: size of the iData Signal (double)
 ex:     size(iData), size(iData,1)
 Version: oct.. 23, 2018
 See also iData, iData/disp, iData/get, length
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
size size(s) : get iData object size (number of elements)
subsref b = subsref(a,s) : iData indexed references
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
cat s = cat(dim,a,...) : catenate iData objects elements along dimension
caxis c = caxis(s, h) : Use the 2D/3D data as the colormap (CData property) in current object.
cell [content,fields]=cell(s) : convert iData objects into cells
char c = char(s) : convert iData into character
clim b = clim(s,[ cmin cmax ]) : Reduce iData C axis limits
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
commandhistory commandhistory(s) : show the command history of iData object
conv c = conv(a,b) : computes the convolution of iData objects
copyobj b = copyobj(s) : makes a copy of iData object
corrcoef c = corrcoef(a,b) : correlation coefficient with an iData object
cwt b = cwt(s,dim,scales,wname,'wname',...) : Continuous wavelet transform
disp disp(s) : display iData object (details)
display d = display(s) : display iData object (from command line)
dog s= dog(dim,a) : split iData objects elements along dimension
double d = double(s) : convert iData into doubles
edit edit(s) : edit iData object Signal/Monitor
end b = end(s,index,n) : end value for iData objects
event c = event(a) : build an event list
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
find d = find(s) : find iData signal non zeros values
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
getframe frame = getframe(s, dim, options) : create an iData object thumbnail/frame matrix
gradient g = gradient(a, dim) : computes the gradient (derivative) of iData objects
help c = help(s) : display iData information as a Dialogue window
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
iData
image h = image(r,g,b, option) : Plot up to 3 images overlayed on the RGB channels
imroi imroi: define a region of interest on a data set
interp [b...] = interp(s, ...) : interpolate iData object
isempty isempty(s) : true for empty iData object
isfield b = isfield(s, field) : check existence of field/alias in iData objects
isvector b = isvector(s) : True for vector iData object
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
label b = label(s, alias, label) : Change iData label for a given alias/axis
linspace v = linspace(a,b,n) : creates a linearly spaced vector of objects
load d = load(s, file, loader, ...): iData file loader
logical d = logical(s) : convert iData into logical array
logspace v = logspace(a,b,n) : creates a logarithmically spaced vector of objects
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
mean b = mean(s, dim) : mean value of iData object
median b = median(s, dim) : median value of iData object
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
mtimes c = mtimes(a,b) : computes the matrix product of iData objects
ndims d = ndims(s) : get the dimensionality of iData object
ones s = ones(s,N,M,P,...) : initialize an iData array
pack b = pack(a) : compress iData storage to save memory
pca [b] = pca(X, k) : Principal component analysis of iData object(s)
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
plot h = plot(s, method, ...) : plot iData object
reducevolume h = reducevolume(s, factor) : reduce an iData object size
reshape c = reshape(a) : reshape the object Signal
resize c = resize(a) : resize/rebin the object Signal
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
saveas f = saveas(s, filename, format, options) : save iData object into various data formats
setaxis s = setaxis(s, rank, alias, value) : set iData axes
single d = single(s) : convert iData into single floats
size size(s) : get iData object size (number of elements)
slice slice(s) : Plot a 2D/3D object with slice rendering
smooth Z = smooth(Y) : smooth iData objects
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
subplot h = subplot(s) : plot iData array as subplots
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
xlim b = xlim(s,[ xmin xmax ]) : Reduce iData X axis limits
ylim b = ylim(s,[ ymin ymax ]) : Reduce iData Y axis limits
zeros s = zeros(s,N,M,P,...) : initialize an iData array
zlim b = zlim(s,[ zmin zmax ]) : Reduce iData Z axis limits