ifit.mccode.org - Description of sort
Home > Objects > @iData > sort.m
iFit/sort
PURPOSE
s = sort(a,dim) : Sort iData objects axes in ascending or descending order
SYNOPSIS
function a = sort(a,dim,mode)
DESCRIPTION
 s = sort(a,dim) : Sort iData objects axes in ascending or descending order
   @iData/sort function to sort the data set on its axes
     sort(a,dim) sorts along axis of rank dim.
       If dim=0, sorting is done on all axes.
     sort(a,dim,mode) where mode='ascend' or 'descend' select sorting order
 input:  a: object or array (iData)
         dim: dimension to sort (int)
         mode: sorting order 'ascend' or 'descend'
 output: s: sorted data (iData)
 ex:     c=sort(iData(peaks));
 Version: oct.. 23, 2018
 See also iData, iData/plus, iData/sort, iData/unique
CROSS-REFERENCE INFORMATION
This function calls:
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
isequal c = isequal(a,b) : full numerical equality comparison of iData objects
ndims d = ndims(s) : get the dimensionality of iData object
reshape c = reshape(a) : reshape the object Signal
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
subsref b = subsref(a,s) : iData indexed references
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
pca [b] = pca(X, k) : Principal component analysis of iData object(s)
plot h = plot(s, method, ...) : plot iData object
reducevolume h = reducevolume(s, factor) : reduce an iData object size
setaxis s = setaxis(s, rank, alias, value) : set iData axes
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order