ifit.mccode.org - Description of sqrt
Home > Objects > @iData > sqrt.m
iFit/sqrt
PURPOSE
b = sqrt(s) : square root value of iData object
SYNOPSIS
function a = sqrt(a)
DESCRIPTION
 b = sqrt(s) : square root value of iData object
   @iData/sqrt function to return the square root value of data sets
 input:  s: object or array (iData)
 output: b: object or array (iData)
 ex:     b=sqrt(a);
 Version: oct.. 23, 2018
 See also iData, iData/sqrt, iData/power
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
event c = event(a) : build an event list
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
imroi imroi: define a region of interest on a data set
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
std [half_width, center] = std(s, dim) : standard deviation of iData
subplot h = subplot(s) : plot iData array as subplots
subsref b = subsref(a,s) : iData indexed references