ifit.mccode.org - Description of std
Home > Objects > @iData > std.m
iFit/std
PURPOSE
[half_width, center] = std(s, dim) : standard deviation of iData
SYNOPSIS
function [s, f] = std(a, dim)
DESCRIPTION
 [half_width, center] = std(s, dim) : standard deviation of iData
   @iData/std function to compute the standard deviation of objects, that is
     their gaussian half width (second moment). Optionally, the distribution
     center (first moment) can be returned as well.
   std(a, dim) computes standard deviation along axis of rank 'dim'.
     When omitted, dim is set to 1.
   std(a, -dim)
     Using a negative dimension will subtract minimum signal value to signal
       before computation of std, that is remove background. This may be
       needed to avoid an imaginary result.
   std(a, 0) computes std(Signal) and mean(Signal).
 input:  a: object or array (iData/array of)
         dim: dimension to use. Negative dim subtract background (int/array)
 output: half_width: standard deviation (scalar/array)
         center:     center of distribution (scalar/array)
 ex:     a=iData(peaks); c=std(a);
 Version: oct.. 23, 2018
 See also iData, iData/median, iData/mean
CROSS-REFERENCE INFORMATION
This function calls:
abs b = abs(s) : absolute value of iData object
double d = double(s) : convert iData into doubles
end b = end(s,index,n) : end value for iData objects
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
isempty isempty(s) : true for empty iData object
isfloat b = isfloat(s) : True for float iData object elements
isreal b = isreal(s) : True for real iData object elements
isvector b = isvector(s) : True for vector iData object
mean b = mean(s, dim) : mean value of iData object
meshgrid s = meshgrid(a) : transforms an iData object so that its axes are grids
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
ndims d = ndims(s) : get the dimensionality of iData object
sqrt b = sqrt(s) : square root value of iData object
std [half_width, center] = std(s, dim) : standard deviation of iData
sum s = sum(a,dim) : computes the sum of iData objects elements
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
cart2sph s = cart2sph(a,dim) : cartesian to polar/spherical representation of iData objects
disp disp(s) : display iData object (details)
help c = help(s) : display iData information as a Dialogue window
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
pca [b] = pca(X, k) : Principal component analysis of iData object(s)
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
std [half_width, center] = std(s, dim) : standard deviation of iData