ifit.mccode.org - Description of subplot
Home > Objects > @iData > subplot.m
iFit/subplot
PURPOSE
h = subplot(s) : plot iData array as subplots
SYNOPSIS
function h=subplot(a, varargin)
DESCRIPTION
 h = subplot(s) : plot iData array as subplots
   @iData/subplot plot each iData element in a subplot
     subplot(a, [])    uses the best subplot fit
     subplot(a, [m n]) uses an m x n subplot grid
     subplot(a, [m n], options) sends options to the plot
 input:  s: object or array (iData)
         [m n]: optional subplot grid dimensions
         additional arguments are passed to the plot method (e.g. color, plot type, ...)
 output: h: plot handles (double)
 ex:     subplot([ a a ])
 Version: oct.. 23, 2018
 See also iData, iData/plot
CROSS-REFERENCE INFORMATION
This function calls:
ceil b = ceil(s) : upper integer round of iData object
end b = end(s,index,n) : end value for iData objects
floor b = floor(s) : lower integer round of iData object
isempty isempty(s) : true for empty iData object
isnumeric b = isnumeric(s) : True for numeric iData object elements
plot h = plot(s, method, ...) : plot iData object
size size(s) : get iData object size (number of elements)
sqrt b = sqrt(s) : square root value of iData object
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
subplot h = subplot(s) : plot iData array as subplots
This function is called by:
subplot h = subplot(s) : plot iData array as subplots