ifit.mccode.org - Description of subsref
Home > Objects > @iData > subsref.m
iFit/subsref
PURPOSE
b = subsref(a,s) : iData indexed references
SYNOPSIS
function b = subsref(a,S)
DESCRIPTION
 b = subsref(a,s) : iData indexed references
   @iData/subsref: function returns subset indexed references
     such as a(1:2) or a.field.
   The special syntax a{0} where a is a single iData returns the
     Signal/Monitor, and a{n} returns the axis of rank n.
   When given an iFunc model, the iData axes are used to evaluate the model
     signal = iData(model)
     signal = iData(model, p)  uses given parameters
 Version: oct.. 23, 2018
 See also iData, iData/subsasgn
CROSS-REFERENCE INFORMATION
This function calls:
abs b = abs(s) : absolute value of iData object
char c = char(s) : convert iData into character
copyobj b = copyobj(s) : makes a copy of iData object
double d = double(s) : convert iData into doubles
end b = end(s,index,n) : end value for iData objects
find d = find(s) : find iData signal non zeros values
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getalias [link, label,names] = getalias(s, 'AliasName') : get iData alias
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
isempty isempty(s) : true for empty iData object
isfield b = isfield(s, field) : check existence of field/alias in iData objects
islogical b = islogical(s) : True for logical iData object elements
isnan b = isnan(s) : True for NaN iData object elements
isnumeric b = isnumeric(s) : True for numeric iData object elements
isscalar b = isscalar(s) : True for scalar iData objects
isvector b = isvector(s) : True for vector iData object
max [m,id] = max(a,b, dim) : computes the maximum value of iData object(s)
min [m,id] = min(a,b, dim) : computes the maximum value of iData object(s)
ndims d = ndims(s) : get the dimensionality of iData object
not b = not(s) : computes the logical 'not' of iData object
prod s = prod(a,dim) : computes the product of iData objects elements
reshape c = reshape(a) : reshape the object Signal
set [s,...] = set(s, 'PropertyName', Propertyvalue, ...) : set iData properties
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
sqrt b = sqrt(s) : square root value of iData object
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
subsref b = subsref(a,s) : iData indexed references
times c = times(a,b) : computes the product of iData objects
This function is called by:
clim b = clim(s,[ cmin cmax ]) : Reduce iData C axis limits
dog s= dog(dim,a) : split iData objects elements along dimension
fill FILL fill-in over missing data
fits [pars,criteria,message,output] = fits(a, model, pars, options, constraints, ...) : fit data set on a model
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
getframe frame = getframe(s, dim, options) : create an iData object thumbnail/frame matrix
hist hist(a, axis1, axis2, ...) computes the accumulated histogram from event data sets
interp [b...] = interp(s, ...) : interpolate iData object
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
pca [b] = pca(X, k) : Principal component analysis of iData object(s)
reducevolume h = reducevolume(s, factor) : reduce an iData object size
resize c = resize(a) : resize/rebin the object Signal
size size(s) : get iData object size (number of elements)
smooth Z = smooth(Y) : smooth iData objects
sort s = sort(a,dim) : Sort iData objects axes in ascending or descending order
squeeze c = squeeze(a) : remove singleton dimensions from iData objects/arrays
subsasgn b = subsasgn(a,index,b) : iData indexed assignement
subsref b = subsref(a,s) : iData indexed references
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
xlim b = xlim(s,[ xmin xmax ]) : Reduce iData X axis limits
ylim b = ylim(s,[ ymin ymax ]) : Reduce iData Y axis limits
zlim b = zlim(s,[ zmin zmax ]) : Reduce iData Z axis limits