ifit.mccode.org - Description of sum
Home > Objects > @iData > sum.m
iFit/sum
PURPOSE
s = sum(a,dim) : computes the sum of iData objects elements
SYNOPSIS
function [s,sigma] = sum(a,dim)
DESCRIPTION
 s = sum(a,dim) : computes the sum of iData objects elements
   @iData/sum function to compute the sum of the elements of the data set
     sum(a,dim) accumulates along axis of rank dim. The axis is then removed.
       If dim=0, sum is done on all axes and the total is returned as a scalar value.
         In this case, a second output argument holds the error bar.
       If dim='radial', the sum is done radially (R=sqrt(sum(axes^2)).
       sum(a,1) accumulates on first dimension (columns).
       camproj accumulates on all other axes.
 input:  a: object or array (iData/array of)
         dim: dimension to accumulate (int/array of, or 'radial')
 output: s: sum of elements (iData/scalar)
 ex:     c=sum(a);
 Version: oct.. 23, 2018
 See also iData, iData/plus, iData/prod, iData/cumsum, iData/mean,
 iData/camproj, iData/trapz, iData/cart2sph
CROSS-REFERENCE INFORMATION
This function calls:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
end b = end(s,index,n) : end value for iData objects
This function is called by:
disp disp(s) : display iData object (details)
event c = event(a) : build an event list
help c = help(s) : display iData information as a Dialogue window
imroi imroi: define a region of interest on a data set
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
load d = load(s, file, loader, ...): iData file loader
peaks [half_width, center, amplitude, baseline] = peaks(s, dim, m) : peak position and width of iData
saveas f = saveas(s, filename, format, options) : save iData object into various data formats
std [half_width, center] = std(s, dim) : standard deviation of iData