ifit.mccode.org - Description of transpose
Home > Objects > @iData > transpose.m
iFit/transpose
PURPOSE
b = transpose(s) : non-conjugate transpose of iData object
SYNOPSIS
function a = transpose(a)
DESCRIPTION
 b = transpose(s) : non-conjugate transpose of iData object
   @iData/transpose function to return the non-conjugate transpose of data sets
     which corresponds to syntax: b = s.'
   When the argument is an iData array, each element is transposed. To
     transpose the array itself, use ctranspose(s) or b=s'
 input:  s: object or array (iData)
 output: b: object or array (iData)
 ex:     b=transpose(a);
 Version: oct.. 23, 2018
 See also iData, iData/transpose, iData/ctranspose, iData/setaxis, iData/getaxis
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
ndims d = ndims(s) : get the dimensionality of iData object
permute c = permute(a, order) : Permute object dimensions from iData objects/arrays
This function is called by:
char c = char(s) : convert iData into character
disp disp(s) : display iData object (details)
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
help c = help(s) : display iData information as a Dialogue window
interp [b...] = interp(s, ...) : interpolate iData object
plot h = plot(s, method, ...) : plot iData object
subsasgn b = subsasgn(a,index,b) : iData indexed assignement