ifit.mccode.org - Description of unique
Home > Objects > @iData > unique.m
iFit/unique
PURPOSE
s = unique(a,dim) : set unique iData objects axes with no repetitions
SYNOPSIS
function s = unique(a,dim,mode)
DESCRIPTION
 s = unique(a,dim) : set unique iData objects axes with no repetitions
   @iData/unique function to remove duplicates along data set axes
     unique(a,dim) set unique along axis of rank dim.
       If dim=0, operates on all axes.
   Alternatively, you can use 'isequal' to find unique data sets and remove
     duplicates.
 input:  a: object or array (iData)
         dim: dimension to unique (int)
 output: s: data set with unique axes (iData)
 ex:     c=unique(a);
 Version: oct.. 23, 2018
 See also iData, iData/plus, iData/unique, iData/sort, iData/isequal
CROSS-REFERENCE INFORMATION
This function calls:
copyobj b = copyobj(s) : makes a copy of iData object
end b = end(s,index,n) : end value for iData objects
get [...] = get(s, 'PropertyName', ...) : get iData object properties
getaxis [val, lab] = getaxis(s, AxisIndex) : get iData axis value and label
iData
ndims d = ndims(s) : get the dimensionality of iData object
reshape c = reshape(a) : reshape the object Signal
setalias [s,...] = setalias(s, AliasName, AliasLink, {AliasLabel}) : set iData aliases
setaxis s = setaxis(s, rank, alias, value) : set iData axes
size size(s) : get iData object size (number of elements)
subsref b = subsref(a,s) : iData indexed references
unique s = unique(a,dim) : set unique iData objects axes with no repetitions
zeros s = zeros(s,N,M,P,...) : initialize an iData array
This function is called by:
edit edit(s) : edit iData object Signal/Monitor
fft c = fft(a) : computes the Discrete Fourier transform of iData objects
fileattrib [attribute, link] = fileattrib(s, field) : return a field Attribute
findfield [match, types, nelements]=findfield(iData, field, option) : look for iData fields
findobj [s,...]=findobj(s,...) : look for existing iData objects
jacobian [b, j] = jacobian(a, new_axes, 'new_axes_labels'...) : computes the gradient (derivative) of iData objects
kmeans [b,c] = kmeans(X, k) : k-means clustering of iData object
load d = load(s, file, loader, ...): iData file loader
rotate s = rotate(a, theta) : computes the rotation of iData objects around the origin
slice slice(s) : Plot a 2D/3D object with slice rendering
subsindex d = subsindex(s) : subscript index for iData objects
unique s = unique(a,dim) : set unique iData objects axes with no repetitions