ifit.mccode.org - Description of xlabel
Home > Objects > @iData > xlabel.m
iFit/xlabel
PURPOSE
b = xlabel(s,label) : Change iData X axis label
SYNOPSIS
function a = xlabel(a, lab)
DESCRIPTION
 b = xlabel(s,label) : Change iData X axis label
   @iData/xlabel function to change the X axis (rank 2, columns) label
     xlabel(s) returns the current X axis label
   The input iData object is updated if no output argument is specified.
 input:  s: object or array (iData)
         label: new X label (char/cellstr)
 output: b: object or array (iData)
 ex:     b=xlabel(a);
 Version: oct.. 23, 2018
 See also iData, iData/plot, iData/label, iData/ylabel, iData/zlabel, iData/clabel
CROSS-REFERENCE INFORMATION
This function calls:
end b = end(s,index,n) : end value for iData objects
isempty isempty(s) : true for empty iData object
isvector b = isvector(s) : True for vector iData object
label b = label(s, alias, label) : Change iData label for a given alias/axis
This function is called by:
camproj s = camproj(a,dim) : projection/radial integration of iData objects elements
colormap h=colormap(objects, colormaps, ..., options): Produce surfaces from iData 2D objects with different colormaps
edit edit(s) : edit iData object Signal/Monitor
getframe frame = getframe(s, dim, options) : create an iData object thumbnail/frame matrix
help c = help(s) : display iData information as a Dialogue window
plot h = plot(s, method, ...) : plot iData object
slice slice(s) : Plot a 2D/3D object with slice rendering